### ISSUE TITLE
Question: Intel® UHD Graphics 620 vs. MYRIAD VPU

### ISSUE THREAD

**Issue by mszuyx** [openvinotoolkit/openvino#10215]
Our deployment machine, [up xtreme ](https://up-board.org/up-xtreme/) has an integrated GPU: **Mesa Intel® UHD Graphics 620**.

As we test our FP16 model, we observe that there is a huge performance boost when deploying the FP16 model to the GPU. (Changing the model from FP32 to FP16 and deploy on CPU only gives ~ 1FPS  improvement, but on GPU, **it is 48% higher**)

We are also interesting on trying the [MYRIAD VPU](https://up-shop.org/up-ai-core-x-series-myriadtmx.html). The up xtreme board support up to x6 VPU stack add-on. We are wondering how many VPU we should get (rule of thumb estimation) to match or out performs the UHD Graphics 620? (Because otherwise we should just go with the GPU)

Thanks! :  )

**Comment by Iffa-Meah** [comment]
Hi,

Choosing the right data precision in combination with specific hardware is important. You may refer [here](https://www.intel.com/content/www/us/en/developer/articles/technical/should-i-choose-fp16-or-fp32-for-my-deep-learning-model.html) to see which precision is compatible with which hardware.

The CPU supports FP32 and Int8 while GPU supports FP16, FP32 (but preferred FP16). This is why you were getting higher improvement on GPU compared to CPU.

Generally, the measurements of performance involve 4 key parameters:
Throughput: number of inferences delivered within a latency threshold (eg FPS)
Efficiency: power efficiency (throughput/watt)
Value: Application performance in throughput per dollar of system cost (performance-per-cost)
Latency: synchronous execution of inference requests and reported in milliseconds

The GPU hardware definitely would have better performance than VPU devices since they have more processing power for graphics. This is one of the reasons why they are meant to be used in gaming.

Meanwhile, the VPU devices are meant for acceleration purposes and would be really helpful especially in the case of the main processing power had been exhausted.

However, stacking the VPU devices **might** change that (if the cost is relevant compared to purchasing a single GPU hardware). 

Looking at this [Benchmark Result](https://docs.openvino.ai/latest/openvino_docs_performance_benchmarks_openvino.html#faster-rcnn-resnet50-coco-tf-600x1024) (I'm focusing on the **faster-rcnn-resnet50-coco-TF [600x1024]** model), a single VPU device produce: Throughput of 0.6. If max 8 VPU is used: 0.6 x 8 =  4.8
Efficiency of 0.24. For max 8 VPU: 0.24 x 8 = 1.92
Value of 0.008. Max 8 VPU: 0.008 x 8 = 0.064

**Note that the values for 8 VPU above are theoretical .**

**Comment by mszuyx** [comment]
@Iffa-Meah Thanks! These are great references!

Here are some follow up questions:

- Is there a reason you made the estimation based on the performance of NCS2 instead of MYRIAD?
- The benchmark chart doesn't show FP16's performance on GPU, so it is little hard to put things into perspective (FP16 in GPU vs. VPU). From your experience, would the throughput of INT8 and FP16 be similar on GPU?

Thanks!
Yu

**Comment by Iffa-Meah** [comment]
@mszuyx ,

both NCS2 and the device you showed in the link use the same VPU (  Intel Movidius Myriad X VPU ) but again, as I said that calculation is theoretical since there are other factors that might affect the performance. I used 8 because, in that link, max is UP AI CORE XP8 (MYRIAD X*8).

If you look closely, there's iGPU (Intel GPU), but the model precision is not in FP16 tho. Note that the OpenVINO™ toolkit is **officially supported** by Intel hardware only. You may refer [here](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_GPU.html#doxid-openvino-docs-i-e-d-g-supported-plugins-g-p-u).

To get an exact result, the best would be to test on the actual device itself, if the circumstances are not available in the provided performance results.

Probably this explanation would help you : [Choosing the Right Precision](https://www.youtube.com/watch?v=RF8ypHyiKrY)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
