### ISSUE TITLE
Cannot load network when containing v0 Convolution layer.

### ISSUE THREAD

**Issue by Maosquerade** [openvinotoolkit/openvino#1082]
I've tried to build a network with ngraph. And I want that to operate a convolution operation with bias. I noticed that there are v0 and v1 Convolution Node and it seems that they do the same job.
However, it seems only v0 Convolution Node can add bias opeartion while v0 convolution cannot load network.
```
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Error of validate layer: Convolution_3 with type: Convolution. Layer is not instance of ConvolutionLayer class
```
I would like to know what is the difference between v0 and v1 convolution node, and if there's possible ways to add a bias operation with v1 convolution Node?

**Comment by ilyachur** [comment]
Hi @Maosquerade 

Inference Engine doesn't support operations from 0 opset. v0::Convolution is from opset0, please use v1 Convolution operation.

All information about supported operations and opsets you can find [here](https://docs.openvinotoolkit.org/latest/_docs_ops_opset.html).

In order to add biases to v1 convolution layer please use Add operation after the convolution layer. It will look like:
[weights]------------|         [biases]------|
[data]----------[convolution]----[add]--[...]

**Comment by Maosquerade** [comment]
Thanks for this Information about opset!
I will try this method for convolution bias layer, thanks again!

**Comment by ilyachur** [comment]
@Maosquerade Do you have any update about this issue? Did my advice help to resolve the issue?

**Comment by Maosquerade** [comment]
@ilyachur Hi，That works！Thanks a lot!

**Comment by ilyachur** [comment]
@Maosquerade Ok, in this case I will close the issue. Feel free to reopen it if you have any questions.
