### ISSUE TITLE
Does openvino support  dynamic length  input  in NLP as text length is variable?

### ISSUE THREAD

**Issue by MrRace** [openvinotoolkit/openvino#10831]
I have converted my onnx model to openvino use the cmd like:
```
python3 mo.py --input_model /home/model.onnx --input "input_ids[1 128],attention_mask[1 128],token_type_ids[1 128]" --output_dir /home/openvino/
```
When do inference, the text input must be the same length as above max length(128) or do padding, but in fact the text length is variable and do padding would take some time. Is there some way to achieve this purpose？ Thanks a lot~

**Comment by jgespino** [comment]
Hi @MrRace

With the current release OpenVINO 2021.4.2 you would need to call [reshape method](https://docs.openvino.ai/latest/openvino_docs_IE_DG_ShapeInference.html) before loading the model. However, we are currently working to support Dynamic Shapes for the next software release. If you would like to test this, please take a look at the [Dynamic Shapes User Guide](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_DynamicShapes.html) and download the [OpenVINO™ toolkit pre-release](https://github.com/openvinotoolkit/openvino/releases) package. 

Regards,
Jesus

**Comment by MrRace** [comment]
@jgespino Thank you for your prompt reply. I try to  follow the example in [ShapeInference](https://docs.openvino.ai/latest/openvino_docs_IE_DG_ShapeInference.html) and do reshape.
I want to reshape the network so that can support text which length is 64. Therefore  i reshape the network like that:
```
network = ie_core_handler.read_network(model=XML_PATH, weights=BIN_PATH)
input_layer = next(iter(network.input_info))
print(f"input layout: {network.input_info[input_layer].layout}")
print(f"input shape: {network.input_info[input_layer].tensor_desc.dims}")
print(f"output shape: {network.outputs[output_layer].shape}")
network.reshape({input_layer: [1, 64]})
"""
input layout: NC
input shape: [1, 128]
output shape: [1, 128, 768]
"""
```
however some error happens:
```
Traceback (most recent call last):
  File "check_openvino.py", line 37, in <module>
    network.reshape({input_layer: [1, 64]})
  File "ie_api.pyx", line 1870, in openvino.inference_engine.ie_api.IENetwork.reshape
RuntimeError: Check 'PartialShape::broadcast_merge_into( pshape, node->get_input_partial_shape(i), autob)' failed at core/src/op/util/elementwise_args.cpp:40:
While validating node 'v1::Add Add_73 (MatMul_70[0]:f32{1,12,128,128}, Sub_4/Fused_Add_[0]:f32{1,1,1,64}) -> (f32{1,12,128,128})' with friendly_name 'Add_73':
Argument shapes are inconsistent.
``` 
By the way, each time  the length of the text changes, I must reshape the network before load_network?

**Comment by dmitry-gorokhov** [comment]
@MrRace With latest OpenVINO state (master branch or pre-release package that @jgespino mentioned) you can get benefit from native dynamic shapes support on CPU. This means that you compile your model with undefined shapes which gives you ability to send to Infer() text with different length on each iteration without any additional manipulations with the network or data. See https://docs.openvino.ai/nightly/openvino_docs_OV_UG_DynamicShapes.html for details. Such approach should provide best performance.

If approach mentioned above not applicable in your case (you need this functional not only on CPU or smt else) the recommendation will be to pad input data with zeros to fit static model shape. In other words if you know max possible text length you can compile the model with static shape equal to max length and pad input data if required. 

Reshaping the model each time length changes is also an option but the slowest one due to the fact that reshape+load_model is quite time consuming procedure (might required much more time than inference itself).
Regarding reshape issue I would ask @jane-intel to comment. That can be an issue with the model itself - not all of them are reshapable.

**Comment by MrRace** [comment]
@dmitry-gorokhov Thanks for your advice~  In https://docs.openvino.ai/nightly/openvino_docs_OV_UG_DynamicShapes.html  only have C++ example, Could you provide python  examples? Best Regards~

**Comment by dmitry-gorokhov** [comment]
@MrRace Python code snippets have been added. Please use the same link
