### ISSUE TITLE
[Bug] when I load network, dynamic output shape error

### ISSUE THREAD

**Issue by RelayZ** [openvinotoolkit/openvino#11064]
- OpenVINO=> :2022.1:
- Operating System / Platform => :Ubuntu20.04:
- Compiler => :python:
- Problem classification => :Loading onnx model:

##### Detailed description
When I want to load my ONNX model, `RuntimeError: CPU plug-in can't load a model with Dynamic Output Shapes via Legacy API` is displayed. But when I initialize the other models, it makes sense. My loading code is as follows:

``` python
from openvino.inference_engine import IECore
import numpy as np
ie = IECore()
model="/home/relay/projects/PaddleAIStudio/PaddleDetection/output_inference_openvino2022/yolov3_mobilenet_v3_large_ssld_270e_voc.xml"
net = ie.read_network(model=model)
exec_net = ie.load_network(network=net, device_name="CPU")
```

##### error info：
```
  exec_net = ie.load_network(network=net, device_name="CPU")
  File "ie_api.pyx", line 413, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 457, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: CPU plug-in can't load a model with dynamic output shapes via legacy API.
```

I've heard [here](https://github.com/openvinotoolkit/openvino/issues/8613) that OpenVino2022.1 can handle dynamic output shapes.So I want to know if there is a new API, thank you.

**Comment by ilya-lavrenov** [comment]
Hi @RelayZ 

Right, starting with OpenVINO 2022.1, CPU plugin supports dynamic shapes and this support implies not only output dynamic shapes, but also input dynamic shapes (but number of dimensions in shapes must be known) - see [Dynamic shapes in OpenVINO 2022.1](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_DynamicShapes.html).

But in order to have this feature in your application, you should use OpenVINO Runtime API 2.0, see [Migration to OpenVINO 2.0](https://docs.openvino.ai/nightly/openvino_2_0_transition_guide.html) to understand what is it and how to use new API. 

Using old Inference Engine API you cannot use _dynamic shapes feature_ because IE API does not have structures / classes to represent dynamic shapes (both input and output ones).

You can try OpenVINO 2.0 via pre-release _2022.1.0.dev20220316_ package on [PyPi](https://pypi.org/project/openvino/2022.1.0.dev20220316/)

Thanks.

**Comment by RelayZ** [comment]
Thanks for the directions you give, I'm sure it will work.
