### ISSUE TITLE
Are there plans to support dpc++ or oneAPI ecology？

### ISSUE THREAD

**Issue by malixian** [openvinotoolkit/openvino#11395]
I think there are two necessities to support dpc++ or oneAPI ecology：
1. Support user customized Op；
2. Implement end-to-end optimization between graphs and operators, similar to tvm.
3. suppport oneDNN to supply differnet DNN libraries from hardware vendors. 

Is my idea reasonable?  Does openvino also have a corresponding development plan?

Thanks.

**Comment by ilya-lavrenov** [comment]
@malixian could you be more specific?

**Comment by malixian** [comment]
> @malixian could you be more specific?
Specifically, I would like to know whether openvino has the ability to do the following things, or be supported in the future？

First. For example, will openvino support the operator implemented the dpc++ programming model?  

Second. Will learn from some tvm ideas for code generation? For example, the integrated operator is not implemented in the library. Can it be automatically generated by the compiler?

**Comment by ilya-lavrenov** [comment]
> First. For example, will openvino support the operator implemented the dpc++ programming model?

We are thinking about this, but we need to covers more HW, because currently DPC++ supports only CPU and GPU, while OpenVINO supports more

> Second. Will learn from some tvm ideas for code generation? For example, if the fused operator is not implemented in the dnn library. Can it be automatically generated by the compiler?

We have fused operators on CPU implemented via https://github.com/openvinotoolkit/openvino/wiki/SnippetS

> suppport oneDNN to supply differnet DNN libraries from hardware vendors.

OneDNN already is underneath for CPU and GPU plugins

**Comment by malixian** [comment]
> We are thinking about this, but we need to covers more HW, because currently DPC++ supports only CPU and GPU, while OpenVINO supports more

I don't quite understand this problem, OpenVINO's support for different devices should be OpenCL, while DPC++ supports OpenCL. So why it's necessary to cover more HW.

**Comment by ilya-lavrenov** [comment]
> I don't quite understand this problem, OpenVINO's support for different devices should be OpenCL, while DPC++ supports OpenCL

It's not a problem, this is our desire to have unified solution for writing extensions for all HW.
We don't have just a goal to have DPC++ extensions - why they are needed? We already have extensions for [CPU and GPU](https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Intro.html).
Adding just one more way to write code for GPU is not what we want, because OpenCL already covers this.

**Comment by malixian** [comment]
Thanks for your replay
