### ISSUE TITLE
How to set cpu usage when used within onnxruntime

### ISSUE THREAD

**Issue by Liujingxiu23** [openvinotoolkit/openvino#1142]
I combine onnxruntime with openvino and try to use openvino as the EP in onnxruntime. 

I use "export OMP_NUM_THREADS=1" as well as the following code to set the thread num as 1.
g_ort->SetIntraOpNumThreads(session_options, 1);
g_ort->SetInterOpNumThreads(session_options, 1);
When default provider (CPUExeProvider)is used, using top command to check the cpu usage , "%CPU" is less than or equal to 100.

But when I used the following code to set openvino as the provider
Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_OpenVINO(session_options, ""));
top command show "%CPU" larger than 100, about 1000~3000.

How to control the CPU useage when openvino is the provider in onnxruntime?

**Comment by ilya-lavrenov** [comment]
@Liujingxiu23 OpenVINO uses TBB internally, so OpenMP variables don't work here.

In order to control CPU plugin behavior related to threads usage you can use:
- `CPU_THREADS_NUM` https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/include/ie_plugin_config.hpp#L192
- `CPU_THROUGHPUT_STREAMS` https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/include/ie_plugin_config.hpp#L220

**Comment by Liujingxiu23** [comment]
@ilya-lavrenov 
Thank you for your relpy.

I add "config.insert({"CPU_THREADS_NUM", "1"});" in onnxruntime/core/providers/openvino/backends/basic_backend.cc after line 34 and rebuild onnxruntime. Then code can be run in one cpu core. But the speed is really slow.

The same model, runing with the same input, in cpu and thread=1, using libtorch or onnxruntime with default ep, the inference time is about 70ms. But using onnxruntime with openvino as the ep, the time is about 1100+ ms.

**Comment by jgespino** [comment]
Closing, please re-open if assistance is still needed.
