### ISSUE TITLE
Error converting onnx model to OpenVino  

### ISSUE THREAD

**Issue by Dandelion111** [openvinotoolkit/openvino#11488]
The commands and errors for conversion are as follows:
![image](https://user-images.githubusercontent.com/48303408/162408232-a6db15b2-eace-4ec1-adf9-7045263c5a1b.png)

**Comment by mateusztabaka** [comment]
Hi,
what openvino version you use? Can you share the onnx model?

**Comment by Dandelion111** [comment]
> Hi, what openvino version you use? Can you share the onnx model?
Thank you for the response！
openvino version: 2021.2
How can I send the model to you?

**Comment by mateusztabaka** [comment]
You can try to upload the model here

**Comment by Dandelion111** [comment]
> You can try to upload the model here
[model.zip](https://github.com/openvinotoolkit/openvino/files/8451336/model.zip)
input-shape [1, 3,320,320]

**Comment by mateusztabaka** [comment]
Your model has dynamism on the first dimension in 'image' input. With such an old version of openvino (2021.2), you should pass --input_shape parameter to model optimizer command line that will specify the shape of the input (e.g. [1, 3, 320, 320]).
Unfortunately I haven't tried that myself, since 2021.2 is pretty old and I wanted to encourage you to update to latest release (which is 2022.1). However in your case, you will face some issues with this release as well.
I was able to fix the issues, but it will take some time to have them merged to master. If you want to try them (and want to compile openvino from sources), you can pull my branch https://github.com/mateusztabaka/openvino/tree/issue_11488 and see if that resolves you issue. 
Please note that, since 2022.1 release supports dynamic shapes, in your case you're not required to pass '--input_shape' to model optimizer, but I encourage to do so if you know your input shape upfront.

**Comment by Dandelion111** [comment]
> Your model has dynamism on the first dimension in 'image' input. With such an old version of openvino (2021.2), you should pass --input_shape parameter to model optimizer command line that will specify the shape of the input (e.g. [1, 3, 320, 320]). Unfortunately I haven't tried that myself, since 2021.2 is pretty old and I wanted to encourage you to update to latest release (which is 2022.1). However in your case, you will face some issues with this release as well. I was able to fix the issues, but it will take some time to have them merged to master. If you want to try the fix (and want to compile openvino from sources), you can pull my branch https://github.com/mateusztabaka/openvino/tree/issue_11488 and see if that resolves you issue. Please note that, since 2022.1 release supports dynamic shapes, in your case you're not required to pass '--input_shape' to model optimizer, but I encourage you to do so if you know your input shape upfront.

Thanks for guidance!

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
