### ISSUE TITLE
Model Optimizer does not support array dimension value of -1

### ISSUE THREAD

**Issue by stefan-andritoiu** [openvinotoolkit/openvino#12]
Received this error, when running model_optimizer on a frozen Tensorflow graph.
_[ ERROR ]  Shape [ -1 224 224   3] is not fully defined for output 0 of "input". Use --input_shape with positive integers to override model input shapes._

From the  numpy.reshape() documentation (https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html):
"One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

The error appears because the model_optimizer requires all dimensions to be positive. And yes, if you use --input_shape [1,3,224,224] as command-line parameter, it works perfectly fine.

The issue here is that it's common practice in the entire "ML in python" field to have the batch size -1, as you don't want to constrict the model to a fixed batch size, but inferred at run time.
And almost every Tensorflow model uses -1 as batch size. So this will be an error that will pop-up every time someone just downloads a model from the internet and tries to optimize it. 

Are there any plans of adding support for this type of **"run-time inferred dimension"** ?

**Comment by stefan-andritoiu** [comment]
numpy offers this feature where one dimension can be left out as it can be inferred from the total number of elements and the other dimension.
This is very often _(almost always)_ used for defining the batch-size of model as you don't want to constrict the model to have a fixed batch size. The batch size will be inferred from the size of the input you give it and the other dimensions at runtime. 
You will often see inputs defined with shape [-1,3,300,300] (for example: batch, channel, height, width)

Now unfortunately, this is not something the **model_optimizer** can set up as this dimension can only be inferred at run time. Best solution would be to add this concept of a **"run-time inferred dimension" placeholder** (the -1 in numpy) to the **model_optimizer** and inference engine (basically to OpenVINO). 
So this placeholder is something that needs to be recognized by the **model_optimizer**, passed along unchanged, and kept in the **Intermediate Representation** (the .xml file to be exact). And then the **inference_engine**, when running the model, will replace the placeholder with the calculated value.

Seeing as how, batch size is mostly relevant for the training part, and not so much for inference; it's safe to assume the batch size (if the model defines it as -1) can be default set to 1. And give the option to be manually overridden by functions in the OpenVINO API.

But this kind of approach (default setting any -1 to 1) would prove problematic if you have any other dimension (other than the batch size) defined as -1.
But something like this would be very bad practice on the model creator's side, and I doubt it would be a common thing any developer would do.

**Comment by shubha-ramani** [comment]
stefan it is under discussion. I have informed the Model Optimizer development team of your request.

**Comment by lazarevevgeny** [comment]
@stefan-andritoiu the current workflow is that you have to specify positive values for all dimensions of the model input during the model conversion. Then you can change the batch size (and the spatial dimensions of the image also) at runtime using the Inference Engine API method `InferenceEngine::CNNNetwork::reshape`.

There are no plans to support dynamic shapes in the Model Optimizer.

**Comment by elvin-nnov** [comment]
We cannot have undefined shape in IR because model eventually must be loaded to IE plugin and all shapes must be defined. Even for dynamic batch that I will mention later, you must have all values defined.

Thus, IR have all values predefined and there might be a question "what should I do if I want to change input shape"? The answer on this question - shape propagation feature in Inference Engine or explicit call of setBatchSize for ICNNNetwork. There are two different functions functionality of which are overlapped and there might be a change in API in this regard to leave only one approach or to address issues with ` ICNNNetwork::setBatchSize`
 
After loading model from IR and before loading model to plugin, you can change input shape or batch size as a partial use case of changing shape.
Here is an example:
`        SizeVector input_shape;
        std::tie(input_name, input_shape) = *input_shapes.begin();
        cv::Mat image = cv::imread(input_image_path);
        input_shape[0] = batch_size;
        input_shape[2] = image.rows;
        input_shape[3] = image.cols;
        input_shapes[input_name] = input_shape;
        std::cout << "Resizing network to the image size = [" << image.rows << "x" << image.cols << "] "
                  << "with batch = " << batch_size << std::endl;
        network.reshape(input_shapes);`

Function ICNNNetwork::reshape might fail if layer cannot do shape propagation. For example if network has fully connected layers and if you want to change width ot heihgt.

This approach should be used for changing of batch size for network. It works for all cases.


As an alternative to shape propagation - there is a function ICNNNetwork::setBatchSize. Call of this function is simple, but it has many limitation. This function does not use for now shape inference and assumes that batch dimension is always the first. And it just change this value for all layers. It works well for many networks but there are a lot of networks having layers which do not have dedicated dimension for batch. For example Detection Output layer or Proposal. In this case there might be unpredictable behaviour till the application crash. 
Limitations are described in the comment for ICNNNetwork.
Use of this function is simple but we recommend to use shape inference instead even for changing of batch.


Previous two examples described use cases of changing shapes before loading network to plugin. After loading network to plugin, you cannot change anything in the inference configuration. All actions on ICNNNetwork will not be applied to already loaded network and their representatives ExecutableNetwork/InferRequest.

There is one more use case - dynamic batch size which can be changed from inference to infernece. Even in this case the batch size must be defined on moment of loading network to plugin. This batch size means the maximum batch which you cannot exceed for dynamic batch for certain ExecutableNetwork. The second prerequisite to turn on this dynamic batch - send config key PluginConfigParams::KEY_DYN_BATCH_ENABLED to YES.
And third prerequisite - you can use IInferRequest::SetBatch() to define of batch size for next infer calls
This function has same limitations for now as `ICNNNetwork::setBatchSize`

**Comment by lazarevevgeny** [comment]
@stefan-andritoiu could you close the ticket if you don't have any more comments?

**Comment by jlygit** [comment]
@elvin-nnov 

I change twe input shape and it doesn't work for the second input when the IR has two input node. why?

the code is
![image](https://user-images.githubusercontent.com/10195989/50214269-cd057c80-03ba-11e9-9cb1-99b918079756.png)

and the printf
![image](https://user-images.githubusercontent.com/10195989/50214288-d8f13e80-03ba-11e9-994c-537aab593a49.png)

**Comment by mrinmayk** [comment]
I am having similar errors; someone please solve issue with multiple input node issue.

**Comment by lazarevevgeny** [comment]
Closing the ticket since there are no plans to support dynamic input shape.
