### ISSUE TITLE
dose quant tool support lstm operations in onnx?

### ISSUE THREAD

**Issue by xiguadong** [openvinotoolkit/openvino#12196]
hello,
   I have some rnn models within LSTM operations , does the quant tool of openvino support this operation? 
   sry, I don't find the quantable opertion support list from  https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_IR_suitable_for_INT8_inference.html

**Comment by zulkifli-halim** [comment]
Hi @xiguadong. LSTM layer is supported in ONNX framework. You may refer to [Supported Framework Layers](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx-supported-operators).

Low precision IR is also suitable for FP32 and FP16 inference if a chosen plugin supports all operations of the IR, because the only difference between a Low Precision IR and FP16 or FP32 IR is the existence of FakeQuantize in the Low Precision IR.

**Comment by wenjiew** [comment]
LSTM INT8 support is WIP right now.

**Comment by xiguadong** [comment]
> Hi @xiguadong. LSTM layer is supported in ONNX framework. You may refer to [Supported Framework Layers](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx-supported-operators).
> 
> Low precision IR is also suitable for FP32 and FP16 inference if a chosen plugin supports all operations of the IR, because the only difference between a Low Precision IR and FP16 or FP32 IR is the existence of FakeQuantize in the Low Precision IR.
Thanks very much.

**Comment by SakuraYM** [comment]
> LSTM INT8 support is WIP right now.

Can I ask how long it will take? Thanks：）

**Comment by zulkifli-halim** [comment]
My peer has linked this thread to the related PR. Please monitor this PR #11353 for updates.
