### ISSUE TITLE
custom layter time cost

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#12238]
##### System information (version)

- OpenVINO=>2022.1
- Operating System / Platform => :win10
- Problem classification => :custom layter time cost

##### Detailed description

I have implemented a custom layter, and inferenced by CPU and GPU. 
The GPU inference time takes long time(the model cost ~40ms, and the customized layer takes about 20ms). The GPU usage is about 56%.
I implemented a model with only the customization layer, where the customization layer parameters are consistent with the original model. and the it only takes about 4ms.The GPU usage is about 12%.
Why is it so different? What are the optimization strategies?

**Comment by vladimir-paramuzov** [comment]
@wang7393 such behavior may be caused by cache effects, i.e. when you run full model all the data may be evicted from the caches in comparison with single custom layer run. Also, have you checked that the custom layer source code (after code generation passes) is exactly the same in both cases? You can use OV_GPU_DumpSources debug option (https://github.com/openvinotoolkit/openvino/wiki/GPUPluginDebugUtils) to check that

**Comment by vladimir-paramuzov** [comment]
@wang7393 Project should be compiled with -DENABLE_DEBUG_CAPS=ON cmake option. Did you set it?

**Comment by wang7393** [comment]
@vladimir-paramuzov Is it necessary to recompile OpenVino with -DENABLE_DEBUG_CAPS=ON？

**Comment by vladimir-paramuzov** [comment]
@wang7393 Your approach is correct, so please check that you use correct binaries.
Also, once the debug options are enabled, the plugin will print detected options to the logs like this:
```
GPU_Debug: Config Verbose = 1
GPU_Debug: Config DumpLayersPath = cldnn/
```
