### ISSUE TITLE
Error when i test a demo with FPGA

### ISSUE THREAD

**Issue by mlchuxueing** [openvinotoolkit/openvino#123]
When i run this scripts: /root/inference_engine_samples/intel64/Release/object_detection_sample_ssd -i /root/inference_engine_samples/intel64/Release/people.jpg -m /opt/intel/computer_vision_sdk_fpga_2018.3.343/deployment_tools/model_optimizer/model/ssd/frozen_inference_graph.xml -d HETERO:FPGA,CPU -ni 1, the error happens:
ERROR: CL_OUT_OF_HOST_MEMORY
Location: /home/user/teamcity/work/scoring_engine_build/releases_openvino-2018-r3/thirdparty/dla/api/src/dla_runtime.cpp:115
Failed clCreateCommandQueue
[ ERROR ] DLA error: Error: Failure due to generic standard exception .

**Comment by shubha-ramani** [comment]
Dear @mlchuxueing can you kindly retry with the latest OpenVino version ? 2019 R1 was just released and 2018.3.343 is pretty old.

Thanks for using OpenVino !

Shubha

**Comment by ilya-lavrenov** [comment]
Hi,

This happens because your graph many unsupported FPGA layers and they present in the graph in repetitive manner. E.g. supported0 -> unsupported1 -> supported2 -> unsupported2 etc. In this case we will have a lot of FPGA subgraphs and we need several OCL queues for each FPGA subgraph. And after certain FPGA subgraph we are out of memory.

Please, try to dump picture of your graph after affinities are assigned in HETERO mode. Maybe some layers can be assigned to CPU and you can fit into limitation by number of OCL queues.

**Comment by noticeable** [comment]
Hi,
  I have met the same problem as you met,have you solved it?May you please share the way to solve it
Thanks in advance

**Comment by ilya-lavrenov** [comment]
FPGA is not a part of OpenVINO anymore
