### ISSUE TITLE
Model precision: does CPU mode support FP32 ONLY?

### ISSUE THREAD

**Issue by letmejoin** [openvinotoolkit/openvino#124]
hello everyone. When I use CPU mode in  precision FP16, [ ERROR ] The plugin does not support FP16 is occurred,  but GPU mode is accepted. SO, the CPU plugin support FP32 only? GPU can support all precision? MYRIAD support FP16 only? ps: api version 2019 R1 and 2018 R5. Thanks!

**Comment by shubha-ramani** [comment]
Dear @letmejoin,
All the information you are asking about is here:
[https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html)
FP16 is not supported on CPU and it is the preferred format for GPU.

**Comment by ilya-lavrenov** [comment]
Hi,

In future OpenVINO releases CPU will also support FP16 IR files / models.

Thanks,
Ilya.

**Comment by ilyachur** [comment]
At the current moment CPU plugin supports the FP16 precision.

I will close a ticket. Feel free to reopen it, if you have any problems.

**Comment by sonebu** [comment]
Sorry for bumping this thread, but I have a question about the extent of this support: How does the CPU treat FP16 values and operations? Are FP16 values cast to FP32, operated on (with standard FP32 operations) and then converted back to FP16? 

Asking this because -> I just ran an FP16 model through my CPU and then through my MYRIAD device (exactly the same code, exactly the same model xml/bin), and got two significantly different outputs (segmentation masks were off with MYRIAD). I can imagine the MYRIAD device supporting FP16 "natively" (directly operating on FP16 quantities on HW/asm-level, e.g., extend bitwidth from 16 to something arbitrary while doing add/mult etc), but I'm pretty sure my x86_64 CPU doesn't have "native" support for FP16 operations (i.e., no asm instructions), so it must be doing something different (thus resulting in a different output)?
