### ISSUE TITLE
Batch inference takes time

### ISSUE THREAD

**Issue by largestcabbage** [openvinotoolkit/openvino#12921]
Hello，I wonder if the time-consuming of batch inference grows linearly? For example, when batch is 1, it takes 10ms. When the batch is 2, it takes about 20ms. When the batch is 4, it takes about 40ms. When the batch is 8, it takes about 80ms?

**Comment by Iffa-Meah** [comment]
Actually, measuring inference performance involves many variables and is extremely use-case and application-dependent.
In OpenVINO these four parameters for measurements are used:

1. Throughput - Measures the number of inferences delivered within a latency threshold. (for example, number of Frames Per Second - FPS).
2. Value - While throughput is important, what is more critical in edge AI deployments is the performance efficiency or performance-per-cost.
3. Efficiency - System power is a key consideration from the edge to the data center.
4. Latency - This measures the synchronous execution of inference requests and is reported in milliseconds. 

If you are referring to throughput, this formula is used for its optimal calculation:
 **(number of batches X batch size)/(total time in seconds).**

This formula gives the number of examples our network can process in one second.

**Comment by largestcabbage** [comment]
Yeah, I know. I want to know that no matter how the batch_size is changed, the throughput of the fixed model is almost the same? Or the number of examples that the network can process in one second, related to the network model, not related to the batch_size during inference?

**Comment by Iffa-Meah** [comment]
In that's the case, you probably already know these 2 steps which are crucial to correctly measure throughput:

1. Estimation of the optimal batch size that allows for maximum parallelism
2. Measure the number of instances the network can process in one second based on the optimal batch.

These are **not solely** depend on Neural Network or model, it's also depends on your hardware limitation (as i mentioned above  use-case and application-dependent)

Meanwhile, **In OpenVINO perspective**, the batch size is derived from the model (since the IR is derived from your model). It can be set by the model optimizer tool by specifying input_shape parameter. Eg: with input shape (8, 3, 225, 225) the batch size is set to 8.

So if you want to play around and see whether throughput of the fixed model has significant differences according to the batch size, or not you'll need to change your input shape values (btw OpenVINO is using NCHW layout) during IR conversion using OpenVINO Model Optimizer. Then, run the IR with OpenVINO Benchmark App. From here, you'll get a concrete answer.

**Comment by largestcabbage** [comment]
ok thank you very much for your reply

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
