### ISSUE TITLE
FP16

### ISSUE THREAD

**Issue by largestcabbage** [openvinotoolkit/openvino#12943]
Hello, I would like to ask if the fps of fp16 inference will be improved compared to the fps of fp32 inference? Is it obvious? Why is my FPS not significantly improved when I use FP16 inference compared to FP32 inference?

**Comment by rkazants** [comment]
Hi @largestcabbage! It actually depends on the hardware you are running FP16 model on. If this is CPU, no performance is expected because all computations are performed in FP32 format anyway. We should expect performance improvement on GPU, for example, but it also depends on the size of the model and a number of floating-point operations.

**Comment by largestcabbage** [comment]
Thank you very much for your reply
