### ISSUE TITLE
[Bug] How to compile openvino with MT MSVC C runtime library

### ISSUE THREAD

**Issue by venki-thiyag** [openvinotoolkit/openvino#12959]
Currently when openvino is built on Windows, it is linked with /MD MSVCC runtime library option, how to build openvino as dll, but with /MT option

**Comment by zulkifli-halim** [comment]
Hi @venki-thiyag 

/MD links runtime dynamically, while /MT links it statically. You can refer to [Building OpenVINO static libraries](https://github.com/openvinotoolkit/openvino/wiki/StaticLibraries) for the installation detail. 

Building static OpenVINO Runtime libraries allows to additionally reduce the size of a binary when it is used together with conditional compilation. It is possible because not all interface symbols of OpenVINO Runtime libraries are exported to end users during a static build and can be removed by linker.

**Comment by ilya-lavrenov** [comment]
@venki-thiyag you can look specifically at https://github.com/openvinotoolkit/openvino/wiki/StaticLibraries#building-with-static-msvc-runtime where it's shown that you can use OV cmake toolchain to libs compiled with static runtime.
Having static MSVC runtime with dynamic libs is not right way, because each dll will have its own runtime.

Note, when you are going to build your own app against such static OV with static MSVC runtime, you have to pass /MT version to your project as well. Or just use cmake option https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html for your target

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen if further assistance is needed.
