### ISSUE TITLE
Encountered Reshape Error when converting ONNX model into IR

### ISSUE THREAD

**Issue by largestcabbage** [openvinotoolkit/openvino#13024]
Why do the following errors occur when converting TPH-yolo to onnx and onnx to IR
error：
While validating node 'v1::Reshape Reshape_3078 (599[0]:f32{400,1,512}, 1919[0]:i64{3}) -> (f32{?,?,?})' with friendly_name 'Reshape_3078':
Requested output shape {400,1600,128} is incompatible with input shape {400, 1, 512}

**Comment by Iffa-Meah** [comment]
@largestcabbage biggest possibility for that error to occur is that you parsed an incorrect shape to the model during conversion.

Could you share:
1. Your model files for us to validate from our side
2. Your conversion commands and steps

**Comment by largestcabbage** [comment]
The onnx file is too large for me to upload

**Comment by Iffa-Meah** [comment]
@largestcabbage perhaps you could compress the file & upload it somewhere (GitHub/Google Drive) and share the link or you could send it to my email.

**Comment by largestcabbage** [comment]
Looking forward to your answer,thank you very much
















At 2022-09-14 10:24:19, "SitiNurNazhifah JaisMeah" ***@***.***> wrote:

@largestcabbage perhaps you could compress the file & upload it somewhere (GitHub/Google Drive) and share the link or you could send it to my email.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

从网易163邮箱发来的超大附件
weights.zip (260.61M, 2022年9月29日 10:35 到期)
下载

**Comment by Iffa-Meah** [comment]
@largestcabbage I didn't receive your email in my inbox. This is my official email: siti.nur.nazhifahx.jais.meah@intel.com

**Comment by largestcabbage** [comment]
ok

**Comment by Iffa-Meah** [comment]
@largestcabbage I checked your model.

Your **1st model** (best1.onnx) seems to be supported by OpenVINO as it can be inferred with benchmark_app.

<img width="453" alt="benchmarkonnx1" src="https://user-images.githubusercontent.com/79643476/190103375-4691d8ed-c90b-495b-b89d-eaebee80c709.png">

However, when I converted it into IR using Model Optimizer, the command ends without error but nothing is generated (expected xml and bin files). I tried this for a couple of times but got the same result.
<img width="926" alt="best1MO" src="https://user-images.githubusercontent.com/79643476/190103826-77f98116-c861-49dc-8869-97f2dbb13122.png">

Your 2nd model (best2.onnx) is not supported by OpenVINO since the native infers of the ONNX model itself failed. (OpenVINO does support the inference of the native ONNX model).
<img width="478" alt="benchmark2onnx" src="https://user-images.githubusercontent.com/79643476/190104202-e0068154-f95f-41da-a275-71340f2e7567.png">

Hence, this explains why the best2.onnx cannot be converted into IR
<img width="518" alt="best2MO" src="https://user-images.githubusercontent.com/79643476/190104427-b17675d7-be75-4070-a985-f77d0dce2204.png">


We'll further investigate this and get back to you with possible workarounds.

**Comment by largestcabbage** [comment]
Thank you very much, looking forward to your reply.

**Comment by avitial** [comment]
@largestcabbage it seems these models have static shapes, do these models contain any dynamic shapes and are there any major differences (if any) between _best1.onnx_ and best2.onnx models? How were these models exported to ONNX? [Kindly refer to Converting a PyTorch* Model](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_PyTorch.html) for reference, please share the OpenVINO version used. 

Taking a quick glance at provided onnx models I can see they were generated using PyTorch 1.10.0, would it be possible to re-generate them using PyTorch version specified in open model zoo [requirements-pytorch.in](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/model_tools/requirements-pytorch.in) file and see if the error persists?

**Comment by largestcabbage** [comment]
Thanks a lot, I've managed to solve it, but thanks anyway. The reason is that there is an error in the transfer of nn.MultiheadAttention to onnx in pytorch. At present, it has been successfully solved by using its own rewriting operator, but the specific reason has not been found.

**Comment by avitial** [comment]
Glad you managed to solve it. Closing this issue , feel free to reopen to ask any questions related to this topic.
