### ISSUE TITLE
[Bug] gpu plugin source dump has filename conflictions

### ISSUE THREAD

**Issue by LoSealL** [openvinotoolkit/openvino#13110]
##### System information (version)

- OpenVINO=>  2022.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022
- Problem classification => GPU plugin source dump

##### Detailed description
In some cases, when use source dump functions of gpu plugin, the dumped source file could have name conflictions and the content was mixed up.

##### Steps to reproduce
1. Enable source dump of CLDNN
2. Dump a special graph

    ```c++
    static constexpr ov::Property<std::string> dump_dir{"CLDNN_SOURCES_DUMPS_DIR"};
    ov::Core core(plugins);
    core.set_property("GPU", dump_dir(sources_dumps_dir));
    std::shared_ptr<ov::Model> network = core.read_model(model_xml, model_bin);
    ov::CompiledModel executor = core.compile_model(network, "GPU");
    auto request = executor.create_infer_request();
    request.infer();
    ```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   _I've made a [PR](https://github.com/openvinotoolkit/openvino/pull/13111) #13111  to fix this issue._
 - [x] There is reproducer code and related data files: images, videos, models, etc.
   _Our model is private, so we can't attach it, please see PR for root cause._

**Comment by Iffa-Meah** [comment]
@LoSealL , looking at your description in [here](https://github.com/openvinotoolkit/openvino/pull/13111), you need to create an algorithm, specifically a handler, to check the elements of your tensor (which in that case you call it as "key") so that each element have their own unique ID.

My suggestion would be:
1. check whether there are the same elements in your tensor
2. If yes, check the index position of the same elements
3. If index position !=, assign a new ID


This is more related to your own software design in your custom implementation instead of OpenVINO.

**Comment by LoSealL** [comment]
Hi @Iffa-Meah The ID is not from tensor name, instead it's from tensor source's **compile option**, I don't think we can create a specific handler for that.

**Comment by Iffa-Meah** [comment]
@LoSealL Could you elaborate further so that we could reproduce the error from our side:
1. Did you use any of the OpenVINO sample Applications as a reference, if yes could you share which one?
2. could you share your model files since your custom code mentions .xml and .bin (or any model would do?)
3. Any additional config/library files that are required for this purpose

**Comment by LoSealL** [comment]
Hi @Iffa-Meah, please see model files at https://github.com/LoSealL/openvino/releases/tag/test

On my PC (_i7-9750H with UHD 630 GEN9 24EU_), it will dump **20** .cl_cache, but only **19** .cl files, because two of which have the same name.

**Comment by Iffa-Meah** [comment]
@LoSealL I checked your model and it seems to be supported by OpenVINO.

<img width="621" alt="benchmarkmodel" src="https://user-images.githubusercontent.com/79643476/191652484-e9d9ea81-fc2b-4577-967d-3f385c4b2ea2.png">


However, I didn't found your custom code being applied in any of the cpp sample:

<img width="416" alt="cppsample" src="https://user-images.githubusercontent.com/79643476/191652625-665762fd-2170-4d1a-99c0-6181274e8cc8.png">

Where exactly did you implement these codes?:

```
static constexpr ov::Property<std::string> dump_dir{"CLDNN_SOURCES_DUMPS_DIR"};
ov::Core core(plugins);
core.set_property("GPU", dump_dir(sources_dumps_dir));
std::shared_ptr<ov::Model> network = core.read_model(model_xml, model_bin);
ov::CompiledModel executor = core.compile_model(network, "GPU");
auto request = executor.create_infer_request();
request.infer();
```
