### ISSUE TITLE
[Bug]: Unknown CMake command "add_demo".

### ISSUE THREAD

**Issue by azeemashraf348** [openvinotoolkit/openvino#13319]
##### System information (version)

- OpenVINO => 2020.4
- Operating System / Platform => MAC OS
- Compiler => Apple clang version 12.0.5 (clang-1205.0.22.9)
- Problem classification: Model Conversion
- Model name: Smart_classroom_demo

##### Detailed description
Following error occurs when i run the command " cmake ../smart_classroom_demo/cpp  ". 
------
CMake Error at CMakeLists.txt:8 (add_demo):
Unknown CMake command "add_demo".
------

I have also added the file "CMakeLists.txt" below:

[CMakeLists.txt](https://github.com/openvinotoolkit/openvino/files/9699196/CMakeLists.txt)

**Comment by ilya-lavrenov** [comment]
Hi @azeemashraf348 

> Following error occurs when i run the command " cmake ../smart_classroom_demo/cpp "

This is not right way. You need to use https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos as a cmake source directory, because it contains all common settings and cmake macro including `add_demo`.

If you want to build only `smart_classroom_demo`, you need to configure the whole project anyway, but use `cmake --build . --target smart_classroom_demo` to build a specific target.

**Comment by Iffa-Meah** [comment]
@azeemashraf348 in addition to @ilya-lavrenov explanation above, here is some insight to build that specific demo.

**First and foremost, you'll need to get a working OpenVINO in your environment.** Since you are asking through GitHub Platform, I assume you are using OpenVINO build from source.

Ensure you had fulfill the system requirements and also build steps which you can refer [here](https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS_x86_64).

If everything's good, you can see the samples demo binary in <openvino_source_dir>/bin/intel64/Release/

Try to run the binary and see whether you are able to see the output. If yes, congrats, you now have a working OpenVINO in your env.


**Next, you'll need to do the same concept for [Open Model Zoo]**(https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos).

1. Clone the repo: `git clone --recurse-submodules https://github.com/openvinotoolkit/open_model_zoo.git`

2. define your OpenVINO_DIR, for example mine is: `export OpenVINO_DIR=$OpenVINO_DIR/Users/pse/Desktop/OpenVINO/build`

3. I installed opencv using `brew install opencv` and so far I don't have to manually define its dir.

4. Create a folder named build in the Open Model Zoo dir and access it: `mkdir build && cd build`

5. Compile Release: `cmake -DCMAKE_BUILD_TYPE=Release <open_model_zoo>/demos`

6. Build: cmake --build .

the demo application binaries are in `<path_to_build_directory>/intel64/Release/`

Note that step 5 & 6 would build all demos.

Meanwhile, these commands would compile & build specific demo
 
`cmake -DCMAKE_BUILD_TYPE=Release <open_model_zoo>/demos`

`cmake --build . --target classification_demo segmentation_demo`

<img width="294" alt="13319" src="https://user-images.githubusercontent.com/79643476/193806927-95e4aefd-2d48-4458-809a-4e66dc8d9cf4.png">

**Pay attention & study the official documentation**
Hope this helps.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
