### ISSUE TITLE
[Bug]Can't determine channels dimension for input. Input shape is {1,1,192,192}, needed channels 3

### ISSUE THREAD

**Issue by wwdok** [openvinotoolkit/openvino#13480]
##### System information (version)

- OpenVINO=> : 2022.2.0-7713-af16ea1d79a
- Operating System / Platform => : Windows 64 Bit
- Compiler => :  Visual Studio 2017
- Problem classification => : Model Conversion

##### Detailed description

I want to convert my onnx model to openvino format with `mo`, but it says `Can't determine channels dimension for input. Input shape is {1,1,192,192}, needed channels 3`. **Because my model input is grayscalse image, so the channel dimension is only 1,** does openvino only support RGB image as input ? Can we remove this restriction ?

##### Steps to reproduce

```python
import os

onnx_path = "model.onnx"
output_dir = "./"

mo_command = f"""mo
                 --input_model "{onnx_path}"
                 --input_shape "[1, 1, 192, 192]"
                 --mean_values="[123.675, 116.28 , 103.53]"
                 --scale_values="[58.395, 57.12 , 57.375]"
                 --data_type FP16
                 --output_dir "{output_dir}"
                 """
mo_command = " ".join(mo_command.split())

ret = os.system(mo_command)
print("==>> ret: ", ret)
```
The onnx model:
[model.zip](https://github.com/openvinotoolkit/openvino/files/9778172/model.zip)

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [ ] There is reproducer code and related data files: images, videos, models, etc.

**Comment by rkazants** [comment]
Hello @wwdok,

The problem is with tte cmd-line. since you have gray-scale input, you can't use parameters `mean_values` and `scale_values`. They can be employed only in case RGB input. Please correct your cmd-line as follows:

'''
mo --input_model model.onnx --input_shape "[1, 1, 192, 192]" --data_type FP16
'''

**Comment by Iffa-Meah** [comment]
@wwdok your native ONNX seems to be supported by OpenVINO since it can be inferred with benchmark_app

<img width="544" alt="benchmark_onnx" src="https://user-images.githubusercontent.com/79643476/195766356-37263438-e003-4b00-b863-38fac423e8d0.png">


The conversion into IR with input shape defined are successful and able to be inferred:

<img width="602" alt="IR_inputShape" src="https://user-images.githubusercontent.com/79643476/195766447-952dfd9d-dcd3-4822-bb4a-1c5873ba41e3.png">

<img width="596" alt="IR_inputShapeBenchmark" src="https://user-images.githubusercontent.com/79643476/195766457-478d500c-e652-46e7-8e57-3c59b43b5a12.png">


However, I do face the same issue as yours when I defined the mean and scale value. 
As you mentioned, these parameters indeed required [R G B] format (3 channels) fed to the command.

<img width="585" alt="error_channel" src="https://user-images.githubusercontent.com/79643476/195766614-cbd72d59-1cf1-4253-8349-477c64b75e61.png">


We'll further investigate this and get back to you with possible workaround

**Comment by rkazants** [comment]
Hello @wwdok, 

OpenVINO supports input in gray-scale format as well. There is a problem with your cmd-line because you use `mean_values` and `scale_values` parameters that only targets input in RGB format for mean-scaling. Your gray-scale image does not need this pre-processing. Please correct your cmd-line as follows:

```
mo --input_model model.onnx --input_shape "[1, 1, 192, 192]" --data_type FP16
```

Regards,
Roman

**Comment by Iffa-Meah** [comment]
@wwdok hope the explanation from @rkazants clears your issue.
If you don't have any other inquiries we'll proceed to close this ticket.
