### ISSUE TITLE
Model graph from blob

### ISSUE THREAD

**Issue by tersekmatija** [openvinotoolkit/openvino#13590]
Hey, I am wondering if there already exists a tool/some API that allows you to read and obtain a computational graph directly from compiled blob for MyriadX, rather than from IR.

Thanks,
Matija

**Comment by ilya-lavrenov** [comment]
There is no such way. Compiled blob represents just a raw stream of data which is transferred from host to device. It does not contain any auxiliary information like model structure.
So, once you stored model to compiled blob, some info is lost

**Comment by Maxim-Doronin** [comment]
Hi! You can use compile_tool or Export method in order to save compiled graph in a blob format. Then you can use it in any application that uses Import method. As @ilya-lavrenov said some information is lost like names of operations and metadata. Anyway, after importing and parsing the blob in the myriadx plugin you are able to call QueryNetwork and get some info about the model structure.
