### ISSUE TITLE
[Bug]The reshape issue base on 2021.4

### ISSUE THREAD

**Issue by fireFrappe** [openvinotoolkit/openvino#13817]
Hi, Is there some way to convert Executable network to IR?
I want to reshape the input of an IR network, I follow https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_ShapeInference.html?sw_type=switcher-python to do it. But I don't know how to convert the ``exec_net`` to IR and save it. Openvino is 2021.4.
Many thanks.

##### System information (version)

- OpenVINO=> :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:
- Problem classification => :grey_question:

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [ ] There is reproducer code and related data files: images, videos, models, etc.

**Comment by slyalin** [comment]
@fireFrappe, short answer is NO.

Long answer: this is not what you are probably looking for. We can reshape hardware-independent model representation (IR) before loading to a plugin, so that guide you referenced is applicable for OpenVINO model before it is compiled for a plugin. After compilation, when it is represented as executable network -- your case -- you still can change the shape of the input _but only if_ the plugin you are using supports dynamic shapes. This functionality is available for CPU plugin starting OpenVINO release 2022.1, the functionality is described here: https://docs.openvino.ai/latest/openvino_docs_OV_UG_DynamicShapes.html.

Dynamic shapes should be used only if you really change shapes from one inference to one one and cannot leave them static, so could you provide more information about your use case to let me understand whether my guess that you need dynamic shapes is right? Which particular dimensions are you trying to change and how frequently? Why are you trying to change them after executable network is ready?

Also, you are referring to 2021.4 documentation, is it because you are somehow locked with that version, or you can upgrade to the latest OpenVINO release?

**Comment by andrei-kochin** [comment]
@fireFrappe are there any questions from your side or we can close the issue?
