### ISSUE TITLE
Cannot load library 'libopenvino_intel_myriad_plugin.so:

### ISSUE THREAD

**Issue by glennford49** [openvinotoolkit/openvino#13968]
I have my working openvino 2022.2 toolkit working, then i  tried openvino-dev from pypi.
started running the python files, openvino-dev works on cpu but not on MYRIAD, any idea on this?
MYRIAD  is detected on helloquerydevice, and is working flawlessly on openvino 2022.2 toolkit .

**Comment by ilya-lavrenov** [comment]
MYRIAD plugin is not available through pip packages downloaded on Pypi. This is because of difference license which is used for MYRIAD plugin, while on Pypi can we use packages with apache2.

You can use MYRIAD plugin via python using OpenVINO archives. Python is located in `python` folder and activated once you call setupvars script.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
