### ISSUE TITLE
How to debug the CPP inference process?

### ISSUE THREAD

**Issue by Raise-me-up** [openvinotoolkit/openvino#14181]
As the cpp inference codes of openvino are not provided, how can I compare the results of interlayer with python ones?

**Comment by brmarkus** [comment]
Are you referring to a pre-built version of OpenVINO (i.e. downloaded a binary-installer from "software.intel.com")?

You can also build OpenVINO from source-code and have full control over the code, can add log-messages and re-build, can set break-points (when building DEBUG-build instead of RELEASE-build).

Or do I misunderstand your question?

**Comment by Raise-me-up** [comment]
@brmarkus 

Thank you for your advice! I will have a try!

**Comment by Raise-me-up** [comment]
@brmarkus 
Sadly, I can't debug into the function infer_request.infer(), resulting in the unknown of network inference progress. How can I get the interlayer results during the inference process?

**Comment by brmarkus** [comment]
What do you mean you cannot debug the method "infer()"? You found a binary library you cannot step into with the debugger?
Various plugins (e.g. CPU-plugin, GPU-plugin, VPU-plugin, etc.) could be used and loaded dynamically, OpenCL-kernels would be used for various tensors/operations.

With logging (ITT, Vtune, enabled log-messages) you haven't found enough details?

**Comment by Raise-me-up** [comment]
@brmarkus 

Well, I can't step into the infer method before, as there is no any pdb file in the installation directory of openvino.  Now I have moved them into the debug directory, and the debugger works well! 

Thank you for your help!
