### ISSUE TITLE
How can i control the number of threads in inference?

### ISSUE THREAD

**Issue by Hap-Zhang** [openvinotoolkit/openvino#14245]
Dear all,

How can I control the number of threads when inference with openvino 2021 and 2022? Can someone give a sample code or guide documentations? The "CPU_THREADS_NUM" seems not work.

**Comment by Hap-Zhang** [comment]
Hi，@brmarkus 
Thanks for your reply.

Do you refer to using CPU (CPU-plugin)?
**A:Yes, it's CPU-plugin.**

How have you tried to set "CPU_THREADS_NUM"?
**A:The code list as follow:
`from openvino.runtime import Core`
`core = Core()`
`model_xml="face_detect.xml"`
`encoder_exec = core.compile_model(model_xml, "CPU")`
`core.set_property("CPU", properties={"CPU_THREADS_NUM":"1"})`
`self.infer_request = encoder_exec.create_infer_request()`**

How have you measured the number of threads used by OpenVINO for inference?
**A:I can not measure the number of inference threads,but i find the cpu usage is 70% when "CPU_THREADS_NUM" set to 1. And, the cpu usage does not change when "CPU_THREADS_NUM" set to different value. Could you tell me what is the default inference threads in openvino 2022.1.0? And how can i change the inference threads num?**

Can you describe your environment, first, please?
**A: The version of OpenVINO is 2022.1.0, and the  hw is Intel CPU(Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz)**

**Comment by brmarkus** [comment]
You might have a closer look into the documentation, e.g. under "https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_CPU.html#supported-properties":

> All parameters must be set before calling [ov::Core::compile_model()](https://docs.openvino.ai/latest/classov_1_1Core.html#doxid-classov-1-1-core-1a46555f0803e8c29524626be08e7f5c5a) in order to take effect or passed as additional argument to [ov::Core::compile_model()](https://docs.openvino.ai/latest/classov_1_1Core.html#doxid-classov-1-1-core-1a46555f0803e8c29524626be08e7f5c5a)

The default number of threads is aligned with the number of physical cores (physical cores, not hyperthreading).

Typically with command like `top` or `htop` you can see the processes and it's children-threads.

Can you check with e.g. OpenVINO's sample `benchmark_app`? It allows tuning via several command-line parameters (e.g. number of streams, batch-size, pinning, NUMA, etc.)

Are you sure the seen CPU-load is caused by inferencing? (If you are processing a video/video-stream/image then the frames/images might be decoded on CPU instead of HW-accelerated within a GPU if there is no GPU available (embedded or discrete)).

Are you sure your network architecture allows parallel processing using multiple threads?
Have you tried OperatingSystem (OS) commands like `taskset` or `numactl` for thread-CPU_core-Multi_CPU-pinning?

**Comment by Hap-Zhang** [comment]
@brmarkus 
Thanks for your kindly reply. 
It's ok now when set "CPU_THREADS_NUM" before complie_model().
