### ISSUE TITLE
Missing DynamicToStaticShape If operation for MYRIAD

### ISSUE THREAD

**Issue by lino-alves** [openvinotoolkit/openvino#14281]
I have a model in PyTorch (**Faster R-CNN**) that I exported to ONNX and ran through the model optimizer successfully.
Running the inference on the CPU is working fine, but in the MYRIAD (Intel NCS2) it fails while loading the model due to missing operation(s).

The model includes a couple of (dynamic shape?) `If` operations that are causing the issue with the MYRIAD device.

Here is the error output (the `benchmark_app` gives the same error):
`openvino/src/plugins/intel_myriad/common/src/ngraph/transformations/dynamic_to_static_shape.cpp:200 DynamicToStaticShape transformation encountered dynamic node 2626 of type If ver. 0, but only [Abs ver. 0, Ceiling ver. 0, Clamp ver. 0, Concat ver. 0, Convert ver. 0, Exp ver. 0, ExpGatherElements ver. 0, Floor ver. 0, Log ver. 0, MatMul ver. 0, ...] types are supported for dynamic nodes`

I checked that the `If` is one of the supported operations by OpenVINO, so maybe it is possible to extend the dynamic to static shape operations to include the `If`. Is this feasible to implement and can I get some support on this? I can also try to implement something on my side (if feasible), but would be good to get some guidance and examples to start with.

I'm using OpenVINO 2022.1 in Ubuntu 20.04 (WSL2).

**Comment by Iffa-Meah** [comment]
@lino-alves since you mentioned you are using MYRIAD/NCS2, I assume you already know that the device requires FP16 precision.

Converting the full precision model into FP16 means the model size had been compressed. A compressed model while enhancing the inferencing speed would trade off its accuracy. Certain layers might have been cut off during the conversion with FP16 data precision.

This is a trade-off that users need to bear and thus, it's crucial to evaluate your use case. For example:
1. If your use case required fast inferencing without the need for accuracy, such as parking system in a mall, then using a compressed/optimized model worth it.
2. Meanwhile, if the use case requires accuracy to be precise such as medical results, then full precision would be best but the user need to bear with slower inferencing rate.


Could you share the relevant model files? (ONNX & IR) We'll validate from our side.

**Comment by lino-alves** [comment]
@Iffa-Meah Yes, I am compressing the model to FP16, using the model optimizer, to be able to run it in the NCS2.

I gave you access to a folder that includes the model files (ONNX and IR). You should get a notification on the email you have registered here.

Let me know if you have any issues accessing the files or you need me to give access to someone else.

**Comment by Iffa-Meah** [comment]
@lino-alves I requested access to your files.

![image](https://user-images.githubusercontent.com/79643476/204951796-4a3ed290-aa1f-4431-a541-783311ab7226.png)

**Comment by Iffa-Meah** [comment]
@lino-alves I did a quick check on your model.

It seems that your native ONNX model can be inferred with CPU but not MYRIAD.

CPU

<img width="418" alt="1_cpu" src="https://user-images.githubusercontent.com/79643476/205012470-55d379f3-6ee1-4f62-bef4-a434d2510a7d.png">


MYRIAD
<img width="423" alt="2_MYRIAD" src="https://user-images.githubusercontent.com/79643476/205012499-21a3636d-9cb0-4a71-8ca5-817d594d9382.png">



As you suspected, the MYRIAD does not support inputs being set to dynamic which is discussed in this [GitHub thread](https://github.com/openvinotoolkit/openvino/issues/11510) with a rather similar issue (DynamicToStaticShape transformation).

We'll further investigate this and get back to you with the best alternative asap.

**Comment by hbalasu1** [comment]
Hi @lino-alves 

For your information, Dynamic Shape supports MYRIAD devices but has a very specific topology. 
As the error message mentions, the topology of your model is not supported by Dynamic Shape for the MYRIAD device. 

We apologize for the inconvenience and hope this information help. 

Thank you

**Comment by hbalasu1** [comment]
Hi @lino-alves 
I'm sorry for not getting back to you sooner. Here the response 

1. For now, IF operation is not supported for Dynamic Shape if the MYRIAD device is selected. 

2. Since Dynamic shape implementation happened on OpenVINO 2022 and before OpenVINO 2022, we had limited support for the MYRIAD device. With that, there is little focus on a new feature for MYRIAD devices. 
That is why some Dynamic Operation work on the CPU but not MYRIAD. 
For the MYRIAD limitation, there is no documentation about it, so I couldn't provide you the full list, but for Dynamic Shape, you can refer to this When [Dynamic Shapes API is Not Applicable](https://docs.openvino.ai/latest/openvino_docs_OV_UG_NoDynamicShapes.html#doxid-openvino-docs-o-v-u-g-no-dynamic-shapes).

**Comment by hbalasu1** [comment]
Hi @lino-alves 

Is your question been addressed? Can we close this case?

**Comment by lino-alves** [comment]
Hi @hbalasu1 

In summary, the operation is not supported and I have to work around the limitation based on the documentation you provided.

For now that is fine, hopefully in the future OpenVINO will be expanded to support this operation on the MYRIAD device.

I'm closing the issue.

Thanks
