### ISSUE TITLE
[Bug]ov::inference_num_threads  can not work, when using fork() 

### ISSUE THREAD

**Issue by powermano** [openvinotoolkit/openvino#14394]
##### System information (version)

- OpenVINO => 2022.2
- Operating System / Platform => ubuntu 20.04

##### Detailed description
It works when setting ov::inference_num_threads=1. But when using fork(), for example fork=4, all processes run on one core and each process only utilized 25% of the core.  

What I would like is for each process to run on one core and each core to be utilized at 100%。

```
  ov::Core core;
  core.set_property("CPU", ov::inference_num_threads(1));
  std::shared_ptr<ov::Model> model = core.read_model(onnx_path);

  // compile
  model->reshape(ov_input_shape);
  ov::CompiledModel compilded = core.compile_model(model);
  ov::InferRequest infer_request = compilded.create_infer_request();
```

**Comment by dmitry-gorokhov** [comment]
Hi @powermano!

By default OV uses CORE affinity setting which assumes each inference thread is hard-pinned to specific cores. Since OV instances, which are launched in forked processes, don't know anything about each other, each instance start pinning from 0th physical core. 
Simplest way to avoid such behavior use: change [affinity](https://docs.openvino.ai/latest/enumov_1_1Affinity.html#doxid-group-ov-runtime-cpp-prop-api-1ga72b7c6cde7f94f07bc1519464c55e9c5) to NUMA via set_property API. In that case OV avoids hard-pinning behavior and let OS to schedule inference threads on desired cores.

Another approach is to use some external tools like [numactl](https://linux.die.net/man/8/numactl) which allows to pin application instance to specific core/memory nodes.

Also it might be useful to take a look on OV [streams](https://docs.openvino.ai/latest/openvino_docs_deployment_optimization_guide_tput_advanced.html#openvino-streams) API. In short this functionality allows to run several instances of the same compiled model in parallel, but hides all complicated implementation details (like threads pinning, weights sharing and so on) inside OV.

**Comment by powermano** [comment]
Thanks. change [affinity](https://docs.openvino.ai/latest/enumov_1_1Affinity.html#doxid-group-ov-runtime-cpp-prop-api-1ga72b7c6cde7f94f07bc1519464c55e9c5) to NUMA via set_property API finally works.
