### ISSUE TITLE
[Bug] Canceling transpositions are added when converting from TF

### ISSUE THREAD

**Issue by tazr** [openvinotoolkit/openvino#14886]
##### System information (version)

- OpenVINO=> 2022.3
- Operating System / Platform => Windows 64 Bit
- Compiler => N/A
- Problem classification => Model Conversion
- Framework: TensorFlow

##### Detailed description

When converting a simple TF network and asking to switch to channel first layout, transpositions are added even in simple situations. This is not only a performance issue, but also a regression from 2021.4, where those transpositions where absent.

##### Steps to reproduce

Create this network from TF:
```python
import tensorflow as tf
from tensorflow.tools.graph_transforms import TransformGraph

ph = tf.placeholder(dtype=tf.float32, shape=(1, 32, 32, 32, 2), name='input')
y = tf.math.multiply(ph, 2, "output")
with tf.Session() as sess:
    g = tf.get_default_graph().as_graph_def()
    g = TransformGraph(g, inputs=["input"], outputs=["output"], transforms=[])
    tf.io.write_graph(g, ".", "test.pb", as_text=False)
```

Convert using
```
mo --use_new_frontend --input_model test.pb --input "input" --output "output" --layout "input(ndhwc->ncdhw),output(ndhwc->ncdhw)"
```

The resulting network has two canceling transpositions around the scalar multiplication:

![image](https://user-images.githubusercontent.com/29096027/210222720-e5035f5e-a09b-4f8f-b4e5-7915b0690e46.png)

Note that the same network converted with 2021.4 (which switched to channel-first by default) does not present this issue:

![image](https://user-images.githubusercontent.com/29096027/210223056-0c6dfb69-a8ff-4c35-af4f-4cdfe70afad9.png)

##### Issue submission checklist

 - [X ] I report the issue, it's not a question
   
 - [X ] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [X ] There is reproducer code and related data files: images, videos, models, etc.

**Comment by rkazants** [comment]
The problem exists for both conversion paths via new TensorFlow Frontend and legacy one.
@jane-intel, @slyalin, can you comment please if we should have TransposeSinking transformation in MOC to avoid these Transposes inserted for the layout change? Currently, TS is triggered in the frontend prior to adding pre-processing and post-processing parts for the layout change.

Best regards,
Roman

**Comment by Iffa-Meah** [comment]
@tazr try to covert your Tensorflow model into IR by using the default conversion command without additional parameters:

<img width="711" alt="convIR" src="https://user-images.githubusercontent.com/79643476/210740055-6f1f1d87-cffc-4a0d-a4ec-a5d024eecea3.png">


The IR model doesn't have transpose layers by doing this since this is your concern:

<img width="836" alt="netron20223IR" src="https://user-images.githubusercontent.com/79643476/210740304-5236c325-c5b1-4b49-acfa-0815280eda82.png">

This is your Tensorflow original model layouts (as you had shown above):
<img width="841" alt="netronori" src="https://user-images.githubusercontent.com/79643476/210740436-b4586f6d-4579-4903-9948-73d49c44d743.png">

Plus, this IR can be inferred so far:
<img width="525" alt="inferIR" src="https://user-images.githubusercontent.com/79643476/210740556-e475e99d-e7bf-4a63-81d7-d4bcd60fda0d.png">

Are there any specific requirements for your use case to be using `--layout "input(ndhwc->ncdhw),output(ndhwc->ncdhw)"` without any transpose?

**Comment by tazr** [comment]
@Iffa-Meah yes there is, I work on a product with an existing API relying on the default channel-first convention of earlier OpenVINO releases and I would rather not break it. Not specifying channel-first to `mo` would mean making the transpositions myself outside of the model, which is arguably not a better alternative.

**Comment by Iffa-Meah** [comment]
@tazr In that case, we'll further investigate this and get back to you asap with the best alternative.

**Comment by slyalin** [comment]
@tazr, the transpositions around such simple element-wise fragments look not good, agree. But could you confirm for your real case example, if additional transpositions of a such kind bring bad performance in comparison to the case when they are not inserted? Also please let me know the target device where performance regression happened.

OpenVINO runtime performs model optimization in `compile_model` method, so even if you see something that is not well optimized in IR it can be covered when the model is loaded to HW plugin. It is even more expected for such layout optimization as the elimination of transposes because layout optimization is very HW-sensitive.

**Comment by tazr** [comment]
@slyalin I tried to provide a minimal example for this report. The network I use in practice is akin to a U-Net. For this model, the new conversion has added transpositions at 5 places when there was not before, so it looked a bit alarming.

I did some performance measurements, and you're right, I could not measure any significant difference between both models, so it may be that the transpositions are removed during model compilation, or fast, or both.

However, in the current situation, I would probably have to always benchmark against a "clean" 2021.4 conversion from now on, to make sure I don't get any penalty from those extra transpositions, until I get clear understanding or confidence why these transpositions are harmless or even beneficial. Are channel-last convolutions documented to be faster on (some) CPU?

**Comment by slyalin** [comment]
@dmitry-gorokhov, could you comment on the channel-last convolutions question?

@tazr, the content of the IR is not only thing that may be changed moving from release to release. We can rebalance the transformation flow between offline and runtime stages anytime to target a scenario that you may not have in your practice. If performance validation says that resulting performance for models is OK, then any such change is legitimate.

**Comment by avitial** [comment]
@dmitry-gorokhov gentle ping.

**Comment by dmitry-gorokhov** [comment]
@tazr @slyalin OpenVINO have never used channel-first layout for Convolutions, it is either blocked or channel-last which is required for better performance. These conversions are not expresed in IR, but appear on model compilation stage.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
