### ISSUE TITLE
Error in converting TF2 model with multiple input signature

### ISSUE THREAD

**Issue by mnl12** [openvinotoolkit/openvino#15138]
Operating system linux ubuntu
Openvino, Openvino-dev, Openvino-tensorflow (all 2022.3.0)
Tensorflow 2.9.1
Model: Delg (https://github.com/tensorflow/models/tree/master/research/delf)

Hi,

I am trying to convert a saved TF2 model with multiple Input/output containing signatures. I use the following code

`mo --saved_model_dir tf_scaled_model --input input_image,input_scales,input_max_feature_num,input_abs_thres,input_global_scales_ind --input_shape [1024,1024,3],[1],[0],[0],[1]`

 

where the signature in the original code is defined as 

```
@tf.function(input_signature=[
    tf.TensorSpec(shape=[None, None, 3], dtype=tf.uint8, name='input_image'),
    tf.TensorSpec(shape=[None], dtype=tf.float32, name='input_scales'),
    tf.TensorSpec(shape=(None), dtype=tf.int32, name='input_max_feature_num'),
    tf.TensorSpec(shape=(None), dtype=tf.float32, name='input_abs_thres'),
    tf.TensorSpec(
        shape=[None], dtype=tf.int32, name='input_global_scales_ind')
])
```
However, I receive the following error,

```
[ ERROR ]  Cannot infer shapes or values for node "StatefulPartitionedCall/StatefulPartitionedCall/Any".

[ ERROR ]  Input 0 of node StatefulPartitionedCall/StatefulPartitionedCall/Any was passed int32 from StatefulPartitionedCall/StatefulPartitionedCall/Equal_port_0_ie_placeholder:0 incompatible with expected bool.
```

 

which is weird because I do not have bool input. I was wondering if you could help me in this issue.

 

Thanks.

**Comment by rkazants** [comment]
Hi @mnl12,

Let me clarify your request a bit. What pre-trained model did you try to convert? Is it this one: http://storage.googleapis.com/delf/delf_gld_20190411.tar.gz?

Best regards,
Roman

**Comment by mnl12** [comment]
Thanks for your reply.
Very similar to it. It is actually https://storage.googleapis.com/delf/r101delg_gldv2clean_20200914.tar.gz

**Comment by rkazants** [comment]
Hi @mnl12,

Investigated the problem. It turned out that `reverse_shape_infer` for Unary operations is incorrect and uses the logic for eltwise operations. Let me fix it today.

@pavel-esir, fyi.

Best regards,
Roman

**Comment by mnl12** [comment]
Hi, 
Thanks for your reply.
So should we wait for a new update? and is there any suggestion on what I can do now to possibly resolve the issue? Thanks.

**Comment by pavel-esir** [comment]
Hi @mnl12 thanks for reaching to us and opening this issue. I also took a look. When input shapes are not specified yes Roman is right failing happens on `reverse_shape_infer` but even if shapes are specified we end having error with type inconsistency for `Any` which you reported.

And this happens during offloading shape inference to tensorflow at these lines
https://github.com/openvinotoolkit/openvino/blob/0c9abf43a91fbe2dc95974b6cb2651bd883d1b12/tools/mo/openvino/tools/mo/front/tf/partial_infer/tf.py#L114-L117

and strange thing is that those int32 types that goes into TF are not modified by openvino these types are original TF types. Attached part of the graph from tensorboard
![image](https://user-images.githubusercontent.com/5703039/213770281-b61d0704-0ad6-45d1-a824-fd876a8d7258.png)

Before we move forward we need to clarify a couple of things:
1. Can you please check and verify that on TF models works well and does not fail around this `Any` operation?

2. And the second question. Could you please double check that network is saved with `training=False`? Some details about that. After failing there are also some warnings meaning that model was exported with training nodes:
```
If this input node is as switch between the training and an inference mode, then you need to freeze this input with value True or False.
In order to do this run the Model Optimizer with the command line parameter:
	--input "unused_control_flow_input_9->False" or --input "unused_control_flow_input_9->True"
... and so on..
```
also code of the model also looks like is in training mode
https://github.com/tensorflow/models/blob/9597de31d82f00ac9b8272c54b2192e7dc196f0f/research/delf/delf/python/training/model/delf_model.py#L228-L240

So could please double check and ensure that training is set to false during saving?

**Comment by mnl12** [comment]
Hi @pavel-esir,
Thanks for tracing the problem and your helpful explanations. Regarding your questions,
1. No issue I found in both training and testing of the TF model, as I did it quite many times.
2. The network is saved in export_local_and_global_model.py, and in the line 130
https://github.com/tensorflow/models/blob/12019f750fa78a897db5991e2b849de81139bd9b/research/delf/delf/python/training/model/export_local_and_global_model.py#L130
the training is set to False, which should overwrite the argument you mentioned in your previous comment. So training should be False during the saving of the model.
Thanks.

**Comment by pavel-esir** [comment]
@nnshah1 thank you for the quick reply! I see. Looks like problem is somewhere else. 

I also have update. I did some changes in MO; instead of relying on tf inference now it does it itself. After that this this error was gone, and not it fails at the end of converting (which is much better that on the beginning :))
```
  File "...\openvino\tools\mo\openvino\tools\mo\ops\tensor_iterator.py", line 322, in ti_type_infer
    internal_node = get_internal_node_by_layer_id(node, record['internal_layer_id'])
  File "...\openvino\tools\mo\openvino\tools\mo\ops\tensor_iterator.py", line 403, in get_internal_node_by_layer_id
    'Expected 1 node with `internal_layer_id`={}, {} found'.format(internal_layer_id, len(suitable_nodes))
AssertionError: Expected 1 node with `internal_layer_id`=48, 0 found
```

I am not sure if this error is helpful for you, but we continue on working to solve this issue. 

Meantime, could you please set data which you fed into input of the network? We will need this to check if our future fix works correctly.

**Comment by mnl12** [comment]
Hi @pavel-esir,
You can use the following inputs:
input_image= a numpy RGB image which could be any size, but preferably resized to 1024*1024, dtype=np.uint8
input_abs_thres=np.array([357.48], dtype=np.float32)
input_global_scales_ind=np.array([3, 4, 5], dtype=np.int32)
input_max_feature_num=np.array(1000, dtype=np.int32)
input_scales=np.array([0.25, 0.35355338, 0.5, 0.70710677, 1.0, 1.4142135, 2.0], dtype=np.float32))

Thanks.

**Comment by mnl12** [comment]
Hi,
I was wondering if you have any updates regarding the issue. Thanks.

**Comment by pavel-esir** [comment]
Hi @mnl12, sorry for late reply. We've merged a couple of corrections but the latest fix for While/TensorIterator error is not ready yet. It turned out to be the tricky one. There is a cycle in the model, which makes thing a bit complicated: 
![image](https://user-images.githubusercontent.com/5703039/215980627-1ae47a20-4eb8-4e72-9d4b-a4c267cee8e6.png)

usually such cycles are present for models with LSTM/RNN blocks and model optimizer pattern matcher tries to interpret it as some sort of RNN and pack into TensorIterator which is not correct because here is a While which shouldn't be packed into TensorIterator. We are fixing it not, but fix is not ready jet. I'll update when we have progress.

Thanks again for reaching to us and providing input argument for TF! This is really helpful: considering such nontrivial cases helps us to improve our product

**Comment by pavel-esir** [comment]
@mnl12 i have update. For this models While loop operation [research/delf/delf/python/training/model/export_model_utils.py#L152-L164](https://github.com/tensorflow/models/blob/4711f47537b17cf19bdba4610e36ff6521e21071/research/delf/delf/python/training/model/export_model_utils.py#L152-L164) during export is expanded into a subgraph with `Switch`, `Merge`, `NextIteration` and others.

We faced such problems only in TF1 frozen models and if models was exported with keys `lower_control_flow=True`, therefore full support was a not a priority when we were adding `While` op support. Unfortunately currently we have only partially support for that cases and full support was not planned to this release. We see request to support models with such `While`s and we will consider adding full support when next release will be planed. I will update when time for the next release comes.

Meanwhile, since the obstacle is that `While` loop is expanded into a set of ops, you can try to export this model differently so that while remains one single op (if that's possible). E.g. with explicit setting `lower_control_flow=False`. If you succeed in that then the model should be successfully converted

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask additional questions related to this topic.
