### ISSUE TITLE
Install OpenVINO™ toolkit for Raspbian* OS documentation issue

### ISSUE THREAD

**Issue by nullbyte91** [openvinotoolkit/openvino#1522]
Hello Team,

I'm trying to set up RPI 3+ with NCS2 using documentation page [openvino_docs_install_guides_installing_openvino_raspbian.html](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html). I'm able to query the device, but I'm unable to run any of the CNN application. For example, I'm getting the below error for object_detection_sample_ssd.

```bash
[ ERROR ] Check 'axis < static_cast<size_t>(input_rank)' failed at /teamcity/work/scoring_engine_build/releases_2020_1/ngraph/src/ngraph/op/gather.cpp:140:
While validating node 'Gather[Gather_852](patternLabel_848: float{10,20,30}, patternLabel_849: int64_t{5}, patternLabel_851: int64_t{1}) -> (??)':
The axis must => 0 and <= input_rank (axis: 4294967295).
```
I can see similar error for all the networks.

System and Software Information:
OS             : 2020-05-27-raspios-buster-full-armhf
OpenVino  : l_openvino_toolkit_runtime_raspbian_p_2020.1.023

**Comment by ilyachur** [comment]
Hi @nullbyte91,

The 2020.1 release had a bug https://github.com/openvinotoolkit/openvino/issues/411.
Could you please use newer version of OpenVINO, it should help.

Thanks.

**Comment by natxopedreira** [comment]
@nullbyte91 you have to compile from source to get rid of that bug, seems a persistent one.... since 2019 r3 or you need to use 2019 r3 models

But take care!! last release has another plug in myriad plugin.
[https://github.com/openvinotoolkit/openvino/issues/1330](https://github.com/openvinotoolkit/openvino/issues/1330)

In a perfect world you should know which branch works ok.... but i get no answer, i'm compiling all branch and post results

**Comment by nullbyte91** [comment]
@natxopedreira Thanks for the information. I'm going to do the same thing and update the results.

**Comment by nullbyte91** [comment]
Update:
I tried both 2020.1.023 and 2020.2.120 and didn't worked for me. OpenVino version 2020.3.220 with respective model zoo worked for me.
