### ISSUE TITLE
NCS2 + RPI3 - Performance trade-off between OpenVino native API, OpenCV back-end and ncsdk API

### ISSUE THREAD

**Issue by nullbyte91** [openvinotoolkit/openvino#1537]
Hello All,

I've experienced in OpenVino Toolkit, and I used for few Projects that run on CPU. Now, I'm trying to learn and do some project on RPI with NCS2. 

I come across three different ways to run CNN on NCS2 using RPI as a Host. What is the Performance trade-off between OpenVino Native API, OpenVINO with OpenCV's DNN backend and ncsdk from Movidius?

I'm getting into a lot of use with OpenVino Native API. Is OpenVino ToolKit supports all NCS2 features and the documents are updated?

@natxopedreira Any suggestion or thoughts?
-
Jegathesan S

**Comment by natxopedreira** [comment]
Im going to tell you my opinion.... keep away from openvino+rpi.

IMO openvino on rpi is a mess, i'm currently porting a project that im able to run on a x86 machine without problem in c++, but porting to rpi is a nightmare. It has some persistent bugs that seems no interest to solve or whatever the reason is, last version was my hope but now seems like there is a bug on myriad pluging and now it eats 100% cpu on one core.... seems like every release one thing broken.

Only take a look at all those issues in this repo related to rpi... that repeat over time.

**Comment by nullbyte91** [comment]
Thanks @natxopedreira . True. Even I'm facing a lot of issue with this porting work. Have you tried any other ARM platform i.e Jetson family?

**Comment by natxopedreira** [comment]
Yep, works great on a jetson nano, so i think is something related to armv7 as in arm64 ubuntu that nano use works ok. But who knows, you will get no info, you can spend your time doing analysis but you can not get info on current bugs status, so is very time consuming.

We have a covid related product, you can see it on our website if you are curious and in the begining i tested, jetson nano, coral usb and compute stick. I choose compute stick as i liked the api better, because OpenCV and performance. Even retrained a custom model...

Maybe works better on odroid or any armv8 board, not sure.......

**Comment by jgespino** [comment]
@nullbyte91 @natxopedreira Thank you for providing your input on the current user experience on RPi with NCS. I will pass this information on to the development team to address, It should not be this hard to get started on RPi and NCS.

We do have the [pre-built package](https://download.01.org/opencv/2020/openvinotoolkit/) for the [OpenVINO toolkit for Raspbian OS](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html) available, however, I did not see a 2020.4 package available yet. I am checking with the team about this and will get back to you.

The Intel Movidius Neural Compute SDK (NCSDK) only supports the original Intel Movidius Neural Compute Stick. As you are using the Intel Neural Compute Stick 2 (Intel NCS 2) you will need to use OpenVINO with the Myriad plugin. See Myriad plugin documentation for supported Networks and configuration parameters.

We also have some inference [performance ](https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks.html#intel-ncs2)data available for the Intel NCS 2.

Regards,
Jesus

**Comment by nullbyte91** [comment]
@natxopedreira Thank you so much for sharing your experience, and this will be helpful for people like me. 

@jgespino Thanks. As a developer, it shouldn't be this hard to get started, and the documentation and code are not updated or tested. For example, I found out working combination of OpenVino and Model Zoo version after trial and error and Few examples working with respective model zoo binary some of them not. But, the same binary working with an older version. Most of the edge devices based on ARM and it would great if we get support from Intel OpenVino development team. 

-
Jegathesan S

**Comment by jgespino** [comment]
Hi @nullbyte91 

The pre-built package for OpenVINO 2020.4 for Raspbian OS has been published, could you try it out and let me know if you have any questions?

Download [pre-built OpenVINO 2020.4 for Raspbian OS](https://download.01.org/opencv/2020/openvinotoolkit/2020.4/) and use [2020.4](https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/) models.

OpenVINO [Installation guide](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html) for Raspbian OS

**Couple of fixes that I requested to be updated in the document.**
When building samples use this command, directory was added.
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=armv7-a" /opt/intel/openvino/deployment_tools/inference_engine/samples/cpp`

Download models from 2020.4 release
```
wget --no-check-certificate https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-adas-0001/FP16/face-detection-adas-0001.bin
wget --no-check-certificate https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-adas-0001/FP16/face-detection-adas-0001.xml
```

Regards,
Jesus

Ref. 36087

**Comment by nullbyte91** [comment]
@jgespino I tried both C++ and Python samples with Intel models and I don't see any issues. Thanks for the release update.

@natxopedreira FYI.

**Comment by jgespino** [comment]
@nullbyte91 Glad it worked for you, please let me know if we can close this issue.
