### ISSUE TITLE
[Bug] Custom ops with dynamic input/output shapes

### ISSUE THREAD

**Issue by autumn110** [openvinotoolkit/openvino#15428]
**System information (version)**

- OpenVINO=> build from master branch

- Operating System / Platform => ubuntu18.04 on WSL

- Problem classification => custom ops

**Detailed description**
I have an onnx model with custom ops, which have dynamic input/output shapes. When I test the model with simple ov extension refering to the [doc of custom extension](https://docs.openvino.ai/nightly/openvino_docs_Extensibility_UG_add_openvino_ops.html)，an exception are thrown as like:
`terminate called after throwing an instance of 'ov::Exception'
  what():  Shape inference of Reference node with name o2 failed: Check 'false' failed at src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp:255:
Can't compute static output shape on 0 port for CustomTest node with name: CustomTest_81. Input shapes = ( 0 port = [?], ). Output shapes = ( 0 port = [?,?], 1 port = [?], )`

My custom op is mostly like nms, which the output shapes are determined after the operation has been performed. By reading the source code of nms op, I've found it uses the `InternalDynShapeInfer` for this problem but have no idea how to solve it with custom ops. The example code and data are as follows

[test.zip](https://github.com/openvinotoolkit/openvino/files/10554000/test.zip)

**Comment by mlukasze** [comment]
he @autumn110 
thanks for hitting us, let us check what happened.

@mbencer could you take a look, please?

**Comment by ilyachur** [comment]
CC @jane-intel

**Comment by autumn110** [comment]
hi, after debugging into the internal code, maybe I've found where the problem is.  

it seems like custom ops are mapping into the `Reference `node when compiling the model  
![image](https://user-images.githubusercontent.com/124126622/216304058-2344f54a-03ce-48ba-a817-21d500c6aa85.png)

the `Reference` uses `NgraphShapeInferFactory` creating an `entryFallback `for the shape inference which causes the exception
![image](https://user-images.githubusercontent.com/124126622/216305591-881c5629-bc47-40e0-81d6-109ef9c9c0db.png)

meanwhile, the `Reference `node only supports static shapes as the code shows and call the evaluate function of custom ops with static dims
![image](https://user-images.githubusercontent.com/124126622/216306791-3cd44b9b-1fca-467e-b10b-14d833387719.png)

is there any simple workaround for making the Reference dynamic, any suggestions?

**Comment by mbencer** [comment]
Hi @autumn110 
I've analyzed you code from `test.zip` a bit and I have a few comments:
1. As I understand both `out0` and `out1` should have the same and element type as input. I see, that you make some experiments, but it should be reflected in `set_output_type` call. Otherwise, I am sure if dynamic shape cases from custom ops will be supported during inference on CPU. @jane-intel Correct me if I am wrong.
2. The memory for output tensor of such a custom is allocated in https://github.com/openvinotoolkit/openvino/blob/21fc5fbd75b00505bd18d4b6056a31648ce47eb6/src/plugins/intel_cpu/src/nodes/reference.cpp#L70 (CPU plugin fallbacks execution to evaluate `method`) and you should change shape of output tensor inside the evaluate method (at least in the current design).
I've done some experiments with your code and using [such version](https://github.com/openvinotoolkit/openvino/files/10581036/15428.zip) I can run inference successfully.
Please let me know if it works for you.

**Comment by autumn110** [comment]
hi @mbencer thanks for your help.  
As for your first comment, I totally agree with you if you could easily know the output shape from input shape and values,  by using `set_output_type` the dynamic shape cases are supported as you said. However, my case is a little bit complicated, just like some internal implemented ops, for example **non-maximum suppression**, as the output shape could not be determined until the calculation of op has finished. So in this case, I cannot simply use the `set_output_type` to setup the shape info. As the function **validate_and_infer_types** is called many times, that will cause severe performance issue.

**Comment by autumn110** [comment]
well, I think I'm understanding what you mean. 

You mean in the `validate_and_infer_types` function, I could use a placeholder shape like input shape as your code

>     set_output_type(0, get_input_element_type(0), get_input_partial_shape(0));

and in `evaluate` function, after computation finished I could change the output shape manually and then assign results. I have used `set_shape` function but crash again. Which method should I use to change the memory shape in `Reference` by outside `ov::Tensor` object?

@mbencer Not sure my understanding is correct.

**Comment by mbencer** [comment]
Hi @autumn110
> You mean in the validate_and_infer_types function, I could use a placeholder shape like input shape as your code

I mean, that that you should set here a static shape if possible or provide the code which calculate the output shape in most accurately way as possible (to avoid dynamic shapes). I've put here `set_output_type(0, get_input_element_type(0), get_input_partial_shape(0));` because I've thought that is expected here (based on your comments), but I can be wrong ;)
> and in evaluate function, after computation finished I could change the output shape manually and then assign results. I have used set_shape function but crash again. Which method should I use to change the memory shape in Reference by outside ov::Tensor object?

You shouldn't set the output shape in evaluate method at all. An output tensor has a shape (and a memory) calculated in `validate_and_infer_types`. Be aware that `validate_and_infer_types` is called also during during `infer` step when input data is known, so we can propagate shapes thourgh the graph.

Unfortunately, the cases where output shapes depends on calculated results (like NMS) are not supported now.
Source: https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_CPU.html
![image](https://user-images.githubusercontent.com/11331953/217308138-d8da08fa-ec5c-4494-9a5c-0fc430a3cbba.png)

I believe, that in such a case you should implement also CPU custom op. @nshchego Could you confirm it and do you maybe know if we have some instruction about CPU custom ops (using the new API)?

**Comment by autumn110** [comment]
hi @mbencer, thank you so much for your support.

So it looks like internal dynamism of custom ops is not supported now and I didn't find any instruction about cpu custom ops. In this case I've written a new cpu node based on `Reference` which successfully support the dynamism and temporarily solved my problem without causing other issues. However it's only a workaround for me, I'm really looking forward to the offical support in the near future.

**Comment by slyalin** [comment]
If my understanding of the issue is correct, we have an internal record for this defect, 99106. CCed @dmitry-gorokhov, @maxnick

**Comment by maxnick** [comment]
Hi @autumn110 , we are working on the internal dynamism support within the CPU plugin `Reference` node, so custom nodes with this feature will also be supported. PR will be ready soon.

**Comment by autumn110** [comment]
hi @maxnick , i find the PR has been merged into master, so i'm wondering how to write extension with the new internal dynamism? any example about this?

**Comment by autumn110** [comment]
hi @maxnick , thanks for your great work! I tested my ops according to your unit test of the PR, it works well. However, I find it has performance issue in my case due to large output tensor data. 

I read the new reference.cpp code, find it will copy output data of each output tensor by cpu_memory if the status is `ShapeInferStatus::skip` 

https://github.com/openvinotoolkit/openvino/blob/016d36f03259531c69a46efee58252144eeea13b/src/plugins/intel_cpu/src/nodes/reference.cpp#L109

So is there a way that only copy the output of dynamic shape if necessary? And for the pre-determined shape I could use the memory directly like static tensor. This is like an intermediate state between the `ShapeInferStatus::success` and `ShapeInferStatus::skip` 

Thanks in advance

**Comment by maxnick** [comment]
Hi @autumn110, when the shape is static https://github.com/openvinotoolkit/openvino/blob/fc98454174859d1943dabf833539f002fb596a73/src/plugins/intel_cpu/src/nodes/reference.cpp#L62-L68 code path is used. But, in that situation the output shape should be know in advance, on the compile model stage.
Also a ov Tensor interface has been merged recently (see https://github.com/openvinotoolkit/openvino/blob/7bce07a46e570e02e657cc1817e25963dd9a9f89/src/core/dev_api/openvino/runtime/itensor.hpp). So I think it is possible to write a wrapper over the CPU internal memory class and use the following ov::Tensor constructor: https://github.com/openvinotoolkit/openvino/blob/b2a2266f603c3372a2c2f69341d96bce99c8dd96/src/core/include/openvino/runtime/tensor.hpp#L60. Thus we theoretically should be able to remove the copy at all.

**Comment by autumn110** [comment]
hi @maxnick , thanks for your quick reply! it'll be great that could combine CPU internal memory with ov::Tensor. So currently it's not fully ready for removing the copy? I'm really looking forward to it in the future.

**Comment by maxnick** [comment]
I think it is ready, just needs to be implemented and tested.
