### ISSUE TITLE
FP16 compressed model holds FP32 data type for most of the layers - why?

### ISSUE THREAD

**Issue by kamalasubha** [openvinotoolkit/openvino#15439]
Hi all,
I explored the model optimizer that converts floating point weight to FP16 datatype [https://docs.openvino.ai/latest/openvino_docs_MO_DG_FP16_Compression.html](URL). When I checked the XML file of one compressed FP16 model, I could see the FP32 datatype on most of the layers. Should all layers have FP16 datatype rite? Please correct me if I am wrong.
![file](https://user-images.githubusercontent.com/36927102/216091447-0c436ca6-0c8e-453d-bff1-b75d8c0d29c2.png)

**Comment by ilya-lavrenov** [comment]
Hi @kamalasubha 

FP16 IR stores constants (model weights and other data) as FP16, but precisions of operations are still as in framework. See https://docs.openvino.ai/latest/openvino_docs_MO_DG_FP16_Compression.html. So, FP16 in IR is just a compression mode to have 2x less IR size in average.

If you want to affect inference aspects, you can use [ov::inference_precision](https://docs.openvino.ai/latest/groupov_runtime_cpp_prop_api.html#doxid-group-ov-runtime-cpp-prop-api-1gad605a888f3c9b7598ab55023fbf44240).

**Comment by lalith-mcw** [comment]
> If you want to affect inference aspects, you can use [ov::inference_precision](https://docs.openvino.ai/latest/groupov_runtime_cpp_prop_api.html#doxid-group-ov-runtime-cpp-prop-api-1gad605a888f3c9b7598ab55023fbf44240):
> 
> ```c++
> ov::Core core;
> auto cm_fp16 = core.compile_model("model_fp32.xml", "GPU", ov::inference_precision(ov::element::f16));

Tried the same in python 

API
`core.get_property("CPU", "OPTIMIZATION_CAPABILITIES")`

Output:
```
OPTIMIZATION_CAPABILITIES:
['BF16', 'FP32', 'FP16', 'INT8', 'BIN', 'EXPORT_IMPORT']
```

But when tried out:
API
`core.compile_model(mode, "CPU", {"INFERENCE_PRECISION_HINT": "F16"})`

Error:
`Wrong value for property key INFERENCE_PRECISION_HINT. Supported values: bf16, f32`

**Comment by ilya-lavrenov** [comment]
`OPTIMIZATION_CAPABILITIES` for CPU lists `FP16` just to denote that CPU can inference FP16 IR files. We agree it's confusing and we are planning to work on better clarification what `OPTIMIZATION_CAPABILITIES` specifies.

But as it was stated in the error message - x86 CPU device is not able to perform inference in FP16 and only BF16 and FP32 are supported, since there are no instructions in current generation of HW to optimally perform computations in FP16.

FP16 inference is available on ARM CPUs or Intel GPUs.
