### ISSUE TITLE
The results are different for each inference.

### ISSUE THREAD

**Issue by worker-ljw** [openvinotoolkit/openvino#15491]
![1675425399374](https://user-images.githubusercontent.com/105470801/216597892-06b31910-2a64-4ab3-9eec-0c6d7a7c4851.png)

**Comment by brmarkus** [comment]
Can you provide more information about your environment, please (OS, which version of OS, which version of OpenVINO and how it was installed, which version of Python, running on which HW, which CPU)?

Where and how have you retrieved the MobileNet-V2 model (how, in which version, using the model-downloader of the same installed version of OpenVINO)?

Can you show examples of what you get, and how they are different for multiple run/cycle, please?

Do you see the same behavior when using the IR variant of the model, instead of using the ONNX variant?

Which input file "demo.png" do you use, in RGB or BGR?

**Comment by vladimir-paramuzov** [comment]
@worker-ljw Seems like you haven't called `infer_request.infer()` before getting output tensor. In that case output memory may be uninitialized.

**Comment by worker-ljw** [comment]
You get it!
