### ISSUE TITLE
Whether using multiple models at the same time will affect the inference effect？

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#15730]
I want to achieve high performance ocr with openvino, I need to detect and recognize both models compile on cpu.

I  traversed hundreds of pictures and measured their time consumption. One picture needs to be detected once and recognized many times.

But I found that this will cause the recognition model to be time-consuming and unstable in the throughput mode. The recognition time may fluctuate from 40ms to 70ms, but the multi-threading with onnx is relatively stable;

I would like to ask if the two models are compiled differently，is it will cause a conflict in cpu usage? In general, onnx multithreading will be a little faster, because the time change of the recognition process is relatively stable.
I have used the `AsyncInferQueue`  and set it to the core count of cpu (20/2=10, not 20):
https://github.com/openvinotoolkit/openvino/issues/15573#event-8512643071
(there are also some onnx information in it)

These are my config info：
reconition:
![image](https://user-images.githubusercontent.com/96160062/219003483-19a5a80e-804d-4fd7-9b7b-b25af9c762cf.png)
![image](https://user-images.githubusercontent.com/96160062/219003594-8f764f8d-b17d-4335-b8fc-ab7578cb94ed.png)
detection:
![image](https://user-images.githubusercontent.com/96160062/219003878-bd1ff320-318b-47e3-850c-7ba4a7ab5ad0.png)

**Comment by Iffa-Meah** [comment]
Achieving high performance when inferencing multiple models in a single inference really depends on how you design your code and process the data.

For example, the [OpenVINO Security Barrier Demo](https://docs.openvino.ai/latest/omz_demos_security_barrier_camera_demo_cpp.html) is actually using 3 models in a single inference:
1. vehicle-license-plate-detection-barrier-0106 (detection)
2. vehicle-attributes-recognition-barrier-0039 (object attributes)
3. license-plate-recognition-barrier-0001 (ocr)

The models are chained together in a way that when the original frame is sent to the first vehicle in the license plate detection model, the model detects the presence of a vehicle with a license plate in the frame. The output of this first model would contain the x,y coordinates of these two objects (vehicle and plate).

The application draws bounding boxes around those objects and they are cropped. The license plate from model 1 output is sent to model 2 as input and model 3 would receive the cropped region of the vehicle as input and recognize the vehicle type and colour.

It's important to have handlers that cascade those processes and their flow because these are one of the factors that contribute to the inferencing performance especially if they are dependent on each other. Using [AsyncInferQueue](https://docs.openvino.ai/latest/openvino_docs_ie_plugin_dg_async_infer_request.html) which you mentioned above is a great choice.

Perhaps you need two or more executors to overlap compute tasks of your CPU and a remote device the plugin works with. Otherwise, CPU and device tasks are executed serially one by one and thus, increasing CPU consumption.

**Comment by wangleis** [comment]
@sanbuphy By default, CPU plugin will use all CPU resource for each network model. So there is conflict in cpu usage when you run two network on one CPU.

Could you try the following two options separately and check if they can improve your situation?

1. Add `"AFFINITY": "NUMA"` in your config of compile_model().
2. After option 1, set `"INFERENCE_NUM_THREADS:number"` in your config of compile_model(). Detection model and recognition model can be set different number. But total number should less than the number to processors in system.

**Comment by Wan-Intel** [comment]
Please allocate maximum number of threads that can be used for compilation tasks.

For more information, please refer to[ov::inference_num_threads {"INFERENCE_NUM_THREADS"};](https://docs.openvino.ai/latest/groupov_runtime_cpp_prop_api.html#doxid-group-ov-runtime-cpp-prop-api-1gae73c9d9977901744090317e2afe09440)
