### ISSUE TITLE
How to optimise Detectron models using MO?

### ISSUE THREAD

**Issue by fuzzyBatman** [openvinotoolkit/openvino#158]
Good day.

On [this](https://docs.openvinotoolkit.org/latest/_inference_engine_ie_bridges_python_sample_instance_segmentation_demo_README.html) page it states

### This sample demonstrates how to run Instance Segmentation models from Detectron or maskrcnn-benchmark using OpenVINO™.

and on scrolling down

### Before running the demo with a trained model, make sure the model is converted to the Inference Engine format (*.xml + *.bin) using the Model Optimizer tool.

Is there a procedure to optimise Detectron models? Detectron is based on the Caffe2 framework.

**Comment by shubha-ramani** [comment]
Dear @fuzzyBatman 
As discussed in [this forum post ](https://software.intel.com/en-us/forums/computer-vision/topic/810077) I filed a bug on this issue. The reason is that we mention support for Detectron in our documentation as a supported image segmentation model, yet we don't provide steps to generate IR, nor do we download the model via downloader.py . Thanks for your patience !

Sincerely,
Shubha
