### ISSUE TITLE
intel hd500 win10 openvino 2020/4

### ISSUE THREAD

**Issue by natxopedreira** [openvinotoolkit/openvino#1586]
Hello

I have a celeron intel nuc [https://ark.intel.com/content/www/us/en/ark/products/190736/intel-nuc-8-rugged-kit-nuc8cchkr.html](https://ark.intel.com/content/www/us/en/ark/products/190736/intel-nuc-8-rugged-kit-nuc8cchkr.html) on win10 executing the sample hello_query_devicet shows GPU as available for inference (intel 500 hd).

running object sample with a simple model takes 3 minutes to load the model, model is light
`https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-retail-0004/FP16/`

gpu driver is 26.20.100.8141
windows 10 pro, clean install
openvino 2020/4

Im able to do inference perfectly on CPU and MYRIAD

is that the expected behaviour, 3 minutes to load model to gpu? I also noted that cpu usage is not normal, same app doing inference on MYRIAD CPU is 30% usage and in GPU is 70%

**Comment by vladimir-paramuzov** [comment]
@natxopedreira  Usually most of the time is spent on ocl code compilation. Consider enabling [cl_cache](https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md) 

As for CPU usage, it's caused by the fact that the ocl runtime waits for completion of each kernel in a spin loop. If you want to reduce CPU usage, consider enabling [KEY_CLDNN_PLUGIN_THROTTLE](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_CL_DNN.html) plugin option

**Comment by natxopedreira** [comment]
ok, thank you @vladimir-paramuzov , i will try
