### ISSUE TITLE
Need to be able to build with pre-downloaded dependencies

### ISSUE THREAD

**Issue by bwarden** [openvinotoolkit/openvino#165]
When running cmake for the inference-engine, the scripts attempt to download numerous files, including several from https://download.01.org/opencv/2019/openvinotoolkit/R1/inference_engine/. In order to support reproducible package builds for Clear Linux, all dependencies must be downloaded ahead of time and archived. Network access is explicitly disabled at build time in order to ensure a consistent build environment.

We can automatically download and extract the files wherever is appropriate, but I haven't found a way to inform e.g. inference-engine/cmake/dependencies.cmake where to look for the necessary firmware files, instead of attempting to download them.

I tried explicitly setting the paths, not to mention putting the files in the expected locations:
```
root@mock ~/build/BUILD/dldt-2019_R1.1/inference-engine/clr-build # ls -l ../temp/vpu/firmware/ma2450/mvnc/MvNCAPI-ma2450.mvcmd ../temp/vpu/firmware/ma2480/mvnc/MvNCAPI-ma2480.mvcmd
-rw-r--r-- 1 mockbuild mockbuild 1412868 May 29 15:43 ../temp/vpu/firmware/ma2450/mvnc/MvNCAPI-ma2450.mvcmd
-rw-r--r-- 1 mockbuild mockbuild 1804880 May 29 15:43 ../temp/vpu/firmware/ma2480/mvnc/MvNCAPI-ma2480.mvcmd
root@mock ~/build/BUILD/dldt-2019_R1.1/inference-engine/clr-build # cmake -L .. -DVPU_FIRMWARE_MA2450_FILE=../temp/vpu/firmware/ma2450/mvnc/MvNCAPI-ma2450.mvcmd -DVPU_FIRMWARE_MA2480_FILE=../temp/vpu/firmware/ma2480/mvnc/MvNCAPI-ma2480.mvcmd
```
...and it even deletes `../temp/vpu/firmware/ma2450` then attempts to download it again.

**Comment by vmatveic** [comment]
Hi @bwarden ,

Your question is correct. Moreover, you suggested correct way to solve it - by specifying of the corresponding environment variable to your custom path. But the idea is that you need to chage it little bit.
Details: we already have dependency_solver functionality implemented on CMake level of the project. The idea is that it checks if the corresponding environment variable is set or no. If it's already set then it doesn't fetch the dependency. If it's not set it fetches it and unpack. The main thing is that you used VPU_FIRMWARE_MA2480_FILE variable which is rewritten AFTER the dependency solver execution.
That's why you see that the `../temp/vpu/firmware/ma2450` is deleted and downloaded again.

So, please check `<dldt_repo/inference-engine/cmake/dependencies.cmake>` file. Here you can see that VPU_FIRMWARE_MA2450 (**without** `_FILE`) is used. So, please try to set VPU_FIRMWARE_MA2450 to the required directory and the dependency_solver should skip it!

Thanks!

**Comment by AnastasiaKazantaeva** [comment]
It seems that problem have been solved, because no reply. If you faced with this problem again, reopen this issue or better create a new one
