### ISSUE TITLE
[Bug] Device query freezes

### ISSUE THREAD

**Issue by multiflexi** [openvinotoolkit/openvino#17190]
##### System information (version)
- OpenVINO Source => [AUR](https://aur.archlinux.org/packages/openvino)
- OpenVINO Version => Version 2022.3
- Operating System / Platform => Manjaro
- Compiler => Cmake
- Problem classification: Query device
- Device use: GPU - Intel Arc A380

##### Detailed description
When I run query device  as described [here](https://docs.openvino.ai/latest/openvino_inference_engine_ie_bridges_python_sample_hello_query_device_README.html) the script is just stuck and does nothing

##### Steps to reproduce
`python /opt/intel/openvino/samples/python/hello_query_device/hello_query_device.py`

**Comment by Iffa-Meah** [comment]
@multiflexi Could you elaborate further on the steps/settings that you did to get the OpenVINO setup ready?
I'm validating this with Ubuntu to see whether the problem comes from the software that you shared or else.

It would be great if you could also share if there's anything prompted once you run the script.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by multiflexi** [comment]
I installed OpenVINO from AUR. I have not set or modified anything. All I see when I run it is `[ INFO ] Available devices:` and I cannot kill it with Ctrl+C.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
