### ISSUE TITLE
why there is so many Reorder layers when i use openvino to infer

### ISSUE THREAD

**Issue by jlygit** [openvinotoolkit/openvino#172]
why there is so many Reorder layers when i use openvino to infer and these layers take a lot of time.

![image](https://user-images.githubusercontent.com/10195989/58937550-4f390000-87a5-11e9-8bb5-000c0851f698.png)

**Comment by shubha-ramani** [comment]
Dear @jlygit,
It's a great question. Let me ask - are you using an NCS2 device ? If not, which device are you using ? Is the model a Tensorflow model ? Let me give you some ideas:
1) if it's a Tensorflow model, well Tensorflow uses NHWC tensors while Inference Engine uses NCHW so a reorder can happen to get the layer format into NCHW. By the way, Tensorflow is the odd-ball, since all the other networks are happy with NCHW and Inference Engine was designed for everybody, not just Tensorflow.

2)How large is the input tensor ? Is it perhaps 5D ? Again it is not NHWC and before processing  Model Optimizer should insert a reorder layer to get back to NHWC, then translate 5D part of the graph as is and add layer to convert to NCHW again after 5D piece is done.

3) are you using NCS1 rather than NCS2 ? Because NCS1 will actually compute in NHWC layout. So Myriad plugin will do reverse graph transformation from NCHW IR to internal NHWC representation. 

4)And the plugin will once again do re-orders if faced with a 5D tensor...

My point is, depending on your situation, you could end up with a long chain of re-orders.  These can definitely be optimized however (stick with 4D tensors), don't use NCS1, etc...

Please give me more details about your configuration.

Thanks for using OpenVino !

Shubha

**Comment by ilyachur** [comment]
@jlygit Do you have the same behaviour for the last OpenVINO package?
Can you provide more details about the CPU?

@dmitry-gorokhov FYI

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
