### ISSUE TITLE
[Bug] Model doesn't run correctly on the GPU

### ISSUE THREAD

**Issue by fintan-osullivan-pk** [openvinotoolkit/openvino#17849]
##### System information (version)

- OpenVINO Source=> pip install
- OpenVINO Version=> 2023.0.0
- Operating System / Platform => Ubuntu 20.04
- Compiler => Visual Studio Code
- Problem classification => GPU
- Device use: => CPU / GPU
- Framework => OpenVINO IR
- Model name => CREStereo depth estimation model at 360x640

##### Detailed description
When I run my model on the GPU the output is an array filled entirely with zeros. When I run my model on the CPU the output produces a disparity map as expected. 

##### Steps to reproduce

Download the zip file below and run `tutorial.py`. It will print an array of zeros to the console and show the input image alongside a colour image of the disparity (which is entirely black). Change `device_name=GPU` to `device_name=CPU` on line 31 in `tutorial.py` to see the expected behaviour. 

https://drive.google.com/file/d/1ZhqBSNNAEa4p0Sry938wljkz4FJrNjJr/view?usp=share_link

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [x] There is reproducer code and related data files: images, videos, models, etc.

**Comment by YuChern-Intel** [comment]
I try running your model with Benchmark App on GPU and it works well.
![GPU](https://github.com/openvinotoolkit/openvino/assets/107900329/e1e259a7-2fdf-4e68-93ff-9af2a52132dd)

Try converting your native model into Intermediate Representation(IR) with FP16 precision and read model in FP16 precision.

**Comment by fintan-osullivan-pk** [comment]
The issue here is not that the model won't run on GPU, but that the output is basically empty. The output from running the model on GPU is an array filled with 0s whereas when I run the model on the CPU the output is populated with real values that make a disparity map, as expected. If you run `tutorial.py` in the folder I attached above you will see what I mean.

**Comment by YuChern-Intel** [comment]
Yes, I was able to reproduce the same results.

I noticed that your shared IR is being converted using Model Optimizer 2022.3. 

Could you try to re-convert your native model into IR using Model Optimizer 2023? 

Please let us know if that fixes your model or same issues still exist.

**Comment by fintan-osullivan-pk** [comment]
I re-converted my native model into IR with the updated Model Optimizer but I still have the same issues: works on CPU but not on GPU.

**Comment by avitial** [comment]
@fintan-osullivan-pk we are able to see the described behavior, would it be possible to share the native model and the exact MO command you used to convert to IR? 

**CPU plugin**: next_output [[[[ 1.6629673e+00  1.6754805e+00  1.6852705e+00 ...  1.2467437e+00
     1.2500914e+00  1.2611349e+00]
   [ 1.6812816e+00  1.6749096e+00  1.6901224e+00 ...  1.2657838e+00
     1.2612404e+00  1.2657968e+00]
   [ 1.6758679e+00  1.6751609e+00  1.6818929e+00 ...  1.2569264e+00
     1.2496560e+00  1.2428367e+00]
   ...
**GPU plugin**: next_output [[[[-0.         -0.         -0.         ... -0.         -0.
    -0.        ]
   [-0.         -0.         -0.         ... -0.         -0.
    -0.        ]
   [-0.         -0.         -0.         ... -0.         -0.
    -0.        ]
   ...

**Comment by fintan-osullivan-pk** [comment]
Yes, no problem. Here is the native model:

https://drive.google.com/file/d/1qTaE5rEyoQoyTM8_rVeRDjz0j8LZ-j8M/view?usp=drive_link

And the exact MO command was just: `mo --input_model INPUT_MODEL` where INPUT_MODEL is the onnx model attached above.

**Comment by avitial** [comment]
@fintan-osullivan-pk thanks for providing the model file, it is not clear what may be causing the output disparity while using GPU plugin. I have submitted a bug report for investigation, will provide more details as they become available.


Ref. 114017

**Comment by avitial** [comment]
@fintan-osullivan-pk it seems the issue has been addressed in master branch, I just had a tried with the latest master branch and the issue is no longer observed. You can try building from source as per [build instructions](https://github.com/openvinotoolkit/openvino/wiki#how-to-build) or wait for the next OpenVINO release which should include the fix. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Running on  CPU | Running on  GPU
-- | --
[[[[   1.6629713e+00  1.6754851e+00  1.6852756e+00 ...  1.2467463e+00        1.2500939e+00  1.2611372e+00]      [ 1.6812860e+00  1.6749148e+00  1.6901274e+00 ...  1.2657864e+00        1.2612430e+00  1.2657993e+00]      [ 1.6758732e+00  1.6751661e+00  1.6818981e+00 ...  1.2569288e+00        1.2496583e+00  1.2428392e+00]      ...      [ 1.6487892e+00  1.6700194e+00  1.6813900e+00 ...  1.4786767e+00        1.4782768e+00  1.4757156e+00]      [ 1.6417453e+00  1.6649209e+00  1.6811328e+00 ...  1.4787700e+00        1.4784216e+00  1.4765401e+00]      [ 1.6529703e+00  1.6716962e+00  1.6889484e+00 ...  1.4736183e+00        1.4748025e+00  1.4752485e+00]]         [[ 1.2246068e-03  1.1799248e-03  1.1646259e-03 ...  4.9319813e-05        2.5505280e-05 -3.4559158e-05]      [ 1.1882036e-03  1.1517991e-03  1.1596826e-03 ... -5.8657421e-05       -3.3412351e-05 -6.2598883e-05]      [ 1.1395608e-03  1.1236244e-03  1.1309593e-03 ... -4.6430869e-06        3.5242767e-05  6.7900357e-05]      ...      [ 4.2005224e-05  3.6048747e-05  4.9054383e-05 ...  5.9874664e-04        5.3915859e-04  4.8920291e-04]      [-2.1031774e-05  1.7537619e-05  4.9560724e-05 ...  6.3950999e-04        5.8247853e-04  5.2794779e-04]      [-9.0571455e-05 -3.2277094e-05  1.1954646e-05 ...  7.7600509e-04        6.4448145e-04  5.3900835e-04]]]] | [[[[   1.6629528e+00  1.6754646e+00  1.6852534e+00 ...  1.2467188e+00        1.2500665e+00  1.2611102e+00]      [ 1.6812658e+00  1.6748934e+00  1.6901048e+00 ...  1.2657588e+00        1.2612157e+00  1.2657721e+00]      [ 1.6758492e+00  1.6751411e+00  1.6818718e+00 ...  1.2569019e+00        1.2496316e+00  1.2428124e+00]      ...      [ 1.6487864e+00  1.6700188e+00  1.6813905e+00 ...  1.4786656e+00        1.4782660e+00  1.4757049e+00]      [ 1.6417428e+00  1.6649208e+00  1.6811335e+00 ...  1.4787589e+00        1.4784106e+00  1.4765295e+00]      [ 1.6529690e+00  1.6716967e+00  1.6889498e+00 ...  1.4736053e+00        1.4747905e+00  1.4752373e+00]]         [[ 1.2246028e-03  1.1799036e-03  1.1645957e-03 ...  4.9361108e-05        2.5545887e-05 -3.4524139e-05]      [ 1.1881809e-03  1.1517692e-03  1.1596517e-03 ... -5.8618585e-05       -3.3373897e-05 -6.2562256e-05]      [ 1.1395332e-03  1.1235955e-03  1.1309332e-03 ... -4.6063542e-06        3.5281872e-05  6.7942143e-05]      ...      [ 4.1992425e-05  3.6033685e-05  4.9038506e-05 ...  5.9874239e-04        5.3916126e-04  4.8921397e-04]      [-2.1044201e-05  1.7523169e-05  4.9545197e-05 ...  6.3949934e-04        5.8247673e-04  5.2795548e-04]      [-9.0585490e-05 -3.2292060e-05  1.1937445e-05 ...  7.7598338e-04        6.4447150e-04  5.3901237e-04]]]]



</div>


</body>

</html>

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
