### ISSUE TITLE
[Bug] plugins.xml file is absent in the 2023.0 release

### ISSUE THREAD

**Issue by sbudenkov** [openvinotoolkit/openvino#17971]
##### System information (version)

OpenVINO Source=> Runtime
OpenVINO Version=> Version 2023.0
Operating System / Platform => Windows 64 Bit / Ubuntu 20 / Ubuntu 22
Compiler => Visual Studio 2022/ Cmake
Problem classification => Release package
Device use: => CPU

##### Detailed description
If download release package from: https://storage.openvinotoolkit.org/repositories/openvino/packages/2023.0/
plugins.xml file is absent

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [ ] There is reproducer code and related data files: images, videos, models, etc.

**Comment by ilya-lavrenov** [comment]
Hi @sbudenkov 

This is expected.
Since 2023.0 OpenVINO has a mode to compile without plugins.xml file:
https://github.com/openvinotoolkit/openvino/blob/a14a2c0eb02afbc8b85d8940dee3df0026b46d23/cmake/features.cmake#L103-L105
And by default we build without this file since several users complain that it's not convenient for them to have such files in their distribution.

**Comment by sbudenkov** [comment]
Hi @ilya-lavrenov,

Good. I'm using dynamic libraries. What option should I set? Because now I've got an error.

**Comment by ilya-lavrenov** [comment]
> Good. I'm using dynamic libraries. What option should I set? Because now I've got an error.

Please, provide an error you observe.

**Comment by avitial** [comment]
Closing this due insufficient info and lack of activity. Feel free to reopen and provide the requested info or to ask any questions related to this topic.
