### ISSUE TITLE
Huge loss of precision on VPU with HW optimizations enabled

### ISSUE THREAD

**Issue by leoll2** [openvinotoolkit/openvino#1822]
##### System information (version)

- OpenVINO=> 2020.4
- Operating System / Platform => Ubuntu 18.04
- Compiler => g++
- Problem classification => VPU - Wrong output

##### Detailed description

Myriad (NCS2) suffers from heavy precision loss when `VPU_HW_STAGES_OPTIMIZATION` is enabled.

Let's consider this extremely simple network, made of a single convolution block:
![img](https://i.imgur.com/CFlbqey.png)

After running inference (with hw optimizations enabled) on the same image on CPU and MYRIAD respectively, I printed (part of) the output:
![img](https://i.imgur.com/OkcwMeU.png)

This CPU/VPU output comparison shows that some values are already inaccurate to the second decimal place, after just one layer. One could deem this acceptable, however any realistic network is composed of many more layers, and of course the problem gets worse as the inaccuracies stack as we go deeper in the model.   

For instance, this is what the output deviation looks like after 10 conv blocks like that above:
![img](https://i.imgur.com/GEayqPx.png)
Some numbers are now quite different (e.g. 0.21 vs 0.31, -0.01 vs -0.08).

At the end of my network, about 50 blocks later, the situation becomes embarassing, and the Myriad output is unusable in practice:
![img](https://imgur.com/E2oClfU.png)

I know many people recommend to disable `VPU_HW_STAGES_OPTIMIZATION`, but this also causes a significant performance drop in terms of latency and throughput. Honestly, I don't see why the effect of any properly designed optimization would affect the network accuracy so negatively.  

Is the VPU accuracy supposed to be so low?  
I am curious to know more details about what hardware optimizations get activated by that flag, and whether there is any way to turn them on/off individually.

Thanks in advance.

##### Steps to reproduce

I uploaded [here](https://easyupload.io/d5lvz7) the chunks of my model that I have used for inference, plus the sample image. Then you can easily print any output value you prefer, the loss of precision is everywhere.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [x] There is reproducer code and related data files: images, videos, models, etc.

**Comment by dkurt** [comment]
Hi!
May I ask to try an experiment with `[0..255]` input range for network? With and without `VPU_HW_STAGES_OPTIMIZATION` .

**Comment by leoll2** [comment]
@dkurt 
The relative error looks smaller if I provide an input in the [0..255] range. Is it all about the working point?
By the way, it's curious how the magnitude of VPU values seems to be always lower than CPU ones by 2-10%, never greater: maybe the VPU introduces a bias when rounding internally?

[0..1] no optimization  |  [0..1] with optimization
:-------------------------:|:-------------------------:
![](https://imgur.com/6Lg9lQy.png)  |  ![](https://imgur.com/dNEgJ5m.png)

[0..255] no optimization  |  [0..255] with optimization
:-------------------------:|:-------------------------:
![](https://imgur.com/EEQ6j1s.png)  |  ![](https://imgur.com/JYsrXr1.png)

**Comment by dkurt** [comment]
Actually, it's interesting to see the difference between `[0..1]` inputs with and w/o HW optimization and `[0..255]` input but with convolutions weights divided by 255. So first convolution layer will perform this normalization. Can you try please?

**Comment by leoll2** [comment]
This is the output right after the first conv. Left is standard (input in range [0..1]), right is rescaled (input in [0..255], weights of first conv layer divided by 255). I display one more decimal digit to show better the differences.
Optimizations are enabled in both experiments.

[0..1] standard  |  [0..255] weights rescaled
:-------------------------:|:-------------------------:
![](https://imgur.com/ccZKn0X.png)  |  ![](https://imgur.com/bzeZBVn.png)

As you can see, rescaling does not look better.

As for the final network output (after many layers), the values look very different between 'standard' and 'rescaled', even on CPU, so I don't even plot them.

**Comment by leoll2** [comment]
Hi @dkurt and @jgespino !
Any update on this?

**Comment by mhkabir** [comment]
@jgespino any updates on this?

**Comment by jgespino** [comment]
Hi @mhkabir 

Please share the model and image once more, I am unable to access the easyupload link in the original post.

Regards,
Jesus

**Comment by leoll2** [comment]
Hi @jgespino, 
here is are the models and image:
https://drive.google.com/file/d/1Qv9YFjRTlnOFHyoARf3pismmhaSGgeYa/view?usp=sharing

**Comment by jgespino** [comment]
@leoll2 Could you also share this model in ONNX format and the model optimizer command used? Feel free to send it privately via email if needed.

**Comment by jgespino** [comment]
Hi @leoll2 

Please let me know if we can proceed to close this issue. As I mentioned via email, using --scale 255 improved the results of Myriad when comparing to CPU.

Regards,
Jesus

**Comment by leoll2** [comment]
Thanks for the support.
As a last note, I'd like to know the reason behind the issue, i.e. why --scaled works better. Is it a hardware bug, or supposed to behave like this by design? In any case, it may be worth mentioning it somewhere in the documentation, just in case other users have the same problem.
Feel free to close the issue, possibly commenting that --scaled did the trick.
Leonardo

________________________________
Da: l.lai@santannapisa.it <l.lai@santannapisa.it> per conto di Jesus Espinoza <notifications@github.com>
Inviato: lunedì 9 novembre 2020 19:44
A: leonardo.lai@live.com <leonardo.lai@live.com>
Oggetto: Re: [openvinotoolkit/openvino] Huge loss of precision on VPU with HW optimizations enabled (#1822)


Hi @leoll2<https://github.com/leoll2>

Please let me know if we can proceed to close this issue. As I mentioned via email, using --scale 255 improved the results of Myriad when comparing to CPU.

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @leoll2 

Thank you for confirming, we will need to update our documentation to reflect this. The issue happens because there is a half precision overflow on MatMul layer for the MYRIAD plugin. Adding `--scale` will have the data values and weights analyzed by the MYRIAD plugin correctly and there will be no overflow.

Regards,
Jesus

**Comment by sonebu** [comment]
@jgespino adding a `--scale 255` argument to the model optimizer only divides the values at the network input by 255 right?

This doesn't seem like a generalizable solution since intermediate activations in a given network might just creep out to the "overflowing range" again due to large weights or explicit re-normalization. For instance, I just tested public instance segmentation models in the open model zoo: 

1) with the model optimizer flags `--scale_values=[...]` stated in the default .yml files

2) by replacing `--scale_values=[...]` with `--scale 255` (to test if there's something "magical" about `--scale 255`)

in both cases there were significant differences in the model outputs from the MYRIAD and those from the CPU, just like @leoll2 s test case, but also scaling the input doesn't help there, different from @leoll2 s case. I later also tried scaling by higher values to make the input dynamic range even smaller, but couldn't get matching MYRIAD and CPU outputs in any way. The reason could be what I said above but the networks are huge so I didn't check explicitly. 

**My question is:** If the problem really is overflow, I guess one could somehow explicitly train a network to consider only the dynamic range that could be represented on MYRIAD accurately to avoid this problem, but what is that range exactly? i.e., what are the max/min (abs) numerical values that one could use accurately on MYRIAD for different layers (let's just consider layers that alter dynamic range like conv, matmul, interpolate, fullyconnected etc.)?

Other issues related to this one, that would benefit from the same info: #1551, #2723, #3690
