### ISSUE TITLE
[Bug]: Yolov8s exported with half=true (FP16) does not play well with GPU plugin

### ISSUE THREAD

**Issue by ramonbroox** [openvinotoolkit/openvino#18273]
##### System information (version)
- OpenVINO Source => pip install
- OpenVINO Version => Version 2023.0
- Operating System / Platform => Ubuntu 20
- Compiler =>  Cmake
- Problem classification: Model Conversion  
- Device use: CPU / GPU 
- Framework: PyTorch 
- Model name: YoloV8s ([ultralytics](https://github.com/ultralytics/ultralytics))

##### Detailed description
Executing a custom trained YoloV8 detection model with 3 classes (tested as working with `yolo detect`) and exported in FP16 mode returns values when executed in CPU plugin, but returns NaN-filled arrays on GPU [[NaN, ... NaN]...]

##### Steps to reproduce
- Train model with ultralytics, based on yolov8s, with three classes.
- Export with `yolo export weights=custom.pt format=openvino half=true`
- Try an inference (I attach a simple python test: [yolotest.zip](https://github.com/openvinotoolkit/openvino/files/11893890/yolotest.zip) that passes a random noise image and prints the results).

On CPU:
``` 
$ python ./yolotest.py best.xml CPU
Input images: shape [1,3,640,640]
Output best.xml:'output0' with shape [1,7,8400]
Compiling model best.xml for CPU
RESULT [[[ 1.4572341e+00  6.8883405e+00  2.3498693e+01 ...  7.3322119e+02
    7.5268481e+02  7.8244189e+02]
  [ 5.3422198e+00 -2.9822931e+00  3.0464600e+01 ...  5.9200012e+02
    5.8285742e+02  5.7926495e+02]
  [ 5.4031997e+00  1.6486977e+01  4.6981220e+01 ...  3.4644403e+02
    3.2137115e+02  3.1780518e+02]
  ...
  [ 3.1445357e-11  5.3953231e-21  8.9808324e-20 ...  0.0000000e+00
    0.0000000e+00  0.0000000e+00]
  [ 9.9930331e-10  2.2834070e-22  0.0000000e+00 ...  0.0000000e+00
    0.0000000e+00  0.0000000e+00]
  [ 1.6812189e-01  1.5120466e-14  7.4510307e-34 ...  0.0000000e+00
    0.0000000e+00  0.0000000e+00]]]
```
On GPU:
``` 
$ python ./yolotest.py best.xml GPU
Input images: shape [1,3,640,640]
Output best.xml:'output0' with shape [1,7,8400]
Compiling model best.xml for GPU
RESULT [[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]]
``` 
- You can also test with the default trained yolov8s model. The results are very different between CPU and GPU. See the bunch of zeros at the bottom:

``` 
python yolotest.py yolov8s.xml CPU
Input images: shape [1,3,640,640]
Output yolov8s.xml:'output0' with shape [1,84,8400]
Compiling model yolov8s.xml for CPU
RESULT [[[1.1924194e+01 1.1956043e+01 1.8065708e+01 ... 5.6425232e+02
   6.0448352e+02 6.1249878e+02]
  [1.3750745e+01 1.4097794e+01 1.3824223e+01 ... 4.5740588e+02
   4.6275421e+02 6.1729016e+02]
  [1.6149372e+01 1.6088348e+01 3.5853279e+01 ... 3.2791748e+01
   2.9346741e+01 3.1221985e+01]
  ...
  [1.1434342e-13 4.3745527e-21 1.2634910e-24 ... 1.4978953e-14
   5.7135896e-15 2.3594358e-09]
  [1.1803515e-10 4.2589304e-12 3.9103560e-15 ... 2.7885624e-11
   1.7168598e-11 8.2127141e-09]
  [8.6693361e-11 3.7340471e-17 2.8494361e-19 ... 5.7641908e-12
   1.7851863e-12 1.8116215e-09]]]

$ python yolotest.py yolov8s.xml GPU
Input images: shape [1,3,640,640]
Output yolov8s.xml:'output0' with shape [1,84,8400]
Compiling model yolov8s.xml for GPU
RESULT [[[  2.4941406  11.984375   15.2265625 ... 576.        600.
   609.       ]
  [ 14.1484375  13.9921875  12.6640625 ... 453.75      465.
   508.       ]
  [  3.0273438  16.03125    26.234375  ...  54.5        39.5
    40.       ]
  ...
  [  0.          0.          0.        ...   0.          0.
     0.       ]
  [  0.          0.          0.        ...   0.          0.
     0.       ]
  [  0.          0.          0.        ...   0.          0.
     0.       ]]]

``` 
##### Issue submission checklist

 - [X] I report the issue, it's not a question
 - [X] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
 - [X] There is reproducer code and related data files: images, videos, models, etc.

**Comment by ramonbroox** [comment]
Just in case, converting the .onnx model using model optimizer (`mo --input_model best.onnx --compress_to_fp16`) gives the same behaviour.

**Comment by ramonbroox** [comment]
Wait a second, maybe I forgot to `--scale 255` the input... :sweat_smile:

**Comment by Iffa-Meah** [comment]
@ramonbroox if possible could you share your custom YOLOv8 model (original and IR files)?

Note that, currently, **dynamic shape** support for **GPU** is a preview feature and has the following **limitations**:

- It mainly supports NLP models (Natural Language Processing). Not all operations and optimization passes support dynamic shapes. As a result, a given model may crash or experience significant performance drops.
- Due to the dominant runtime overhead on the host device, dynamic shapes may perform worse than static shapes on a discrete GPU.
- Dynamic rank is not supported.

Detailed documentation is [here](https://docs.openvino.ai/2023.0/openvino_docs_OV_UG_supported_plugins_GPU.html)

**Comment by ramonbroox** [comment]
@Iffa-Meah as far as I can tell we use no dynamic shapes.  I've sent the models to you.

**Comment by Iffa-Meah** [comment]
@ramonbroox I received it & did a quick check on your model using official OpenVINO inferencing (benchmark_app),  

ONNX with GPU
<img width="553" alt="onnx" src="https://github.com/openvinotoolkit/openvino/assets/79643476/1081da11-0870-44c9-b1d2-b81ad3860639">


IR with GPU
<img width="527" alt="IRgpu" src="https://github.com/openvinotoolkit/openvino/assets/79643476/b318ec5b-679f-48ac-9e1c-7a0285aaed82">

I believe this issue is related to your custom inferencing code where you need to cater your codes to further assimilate your use case with OpenVINO GPU Plugin.

Perhaps [this](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb) would help you to further develop your inferencing code.

**Comment by Iffa-Meah** [comment]
@ramonbroox yes, I do understand that your model is not working on GPU. **The test was made on GPU** to ensure your model is able to be inferred on OpenVINO with GPU plugin not to indicate the performance.

I tried inferring using OpenVINO benchmark_app because this app is an official inferencing code which **NOT likely to have issues.**


Thanks for sharing your GPU information. Previously I'm using Intel UHD Graphics.
Now I tried inferring your model specific on **Intel Iris GPU** and found issues (inferred on benchmark_app):

<img width="639" alt="IntelIrisGPUfailedInfer" src="https://github.com/openvinotoolkit/openvino/assets/79643476/62ecb16b-af81-45a5-b2e2-44e8a32fa79c">


This has potential to be an issue with the Ultralytics library (YOLOv8 model) since it has a known "nan" encounter due to compatibility with a couple of GPU types. Source: [Ultralytic GitHub issue](https://github.com/ultralytics/ultralytics/issues/1148)

We'll further investigate this and get back to you.

**Comment by hbalasu1** [comment]
Ref 114795

**Comment by ramonbroox** [comment]
@hbalasu1 Do you mean the openvino gpu plugin? Or the Intel GPU driver?
I've tried with current openvino master and still exhibits the same problem.

**Comment by avitial** [comment]
Cannot reproduce with OpenVINO v2023.2 and graphics driver version 23.05.25593.11. Closing this issue, feel free to reopen to ask any questions related to this topic.

```
$ clinfo -l
Platform #0: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) Iris(R) Xe Graphics

$ export gfx_version=$(dpkg-query --showformat='${Version}' --show intel-opencl-icd)
echo $gfx_version
23.05.25593.11

$ benchmark_app -m best.onnx -d GPU -niter 10
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2023.2.0-13089-cfd42bd2cb0-HEAD
[ INFO ]
[ INFO ] Device info:
[ INFO ] GPU
[ INFO ] Build ................................. 2023.2.0-13089-cfd42bd2cb0-HEAD
[ INFO ]
[ INFO ]
...
...
[ INFO ] First inference took 34.17 ms
[Step 11/11] Dumping statistics report
[ INFO ] Execution Devices:['OCL_GPU.0']
[ INFO ] Count:            12 iterations
[ INFO ] Duration:         333.16 ms
[ INFO ] Latency:
[ INFO ]    Median:        109.81 ms
[ INFO ]    Average:       97.18 ms
[ INFO ]    Min:           37.97 ms
[ INFO ]    Max:           111.93 ms
[ INFO ] Throughput:   36.02 FPS
```
