### ISSUE TITLE
[Performance]: Dynamic shapes in snippets

### ISSUE THREAD

**Issue by hezhiqian01** [openvinotoolkit/openvino#19982]
### OpenVINO Version

Master Branch

### Operating System

Red Hat Enterprise Linux 8

### Device used for inference

CPU

### OpenVINO installation

PyPi

### Programming Language

Python

### Hardware Architecture

x86 (64 bits)

### Model used

Bert

### Model quantization

No

### Performance issue description

Hello team,

I found that ov::snippets::pass::TokenizeMHASnippets cannot allow a dynamic shape of the matmul0 input when I use openvino to deploy a bert text classification model. If so, I must pad every input sentence to the max length which could increase a lot of calculation and cause the performance down. Please tell me if my understanding is wrong or if the snippets design is flawed.   

### Issue submission checklist

- [X] I'm reporting a performance issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by vurusovs** [comment]
@a-sidorova @dmitry-gorokhov please, take a look

**Comment by a-sidorova** [comment]
Hi @hezhiqian01,

Thank you for your interest in OpenVINO and Snippets!

The MHA (Multi-Head-Attention) pattern with dynamic shapes is executed as separate operations performed by the plugin because, unfortunately, Snippets don't yet support dynamic shapes for MHA pattern. But at the moment, we are working on the dynamism support for Snippets to allow the MHA pattern to be executed through Snippets as one whole node.

Thus, if you want to use Snippets for dynamic models, you have to use static model and to pad every input sequence to the max length still, you're right. But we hope that we will be able to infer dynamic models that contain MHA pattern using Snippets in the near future.

However, could you tell me please why you have to use static model for dynamic use-cases to allow Snippets to tokenize MHA pattern? To avoid extra paddings of input sequences you can use dynamic models that are inferred by CPU Plugin with disabled Snippets.

Also could you please share the model with us if possible? Or just the screenshot of the pattern with shapes to add your case to our scope of dynamic patterns for analysis.

cc @IvanNovoselov

**Comment by hezhiqian01** [comment]
> Hi @hezhiqian01,
> 
> Thank you for your interest in OpenVINO and Snippets!
> 
> The MHA (Multi-Head-Attention) pattern with dynamic shapes is executed as separate operations performed by the plugin because, unfortunately, Snippets don't yet support dynamic shapes for MHA pattern. But at the moment, we are working on the dynamism support for Snippets to allow the MHA pattern to be executed through Snippets as one whole node.
> 
> Thus, if you want to use Snippets for dynamic models, you have to use static model and to pad every input sequence to the max length still, you're right. But we hope that we will be able to infer dynamic models that contain MHA pattern using Snippets in the near future.
> 
> However, could you tell me please why you have to use static model for dynamic use-cases to allow Snippets to tokenize MHA pattern? To avoid extra paddings of input sequences you can use dynamic models that are inferred by CPU Plugin with disabled Snippets.
> 
> Also could you please share the model with us if possible? Or just the screenshot of the pattern with shapes to add your case to our scope of dynamic patterns for analysis.
> 
> cc @IvanNovoselov

Hi @IvanNovoselov,

Thanks a lot for your reply. 

As you mentioned the dynamic shape is not currently  supported for snippets, so I will disable snippets when I infer a dynamic model. That's clear.

The model I deployed is just a Bert text classification model which fine tuned on our datasets. The input shape is (1,384) which 384 is the max length of the input sequence. I will reshape the model to (1, ?)  as a dynamic input and disable snippets following your suggestion. Thank you again.
