### ISSUE TITLE
[Good First Issue]: Enable parallel execution of TensorFlow Lite Layer python tests

### ISSUE THREAD

**Issue by mryzhov** [openvinotoolkit/openvino#20920]
### Context

Current CI (https://github.com/openvinotoolkit/openvino/blob/c0381ab08d2fcdc51c621196e935aa02c64a4b50/.github/workflows/linux.yml#L869) runs all the python tests sequentially one by one and it takes too much time.
The idea is to run all those tests in parallel by using pytest-xdist plugin, but tests should be modified for that.
Please find bellow the common tests issues:
- Random inputs generation as parametrization arguments. Solution: all random test arguments should be generated inside of the tests 
- Tests create, use and remove the same artifacts (temporary data, models, etc). Hot fix solution: all test data should be generated in the system temporary directory (TMPDIR) which can be unique for each thread. Long term solution: all test data should be generated in the unique temporary directory or with unique names.

### What needs to be done?

- Modify TensorFlow Lite Layer tests to solve issues described in the Context. Tests are located here - https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/tensorflow_lite_tests
- Enable parallel execution of those test in the CI (https://github.com/openvinotoolkit/openvino/blob/4a0098b26ad6c4cbae97fbe34505fa63c08036eb/.github/workflows/linux.yml#L1080C15-L1080C30)

### Example Pull Requests

https://github.com/openvinotoolkit/openvino/pull/20613

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@mryzhov @akashchi

**Comment by Deepesh0289** [comment]
Hello @mryzhov , I would like to work on this issue. Could you please assign it to me?

**Comment by p-wysocki** [comment]
Hello @Deepesh0289! Thank you for taking a look, please let us know if you have any questions. Just yesterday our CONTRIBUTING.md has been updated [with a technical guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md) - I highly recommend checking it out. :)

**Comment by p-wysocki** [comment]
Hello @Deepesh0289, are you still working on that issue?

I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by Deepesh0289** [comment]
Sorry for the late reply.

Due to some condition I am not able to work upon this issue. Kindly refer
to another one.

**Comment by mlukasze** [comment]
No worries, have a nice day, and thank you for interesting.
Please join us again, any time you can :)

**Comment by Bolt17803** [comment]
Hello @akashchi  @mryzhov , I am interested to work on this issue, please can you assign me this task

**Comment by Bolt17803** [comment]
Hello @akashchi @mryzhov I am getting a weird error in test cases saying " ModuleNotFoundError: No module named 'openvino.tools.mo' ", for the import statement " from openvino.tools.mo.ops import PermuteAttrs " even though I have installed all the dependencies, please can you help with this error

**Comment by p-wysocki** [comment]
Hello @Bolt17803, that's most likely due to a path missing from your environment variable `PYTHONPATH`. The solution to this would be to run `export PYTHONPATH=<OPENVINO_INSTALL_DIR>/python:<OPENVINO_REPO_DIR>/openvino/tools/mo` in your shell.

**Comment by p-wysocki** [comment]
Hi @Bolt17803, are you still working on this task?

**Comment by Bolt17803** [comment]
Hi @p-wysocki , yeah I am still working, I am facing an issue while parallelizing the tests, the error is like this 
<testcase classname="" name="gw1" time="0.000"><error message="collection failure">Different tests were collected between gw0 and gw1.
If I keep no of workers more than 1 I am getting errors like this, pls can you help with it, I have completed the task of random input generation as parametrization arguments for all the test cases

**Comment by mryzhov** [comment]
@Bolt17803 could you share the full error log?

**Comment by Bolt17803** [comment]
hi @mryzhov I have solved the issue of parallelizing tests, they are running but sometimes the processes is getting stopped by a segmentation fault issue, please check the error log here:
"F.FFFF.FF..FFFatal Python error: Segmentation fault

Thread 0x00007f7d4e3fa640 (most recent call first):
  File "/usr/lib/python3.10/ssl.py", line 1371 in do_handshake
  File "/usr/lib/python3.10/ssl.py", line 1100 in _create
  File "/usr/lib/python3.10/ssl.py", line 513 in wrap_socket
  File "/usr/lib/python3.10/http/client.py", line 1455 in connect
.......
.......
.F.FF[gw0] node down: Not properly terminated
F
replacing crashed worker gw0
3 workers [316 items]  INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/xdist/dsession.py", line 123, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/xdist/dsession.py", line 148, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/xdist/dsession.py", line 273, in worker_collectionfinish
INTERNALERROR>     self.sched.schedule()"


here I am sharing the starting and ending info of error, I think it might my hardware issue due to lack of compute power, with less no of tests and workers it is working properly. Please can you tell if this is the situation or anything else
INTERNALERROR>   File "/home/chaitanyasai/.local/lib/python3.10/site-packages/xdist/scheduler/each.py", line 134, in schedule
INTERNALERROR>     pending[:] = range(len(self.node2collection[node]))
INTERNALERROR> KeyError: <WorkerController gw2>

**Comment by mryzhov** [comment]
Yes, it looks like environment issue.
Could you please create the PR with your changes and we will trigger our CI on it?

**Comment by Bolt17803** [comment]
Hi @mryzhov , please check my PR #22478

**Comment by mlukasze** [comment]
awaiting contributor response, further actions based on his decision.

**Comment by Jessielovecodings** [comment]
#WLB
.take

**Comment by p-wysocki** [comment]
Hello @Jessielovecodings, are you still working on that task? Do you need help with anything?

**Comment by tanishka321** [comment]
.take

**Comment by Jessielovecodings** [comment]
.take

**Comment by Jessielovecodings** [comment]
.take

**Comment by mlukasze** [comment]
hey @Jessielovecodings are you still working on this?

**Comment by hub-bla** [comment]
.take
