### ISSUE TITLE
[Good First Issue]: split test_infer_request.py

### ISSUE THREAD

**Issue by akuporos** [openvinotoolkit/openvino#21423]
### Context

[test_infer_request](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_runtime/test_infer_request.py) file is quite big so it's uncomfortable to work with it.
Suggestion: split it to **test_sync_infer_request.py** and **test_async_infer_request.py.**

### What needs to be done?

So test_infer_request.py should be renamed to test_sync_infer_request.py.
Add new file with name **test_async_infer_request**.py to this directory: `openvino/src/bindings/python/tests/test_runtime/`
and move there all tests which contain AsyncInferQueue.

### Example Pull Requests

-

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md#how-to-test-openvino-python-api)

### Contact points

@akuporos 
@jiwaszki
@p-wysocki 

### Ticket

126524

**Comment by sami0i** [comment]
Hello, 
I'm new to open source contributions and would like to work on this issue. Could you please assign it to me?
Thanks in advance.

**Comment by akuporos** [comment]
Hello @sami0i,

Welcome to our GFI program.
Do not hesitate ask questions.

Anastasia

**Comment by sami0i** [comment]
Thanks for assigning this to me. I'll reach out if I have any questions.

**Comment by Bhaskar365** [comment]
Hello akuporos,
I'm new to open source contributions and would like to work on this python issue. Could I try to work on this if you have no problem? Waiting for your response.

**Comment by p-wysocki** [comment]
I apologize @sami0i, we have not yet had such a situation. Usually once an issue is assigned to a person, other people do not open PRs for it. I can only recommend picking up another Good First Issue, we'll be happy to provide all help. We are really sorry for that situation and I hope that it will not discourage you from contributing to OpenVINO. :(

@Bhaskar365 thank you for your contribution. Please ask for assignment first in the future in order to avoid confusing situations like this one.

From now on we'll be only accepting Pull Requests from people assigned to the issue.

**Comment by sami0i** [comment]
Thanks for understanding @p-wysocki. I appreciate your response. I'll look into other issues and continue contributing to OpenVINO. No discouragement at all! :)
