### ISSUE TITLE
[Build]: I want to convert the model but I didn't find how to install ovc

### ISSUE THREAD

**Issue by 994028510** [openvinotoolkit/openvino#21598]
### OpenVINO Version

2023.2

### Operating System

Windows System

### Hardware Architecture

x86 (64 bits)

### Build issue description

How to install ovc?  And is there a difference in performance between using the ONNX model directly and converting it to IR using OVC?

### Issue submission checklist

- [ ] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.

**Comment by ilya-lavrenov** [comment]
Hi @994028510 
OVC is a python tool, so an easiest way to install it is:
```bash
python3 -m pip install openvino
```
And then use `ovc --help`
Other packages where OVC is available:
- https://docs.openvino.ai/2023.2/openvino_docs_install_guides_installing_openvino_from_archive_linux.html
- https://docs.openvino.ai/2023.2/openvino_docs_install_guides_installing_openvino_conda.html

> And is there a difference in performance between using the ONNX model directly and converting it to IR using OVC?

Performance of inference is the same, because internally both OVC and `read_model(onnx)` converts a model to IR representation. The difference is in model loading time: with OVC model is already converted and takes less time to load, while ONNX model needs to be converted to IR on-the-fly and affects first inference latency.

**Comment by 994028510** [comment]
@ilya-lavrenov Thank you. I installed the archive on Windows, but I skipped step 4. It seems that OVC relies on the Python environment and this step is necessary？

**Comment by ilya-lavrenov** [comment]
> It seems that OVC relies on the Python environment and this step is necessary？

Right, `OVC` is a python tool.

**Comment by 994028510** [comment]
If I want to convert the model to fp16, how can I use the C++API to implement it？

**Comment by ilya-lavrenov** [comment]
> If I want to convert the model to fp16, how can I use the C++API to implement it？

Why do you need it?
- If you want to perform inference in FP16, then only GPU supports it and it's a default GPU behavior
- If you want to read ONNX model in C++ and then save this model to FP16 on disk, than you can use `ov::save_model` function which automatically compresses a model to FP16.

**Comment by ilya-lavrenov** [comment]
> > > If I want to convert the model to fp16, how can I use the C++API to implement it？
> > 
> > 
> > Why do you need it?
> > ```
> > * If you want to perform inference in FP16, then only GPU supports it and it's a default GPU behavior
> > 
> > * If you want to read ONNX model in C++ and then save this model to FP16 on disk, than you can use `ov::save_model` function which automatically compresses a model to FP16.
> > ```
> 
> I thought the CPU could also perform fp16 inference, so I wanted to give it a try。。。thanks！

Only ARM CPU supports FP16 inference. 
Intel CPU can perform FP32, int8 (quantized models) or BF16 ([Sapphire Rapids](https://en.wikipedia.org/wiki/Sapphire_Rapids))
