### ISSUE TITLE
[Bug]: Loading custom operations from Python fails

### ISSUE THREAD

**Issue by basioli-k** [openvinotoolkit/openvino#21720]
### OpenVINO Version

2023.2

### Operating System

Ubuntu 20.04 (LTS)

### Device used for inference

GPU

### Framework

ONNX

### Issue description

I created my custom operation library by following https://blog.openvino.ai/blog-posts/custom-pytorch-operations.

When I attempt to load the library via the `C++` API it's successful.

```
ov::Core core;
core.add_extension("user_ie_extensions/build/libuser_ov_extensions.so");
```

When I try to load the library via the `python` API it fails with:
```
>>> ov.Core().add_extension("user_ie_extensions/build/libuser_ov_extensions.so")
```

When I revert back to OpenVINO `2023.0` and build the library the Python API works and successfully loads the extension.

### Step-by-step reproduction

1. Clone the blog repo
2. Build an operation (this is the command I used)
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_FAST_TOKENIZERS=ON -DCUSTOM_OPERATIONS="complex_mul" && cmake --build . --parallel 4
```
3. Create a `Core` object in `Python` and attempt to load the plugin.

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Exception from src/inference/src/core.cpp:179:
Cannot add extension. Cannot find entry point to the extension library. This error happened: [ GENERAL_ERROR ] Cannot load library 'user_ie_extensions/build/libuser_ov_extensions.so': user_ie_extensions/build/libuser_ov_extensions.so: undefined symbol: _ZN2ov3Any4Base9to_stringB5cxx11Ev
```

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by ilya-lavrenov** [comment]
Hi @basioli-k
Could you please try latest OV? 
The nightly build can be downloaded using this menu https://docs.openvino.ai/2023.2/openvino_docs_install_guides_overview.html?VERSION=NIGHTLY&OP_SYSTEM=LINUX&DISTRIBUTION=ARCHIVE

**Comment by ilya-lavrenov** [comment]
> Is there a way to get the nightly version with the mentioned package managers

For nightly releases we definitely don't have Conan, because it's impossible to release packages to CCI every day. 

> _ZN2ov3Any4Base9to_stringB5cxx11Ev

This is a problem of incompatibility of [manylinux2014_x86_64](https://github.com/pypa/manylinux), which is CentOS 7 in fact, with systems with newer compiler like Ubuntu 20.04 / 22.04. They use different ABI https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

If you use OpenVINO Python API from official PyPi channel (which is compiled on `manylinux2014_x86_64`), you have to build extension on the same platform or use different value for `_GLIBCXX_USE_CXX11_ABI` macro.

**Comment by basioli-k** [comment]
Makes sense, thank your for your help.
