### ISSUE TITLE
[Bug]: export_model api of CompiledModel throw error with  RuntimeError: [ NOT_IMPLEMENTED ]

### ISSUE THREAD

**Issue by AIgiraffe** [openvinotoolkit/openvino#21918]
### OpenVINO Version

openvino-dev==2022.3.1

### Operating System

Windows System

### Device used for inference

CPU

### Framework

ONNX

### Issue description

when i use the code as follows,the api of export_model of CompiledModel throw the erroe with RuntimeError: [ NOT_IMPLEMENTED ], how can i fix this?

import openvino.runtime as ov

model = ov.Core().read_model(model_path)
compile_model = ov.core().compile_model(model)
model_stream = compile_model.export()

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by wangleis** [comment]
@AIgiraffe When you run `compile_model = ov.core().compile_model(model)` without device name, OpenVINO will use `AUTO` as default device. `AUTO` device does not support model export because `AUTO` device may change execution device internally. So your test will get this error message.

Since you want to use the CPU for inference in this test, please change command to `compile_model = ov.core().compile_model(model, "CPU")` and retry your test.

**Comment by ilya-lavrenov** [comment]
@AIgiraffe it's also suggested to use [model caching](https://docs.openvino.ai/2023.2/openvino_docs_OV_UG_Model_caching_overview.html) feature. It's available for AUTO and other devices and you don't need to explicitly call `export_model` / `import_model`, because `Core` will perform all this handling internally

**Comment by peterchen-intel** [comment]
> @AIgiraffe it's also suggested to use [model caching](https://docs.openvino.ai/2023.2/openvino_docs_OV_UG_Model_caching_overview.html) feature. It's available for AUTO and other devices and you don't need to explicitly call `export_model` / `import_model`, because `Core` will perform all this handling internally

@AIgiraffe Can this comment fulfil your scenario? If not, can you please provide more details about your scenario?

**Comment by peterchen-intel** [comment]
Closed this issue since no new repones from submitter for a long time.
