### ISSUE TITLE
[Bug]: got an unexpected keyword argument 'shared_memory'

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#21979]
### OpenVINO Version

openvino-nightly

### Operating System

Ubuntu 18.04 (LTS)

### Device used for inference

CPU

### Framework

None

### Issue description

The following code indicates that the parameter seems to be missing in the newer version of OpenVINO. However, when I switched back to version 2023.2 of OpenVINO, it worked well. I'm wondering if some things were deprecated during the update without proper documentation. Many downstream repositories are still using this API.
```
self.request = core.compile_model(self.model, self.device, self.ov_config)
outputs = self.request(inputs, shared_memory=True)
```

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by sanbuphy** [comment]
see also  https://github.com/openvinotoolkit/openvino_notebooks/issues/1592

**Comment by jiwaszki** [comment]
Hi @sanbuphy , good to hear from you again! (I was hoping to have a different topic to discuss though...:))

There is an easy replacement of `shared_memory`, simply replace it with `share_inputs` and it will work the same way. The naming convention was changed due to introducing `share_outputs`. In this way there is no misunderstanding about what `shared_memory` is doing -- "is it only inputs or outputs or both?".

`shared_memory` was finally deprecated in current master (preparing to 2024.0). It was already announced (here a code from 2023.2 release):
https://github.com/openvinotoolkit/openvino/blob/2023.2.0/src/bindings/python/src/openvino/runtime/ie_api.py#L27-L34

It was introduced around 6 moths ago with: https://github.com/openvinotoolkit/openvino/commit/59052d846e421608dca8ab0871cade46d6cce0e0

I hope this gives you a full answer, let me know if I can close this issue. Cheers!

**Comment by sanbuphy** [comment]
> Hi @sanbuphy , good to hear from you again! (I was hoping to have a different topic to discuss though...:))
> 
> There is an easy replacement of `shared_memory`, simply replace it with `share_inputs` and it will work the same way. The naming convention was changed due to introducing `share_outputs`. In this way there is no misunderstanding about what `shared_memory` is doing -- "is it only inputs or outputs or both?".
> 
> `shared_memory` was finally deprecated in current master (preparing to 2024.0). It was already announced (here a code from 2023.2 release): https://github.com/openvinotoolkit/openvino/blob/2023.2.0/src/bindings/python/src/openvino/runtime/ie_api.py#L27-L34
> 
> It was introduced around 6 moths ago with: [59052d8](https://github.com/openvinotoolkit/openvino/commit/59052d846e421608dca8ab0871cade46d6cce0e0)
> 
> I hope this gives you a full answer, let me know if I can close this issue. Cheers!

Long time no see! Thank you for your detailed response as always. I understand completely. So, for some issues with downstream code, can I directly submit a pull request to make the changes?

**Comment by jiwaszki** [comment]
@sanbuphy Of course! Please make sure to add me to reviewers/ping me in the comments. I will be more than happy to leave approvals on them.
