### ISSUE TITLE
[Bug]: compile_model is much slower on GPU in process with system permissions

### ISSUE THREAD

**Issue by zhaoyongjun1113** [openvinotoolkit/openvino#22113]
### OpenVINO Version

tag 2023.0.2

### Operating System

Ubuntu 18.04 (LTS)

### Device used for inference

CPU

### Framework

None

### Model used

self model

### Issue description

I tried running the same process in both the user permission process and the system permission process_ The model function has a significant difference between the two. The user permission process takes less than 500ms, while the system permission process takes more than 7000ms. I have ruled out other different situations。Below is my code.

        string device = "GPU";
        ov::Core ie;
        ie.set_property(ov::cache_dir("D:/back_test/cl_cache/"));
        ov::CompiledModel compiled_model;
	try {
		ov::AnyMap config; 
		config[ov::hint::model_priority.name()] = ov::hint::Priority::LOW;
                std::shared_ptr<ov::Model> model=ie.read_model(xml_path);
		compiled_model = ie.compile_model(model, device, config);
	}
	catch (exception& e)
	{
                std::cout << e.what() << std::endl;
		return 0;
	}

### Step-by-step reproduction

run the code with system permission process,like in service,it will much slower than in user process

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by wangleis** [comment]
@zhaoyongjun1113 May I know if two process is running in parallel or one by one? Could issue be reproduced after remove `ie.set_property(ov::cache_dir("D:/back_test/cl_cache/"));`?

**Comment by wangleis** [comment]
@zhaoyongjun1113 When `ov::cache_dir` is set, model caching function is enabled. Then the first time of compile_model() will take a long time to compile model from input and generate model cache to cache_dir folder. And the second time of compile_model() will take a short time to read model from model cache. Please learn more about model caching in https://docs.openvino.ai/2023.2/openvino_docs_OV_UG_Model_caching_overview.html. 

So I guess what you are reporting is the expected behavior:

- In initial case, the system permission process run first and take long time to compile model from input. And the user permission process run later and take short time to read model from model cache. 
- After you disable model caching in second comment, both the the system permission process and the user permission process take a long time to compile model from input.

**Comment by zhaoyongjun1113** [comment]
I called compile_model for the first time using a user mode process.The model will also be fast. Both the system permission process and the user permission process call compile_model for the first time, without generating cache files, the difference between the two is significant. The system process takes over 7000ms, while the user permission process takes less than 500ms。I suggest that you try this situation yourself by adding system permission processes to the service to execute them

**Comment by wangleis** [comment]
@zhaoyongjun1113 Could you share the time stamp for `compiled_model = ie.compile_model(model, device, config);` only in two situation?

Also could you share the application source code and service you tested?

**Comment by avitial** [comment]
@zhaoyongjun1113 do you have an update for us? If help is still needed, please provide the info as requested by Wanglei.

**Comment by avitial** [comment]
Closing this as it can't be reproduced due to insufficient info, I hope previous responses were sufficient to help you proceed or resolve the issue. Feel free to reopen and ask additional questions related to this topic if issue persists.
