### ISSUE TITLE
LoadNetwork crashes on Android while loading sample's  face detection xml and bin 

### ISSUE THREAD

**Issue by avaish1** [openvinotoolkit/openvino#231]
Hi 
We have recompiled dldt 2019-R1.1 for android P and trying to enable face detection via JNI layer and CMAKE  in  android app via MKLDNN plugin  . The reference for  face detection app  is as mentioned in https://github.com/opencv/open_model_zoo/tree/master/demos/interactive_face_detection_demo  and model tried is face-detection-adas-0001.xml.
 
As we try to upload face-detection-adas-0001.xml from openvino_models, it results in following error all the time
08-21 16:42:23.133 11235 11253 E libc++abi: terminating with uncaught exception of type InferenceEngine::details::InferenceEngineException: Unsupported primitive of type: PriorBox name: fc7_mbox_priorbox
08-21 16:42:23.133 11235 11253 E libc++abi: vendor/intel/external/project-celadon/nn-hal/intel_nn_hal/dl/../../../dldt/inference-engine/src/mkldnn_plugin/mkldnn_node.cpp:167
08-21 16:42:23.133 11235 11253 E libc++abi: ../../../../src/main/cpp/include/inference_engine\details/ie_exception_conversion.hpp:71

As googled for this issue , compiled libcpu_extension.so  on android and included here (attached is the adb output) , but error  still remains. 

As this interactive_Face_demo works on Linux flawlessly , we are trying to simulate the same on Android . 

could someone please help here? Thankyou 
<img width="288" alt="adb_libs" src="http

s://user-images.githubusercontent.com/25952023/63449476-e08f4880-c45d-11e9-89c2-89eaa2bd77d7.PNG"

Model file is also attached.

**Comment by shubha-ramani** [comment]
Dear @avaish1 
Without stepping through Inference Engine code built as Debug there is no way I can determine what went wrong. JNI definitely adds a complication.  I'm glad that you're linked against  libcpu_extension.so because that is indeed the first thing I thought about.

My advice to you is first
1) use 2019R2. 2019R1.1 is quite old and so you should always be on the latest release because many bug fixes and improvements have been made.
2) Follow this [README](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md) to build Inference Engine in Debug and step through your code. If you step through your code you will narrow down the problem.
3) The error seems to say that Inference Engine cannot find this extension right here:
[https://github.com/opencv/dldt/blob/2019/inference-engine/src/extension/ext_priorbox.cpp](https://github.com/opencv/dldt/blob/2019/inference-engine/src/extension/ext_priorbox.cpp). So maybe you need to JNI that part too.
4) If all else fails try with a super simple example first, something like [hello_classification](https://github.com/opencv/dldt/tree/2019/inference-engine/samples/hello_classification)

Hope it helps,

Thanks,

Shubha

**Comment by avaish1** [comment]
Yeh Shubha, could load alexnet , would try other steps now..
2019-08-22 15:23:48.490 4346-4365/? D/FACE_DEMO: layer count of networks are 22
2019-08-22 15:23:48.490 4346-4365/? D/FACE_DEMO: name of networks is AlexNet
2019-08-22 15:23:48.490 4346-4365/? D/FACE_DEMO: batchsize of  networks is 1
2019-08-22 15:23:48.490 4346-4365/? D/FACE_DEMO: size of  networks is 22

**Comment by avaish1** [comment]
adding this line helped resolved this unknown primitive issue .. 
plugin.AddExtension(std::make_shared<Extensions::Cpu::CpuExtensions>());

But encountered another one as below .. though xml shows activation as relu, but here it says convolution.. 

08-22 14:51:31.233  9969  9969 F DEBUG   : Abort message: 'terminating with uncaught exception of type InferenceEngine::details::InferenceEngineException: Node conv2_1/dw has unsupported activation primitive: Convolution : Convolution

**Comment by shubha-ramani** [comment]
@avaish1 
As already discussed, please try again on OpenVino 2019R2. Your issue may already be fixed. Your error is strange since Convolution is not an activation primitive within OpenVIno per the [Supported Devices Doc](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html)

Thanks,

Shubha

**Comment by AnastasiaKazantaeva** [comment]
It seems that issue nor actual anymore closing it. Feel free to open a new issue in case of some problems/issues
