### ISSUE TITLE
[Good First Issue][Bug][Core]: set_rt_info() makes IR not readable

### ISSUE THREAD

**Issue by mlukasze** [openvinotoolkit/openvino#23192]
### Context

```
from openvino.runtime import Core, serialize
import os


def main():
    core = Core()
    model = core.read_model('/home/wov/.cache/omz/intel/face-detection-0200/FP16-INT8/face-detection-0200.xml')
    model.set_rt_info('62d7a6a6587d65534beca376', ["model_parameters", "labels", "all_labels", "62d7a6a6587d65534beca376", "id"])
    out_path = os.path.dirname(__file__) + '/model.xml'
    serialize(model, out_path)
    model = core.read_model(out_path)


if __name__ == '__main__':
    main()
```
fails with
```
Traceback (most recent call last):
  File "r/Segmentation Models/serialize.py", line 15, in <module>
    main()
  File "r/Segmentation Models/serialize.py", line 11, in main
    model = core.read_model(out_path)
RuntimeError: Check 'false' failed at src/frontends/common/src/frontend.cpp:47:
Loading input model
Could not determine tag type at offset 511043
```
It must be something about `62d7a6a6587d65534beca376`. 

### What needs to be done?

problem in described scenario should be fixed

### Example Pull Requests

[PR#15268](https://github.com/openvinotoolkit/openvino/pull/15268)

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@olpipi @Wovchena 

### Ticket

CVS-101287

**Comment by Karroat** [comment]
I'm new to open source and this is my first time contributing, so please bear with me if there are any mistakes in my solution. I've tried my best to address the issue, but I'm open to feedback and eager to learn. 

The error message you're encountering indicates that the OpenVINO Runtime could not determine the tag type in the model file. This usually happens when the model file is corrupted or incomplete.

In your code,
1) First, serializing the model to a file using the serialize function. 
2) Then, you're trying to read the serialized model using the read_model function.
3) However, the serialize function does not save the model in the OpenVINO Intermediate Representation (IR) format.
 Instead, it saves the model in the ONNX format.
 
To resolve this issue, you can either:
1) Save the model in the OpenVINO IR format using the serialize function.
           ` serialize(model, out_path, "IR")`

2) Or, you can directly read the model in the OpenVINO IR format using the read_model function.
           `model.serialize(out_path)`

i hope this is correct !_ _! @olpipi  @Wovchena .

**Comment by Karroat** [comment]
.take

**Comment by Wovchena** [comment]
> To resolve this issue, you can either:
> 1) Save the model in the OpenVINO IR format using the serialize function.
           ` serialize(model, out_path, "IR")`

The reproducer already calls `serialize(model, out_path)`

**Comment by LalitSP** [comment]
.take

**Comment by LalitSP** [comment]
Currently working on set_rt_info() function, which makes IR not readable #23192 issue. Can you please clarify the expected behavior of the code and the main cause of the error?

**Comment by p-wysocki** [comment]
cc @olpipi @Wovchena

**Comment by olpipi** [comment]
Hi  @LalitSP sorry for the late reply.

I prepared a lighter reproducer for you. It helps you to understand what set_rt_info does.
There is no need to use any real model. This elementary one is enough:
```
<?xml version="1.0"?>
<net name="test" version="11">
    <layers>
        <layer id="0" name="input" type="Parameter" version="opset1">
            <data shape="1" element_type="f32" />
            <output>
                <port id="0" precision="FP32" names="input">
                    <dim>1</dim>
                </port>
            </output>
        </layer>
        <layer id="1" name="output" type="Result" version="opset1">
            <input>
                <port id="0" precision="FP32" names="output">
                    <dim>1</dim>
                </port>
            </input>
        </layer>
    </layers>
    <edges>
        <edge from-layer="0" from-port="0" to-layer="1" to-port="0" />
    </edges>
</net>
```

My test python code:
```
from openvino.runtime import Core, serialize
import os


def main():
    core = Core()
    model = core.read_model('<path to model>/test_model.xml')
    model.set_rt_info('value', ["model_parameters", "labels", "111", "id"])
    out_path = '<path where to save>/out_model.xml'
    print(out_path)
    serialize(model, out_path)
    model = core.read_model(out_path)


if __name__ == '__main__':
    main()
```
The issue is in "111" tag. OpenVINO throw an exception when we have tag which starts with digit. So expected behavior is to execute code above without exception.
You need to debug C++ code to find a root cause.
I can help you tomorrow to prepare a C++ sample and find where is the root cause.

**Comment by LalitSP** [comment]
Thanks, @olpipi for your assistance with the issue. It's a great idea to work with a C++ sample which will be a great help in understanding and investigating any bugs. and I'm confident that we'll be able to move forward with a successful solution.

**Comment by olpipi** [comment]
I cannot reproduce the issue with C++ sample.
Let me try some more experiments

**Comment by LalitSP** [comment]
how if we try this insted:
model.set_rt_info(["62d7a6a6587d65534beca376"], ["model_parameters", "labels", "all_labels", "62d7a6a6587d65534beca376", "id"])
I hope this might help
@olpipi

**Comment by olpipi** [comment]
Hi @LalitSP 
I finally debugged this issue. And found the root cause. OpenVINO cannot serialize and deserialize names in rt_info, which start with digit. I also found we had a PR one year ago which add such feature. But this PR was not finalized. You can try to apply appropriate changed on top of master branch and check whether it help. If yes, you can create PR and try to finalize it.
https://github.com/openvinotoolkit/openvino/pull/15268

**Comment by hub-bla** [comment]
Hi @olpipi, is it still the issue? I tried to reproduce the error using 
> 
> ```
> <?xml version="1.0"?>
> <net name="test" version="11">
>     <layers>
>         <layer id="0" name="input" type="Parameter" version="opset1">
>             <data shape="1" element_type="f32" />
>             <output>
>                 <port id="0" precision="FP32" names="input">
>                     <dim>1</dim>
>                 </port>
>             </output>
>         </layer>
>         <layer id="1" name="output" type="Result" version="opset1">
>             <input>
>                 <port id="0" precision="FP32" names="output">
>                     <dim>1</dim>
>                 </port>
>             </input>
>         </layer>
>     </layers>
>     <edges>
>         <edge from-layer="0" from-port="0" to-layer="1" to-port="0" />
>     </edges>
> </net>
> ```
> 
> My test python code:
> 
> ```
> from openvino.runtime import Core, serialize
> import os
> 
> 
> def main():
>     core = Core()
>     model = core.read_model('<path to model>/test_model.xml')
>     model.set_rt_info('value', ["model_parameters", "labels", "111", "id"])
>     out_path = '<path where to save>/out_model.xml'
>     serialize(model, out_path)
>     model = core.read_model(out_path)
> 
> 
> if __name__ == '__main__':
>     main()
> ```


but it seems to work correctly.

**Comment by Wovchena** [comment]
You are correct. Fixed in https://github.com/openvinotoolkit/openvino/pull/25159
