### ISSUE TITLE
[Feature] Add support for converting ONNX to C code?

### ISSUE THREAD

**Issue by mhamdan91** [openvinotoolkit/openvino#2386]
Is it possible to add support convert the ONNX files to C code instead of IR?

**Comment by jgespino** [comment]
Hi @mhamdan91 Could you please provide some additional insight as to why you need this?

OpenVINO toolkit uses the model optimizer to convert the model to IR format to be used by the Inference Engine? Are you running into any issues with the model optimizer or inference engine?

Regards,
Jesus

**Comment by mhamdan91** [comment]
Hi @jgespino , 
I would like to deploy the C code without the need for the API. So if Vino can have such a feature, it would be very helpful.
Also, how do I bench mark a custom model? not classification.

**Comment by jgespino** [comment]
Hi @mhamdan91 

To benchmark a model, you can use the benchmark_app:
C++: https://docs.openvinotoolkit.org/2020.4/openvino_inference_engine_samples_benchmark_app_README.html

Python: https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html

Regards,
Jesus

**Comment by mhamdan91** [comment]
Thanks @jgespino .
Would you consider adding the requested feature?

**Comment by jgespino** [comment]
@mhamdan91 I will check with my peers and the development team for consideration.

**Comment by luoyiroy** [comment]
Hi @mhamdan91 
The 2020.4 already allows you to read ONNX files directly from the C++ API without converting to IR format. Please use functions directly to read models in ONNX format without convert to IR format.

[CNNNetwork InferenceEngine::Core::ReadNetwork( const std::string & modelPath, const std::string & binPath = {} ) const](https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1Core.html#ac716dda382aefd09264b60ea40def3ef)

When the second argument 'binPath' is null, the function will read the ONNX model directly.

**Comment by mhamdan91** [comment]
Hi @luoyiroy , I meant to generate C (Not C++ ) code representation of ONNX that is ready for inference without to run it e.g. on a microcontroller.

**Comment by luoyiroy** [comment]
Hi @mhamdan91 
Can you elaborate on what you are looking for? If I understand you correctly, you want to convert an existing ONNX model directly into C code for deployment on a microsystem (e.g. an embedded device such as an STM32). Usually, an IR model or ONNX model needs to be based on a runtime written in C/C++ to perform inferencing. Since the runtime is open source, you can deploy the runtime directly to your target system, and then use the C/C++ interface of runtime for the original ONNX file to do the neural network inferencing. If you want to translate the ONNX model directly into C code, I think you can consult the more specialized Microsoft ONNX team to see if they can help you with this.
https://github.com/onnx/onnx/issues

**Comment by mhamdan91** [comment]
Hi @luoyiroy , Correct. I want to translate ONNX directly into C code. Btw, is the runtime a mix of C and C++? or is inferencing supported by C only ? As my uC compiler is C targeted.

**Comment by luoyiroy** [comment]
@mhamdan91 
Please check with Microsoft's ONNX team. This issue is not related to OpenVINO product.
In terms of how to convert the ONNX files into code that can be executed directly in C, I think you just need to copy the following three files onto your microsystem and execute them.
- Your ONNX model file
- Using ONNX C binding interface to write an inference code and build it to binary 
- ONNXRuntime compiled binaries

**Comment by mhamdan91** [comment]
@luoyiroy  Right. just to confirm,  "Using ONNX C binding interface to write an inference code and build it to binary" this is separate from openVINO or is such interface available in openVINO? - i.e. the steps you suggested are done within openVINO or you suggest that I look for C binding interface and ONNXRuntime?

**Comment by luoyiroy** [comment]
> @luoyiroy Right. just to confirm, "Using ONNX C binding interface to write an inference code and build it to binary" this is separate from openVINO or is such interface available in openVINO? - i.e. the steps you suggested are done within openVINO or you suggest that I look for C binding interface and ONNXRuntime?

@mhamdan91 
Yes, it is totally two independent works between OpenVINO and ONNX at all.
I think your work is only about the ONNX part and has nothing to do with OpenVINO. I have collected the relevant documentation for you here, please refer to Microsoft's ONNX GitHub for inference your code with C API.
https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md

**Comment by mhamdan91** [comment]
Thank you.
