### ISSUE TITLE
[Feature Request]: Add Support for `MLX` Frontend

### ISSUE THREAD

**Issue by NripeshN** [openvinotoolkit/openvino#24340]
### Request Description

I am writing to propose the inclusion of support for the [MLX](https://github.com/ml-explore/mlx) frontend in the OpenVINO toolkit. 

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by rkazants** [comment]
Hi @NripeshN,

It is quite interesting. I see it is young framework and already collected 28k stars in GitHub. Really great work!

However, is there any objective reason about why research scientist and engineers will select MLX framework for training new models instead of PyTorch? We observe PyTorch to keep a trend despite some new frameworks like JAX, MindSpore made attempts to accelerate training, etc. but anyway scientists select PyTorch. That seems a fact. So our current efforts are absolutely concentrated around PyTorch models support.

In the meantime, we are always open and welcome to our external contributors who want to add new frontend. We can provide more details about how to do this and support this contribution.

Best regards,
Roman

**Comment by NripeshN** [comment]
> is there any objective reason about why research scientist and engineers will select MLX framework for training new models instead of PyTorch?

I think this comment https://github.com/ml-explore/mlx/issues/12#issuecomment-1843956313 explains this in detail. I'd love to contribute and try add this new frontend. Could you please provide me more details to do so?

**Comment by rkazants** [comment]
> Hi @rkazants I think this comment [ml-explore/mlx#12 (comment)](https://github.com/ml-explore/mlx/issues/12#issuecomment-1843956313) explains this in detail. I'd love to contribute and try add this new frontend. Could you please provide me more details to do so?

@NripeshN, cool! Give me some time and I will be back with instructions.

Best regards,
Roman

**Comment by andrei-kochin** [comment]
@NripeshN any updates on the question above?
