### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by krogueintel** [openvinotoolkit/openvino#26]
make install target does not appear to install the .cmake files; it would also be ideal to also have pkg-config files too.

**Comment by shubha-ramani** [comment]
Hi krogueintel. I assume that you're using OpenVino on Ubuntu or some Linux variant ? Why do you need *.cmake files ? pkg-config is normally used on Linux systems and OpenVino is supported on both Windows and Linux.

**Comment by alalek** [comment]
[OpenVINO samples](https://github.com/opencv/open_model_zoo/blob/2018/demos/CMakeLists.txt) expect CMake files for processing `find_package(InferenceEngine)` statement.

**Comment by krogueintel** [comment]
Here are the issues:

- The binary version of OpenVINO does not support Ubuntu 16.04
- The dldt/inference_engine make install target does **NOT** install any pkg-config files for its libraries
- The dldt/inference_engine make install target does **NOT** install any .cmake for its libraries
- The open_model_zoo expects .cmake files, the demos fail to build.

I managed to get the open_mode_zoo demos to build by manually copying the .cmake files of the build process of dldt/interence_engine.  

As of right now, make install is not sufficient to use dldt/inference_engine libraries with cmake.

Ideally, pkg-config files wold also be added to the make install of dldt/inference-engine since there are no such make either.

**Comment by vmatveic** [comment]
Hi @krogueintel @shubha-ramani @alalek ,

Let me comment here regarding proper way of using dldt and open-model-zoo repos.

As first, we don’t officially support Ubuntu 18.04 yet (test environment is not completely adapted to Ubuntu 18.04 so we can't guarantee required quality so far).

Second, make install is not implemented for our CMake project… Instead, if you want to use binaries from dldt build you can just point InferenceEngine_DIR env variable to the cmake folder where you executed cmake build for the dldt project from. You will also need to configure some OpenCV version (set OpenCV_DIR), you can point it to cmake folder within OpenCV package from the openVINO release packet (current version of the repos is aligned with openVINO 2018 R3 version, R4 is going to be merged to these open source repo soon).

So, you need to use openVINO binary package. It’s supposed to be used initially if you build open-model-zoo demos or some other applications. And dldt repo is usually used just to contribute some features/impacts to the inference engine core part…

I've described possible ways of working in the following issue:
https://github.com/opencv/open_model_zoo/issues/6

1. There is **open-model-zoo** repo with a list of demos. These demos are designed to be built separately with the IE environment source before. If you want to build these demos then you need to have OpenVINO package (of appropriate version, currently for R3) installed (can be taken from https://software.intel.com/en-us/openvino-toolkit). Then you need to source an environment from that package (to get InferenceEngine and OpenCV configured for CMake). After that you are able to successfully build demos by creating of own folder and running of “cmake ..” command from here.
1. There is another **dldt** repo which is used to contribute to InferenceEngine core part. If you want to build dldt sources then you can do that like you did (clone dldt repo and build it). Also, it’s implied that the samples from this repo are built together with this dldt project but not separately. If you still want to build these samples separately then you need to copy samples to own location and update its CMake architecture manually + copy extensions here (to have it similar to demos structure within open-model-zoo) and use an environment from an OpenVINO binary package.
1. Also, there is still a possibility to use built dldt binaries like openVINO environment for a separate samples/demos build. You need to set InferenceEngine_DIR to a cmake folder you run “cmake -DGEMM=MKL -DENABLE_MKL_DNN=ON -DCMAKE_BUILD_TYPE=Release ..” command from. But please note, in R3 release this possibility is not completely verified but it will be improved in R4 (also, in R4 you will not need to copy extensions to samples/demos directory, it will be automatically used from binaries).

So, just to repeat, we suggest to use openVINO package (of R version currently) for a separate demos build and use an environment from here. R3 – because current GitHub version of the open source project is adapted to R3 version of openVINO.

THANKS!

**Comment by jiapei100** [comment]
@vmatveic 
OpenVINO R3 will install FFmpeg packages automatically, which may bring the conflicts. Like me, I installed FFmpeg from the source. 

Also, OpenVINO R3 installed libgtk2-dev, which is outdated as well. 

Will OpenVINO open-source someday???

**Comment by jiapei100** [comment]
@shubha-ramani 

Why Windows is still supported ?? That's weird....
