### ISSUE TITLE
Error of collect statistics

### ISSUE THREAD

**Issue by flynnamy** [openvinotoolkit/openvino#261]
I have a problem when I do collect statistics like in tutourial.My command as following:python collect_statistics.py --config ~/inception_v1.yml -d ~/defenitions.yml -M /home/user/intel/openvino/deployment_tools/model_optimizer --models ~/models --source /media/user/calibration/datasets --annotations ~/annotations --converted_models ~/models

Error info:
![image](https://user-images.githubusercontent.com/20398890/65693231-8ad63d80-e0a6-11e9-8a2c-68bc6b5762ec.png)
How to solve this?Or could you please share an example for converting F32 to int8?Thanks!@asuhov

**Comment by flynnamy** [comment]
When I try resnet50_v1,it has same problems.@asuhov
Error info:
![image](https://user-images.githubusercontent.com/20398890/65736225-e6d3ad00-e10c-11e9-9efb-cc1969481bb4.png)

**Comment by shubha-ramani** [comment]
Dear @flynnamy 
That's because according to the [Model Optimizer Supported Frameworks Doc](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html) SpatialSqueeze is not a supported layer.

However, you can certainly make a custom layer to support SpatialSqueeze.  Here is information on how to do that:

For custom layers here is what I refer our forum customers to:

Previous Intel Developer Zone Post which I responded to:
[https://software.intel.com/en-us/forums/computer-vision/topic/805980](https://software.intel.com/en-us/forums/computer-vision/topic/805980)

Just redirect the 2018 https://github.com/opencv/dldt  links to 2019 but the idea is the same

OpenVino Custom Layers Tutorial:
[https://github.com/david-drew/OpenVINO-Custom-Layers](https://github.com/david-drew/OpenVINO-Custom-Layers)

Custom Layers in Model Optimizer Doc:
[http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html)

IE Kernels Extensibility Doc:
[http://docs.openvinotoolkit.org/latest/_docs_IE_DG_Integrate_your_kernels_into_IE.html](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_Integrate_your_kernels_into_IE.html)

**Comment by flynnamy** [comment]
@shubha-ramani  Any examples of onnx or pytorch model which does convert f32 to int8 in dldt?Thanks!

**Comment by elvin-nnov** [comment]
@flynnamy Could you please use simplified mode of the calibration tool instead of direct call of collect_statistics.py? https://docs.openvinotoolkit.org/latest/_inference_engine_tools_calibration_tool_README.html#simplified_mode 
You might need to 
1. use `-e` comamnd line argument to point directory contaiing extension library having that SpatialSqueeze layer. 
2. have `cpu_extensions: AUTO` parameter in yml file like it is described here: https://docs.openvinotoolkit.org/latest/_tools_accuracy_checker_accuracy_checker_launcher_dlsdk_launcher_readme.html

**Comment by flynnamy** [comment]
@elvin-nnov  I check that  SpatialSqueeze is not supported op now. Which extension library contails SpatialSqueeze layer? On the other hand, I want to try onnx model.Could you please share some examples about onnx which does convert f32 to int8? Thanks!

**Comment by elvin-nnov** [comment]
If layer is not implemented in current extension library https://github.com/opencv/dldt/tree/2019/inference-engine/src/extension, then you have to develop it similar to it layers in extensio library. please see links how to develop and register custom layers in @shubha-ramani reply

**Comment by AnastasiaKazantaeva** [comment]
It seems that this issue is not actual anymore, close it. Feel free to reopen it or better create a new issue in cases of some questions/problems
