### ISSUE TITLE
Failed to convert caffemodel to openvino IR

### ISSUE THREAD

**Issue by wfchair** [openvinotoolkit/openvino#2658]
https://github.com/wujixiu/helmet-detection
I wanna convert the SSD-RPA512 hardhat caffemodel into intel openvino IR, but failed.
$ python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --input_model ./VGG_RPA512_Hardhat_iter_148000.caffemodel

The error is unsupported layer; What can I do to fix the problem?
Can you share a detailed procedure to fix the problem?

![mo](https://user-images.githubusercontent.com/38781231/95717755-0306a580-0ca0-11eb-8da1-ffdb70f3aa94.png)

**Comment by mliu2020** [comment]
Hi @wfchair,

I am transferring this to OpenVINO since this is out of DL Streamer's scope. DL Streamer acting the integration framework of OpenVINO and video inputs, it uses OpenVINO inference engine so the model requirement is the same.

This is a typical Model Optimizer question, you can also post this question to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit

Just look at your logs, here are the tips you might check:
- From the log, it seems like you didn’t run prerequisites installation for Caffe on OpenVINO, I saw the warning of protobuf which might causes your error. If you didn’t, please run and try this again.

- If you did run the installation script, you were having a custom layer issue, please refer to Custom Layers in Model Optimizer of Model Optimizer Dev Guide to resolve the customer layer issues.

Mark

**Comment by jgespino** [comment]
Closing, feel free to re-open if additional assistance is needed.
