### ISSUE TITLE
Having a static library version of OpenVINO

### ISSUE THREAD

**Issue by emmanuelattia-philips** [openvinotoolkit/openvino#2675]
Hello,

It would be super useful to have a static library version of OpenVINO
The use case for that would be multiple plugins (not aware of each others / having differents cycle of dev and team of dev) being linked with different versions of OpenVINO, needed to be gathered in the same process.

Ideally it would simply be enabled by one or several Cmake flags.

Is it something planned ? I'm aware that it's a long shot.

Is it something you would be interested in being pull requested ?
I don't think it would be easily done in one merge, maybe going step by step (first having ngraph statically linked, then mkl dnn plugin etc...), I might not be able to do this on my own since it involves a lot of the current CMake machinery (and a bit of source code changes)

Any other thoughts ?

Best Regards

**Comment by ilya-lavrenov** [comment]
> The use case for that would be multiple plugins (not aware of each others / having differents cycle of dev and team of dev) being linked with different versions of OpenVINO, needed to be gathered in the same process.

Plugins linked with different version of OpenVINO are not guaranteed to work. From release to release interface between plugin and Inference Engine is changing, so plugin from 2021.1 release will not work with 2020.4 and so on.

So, how static linkage will solve such issues?

**Comment by emmanuelattia-philips** [comment]
I'm not talking about OpenVINO's plugins, but plugin of another software which might be using different OpenVINO versions.

**Comment by ilya-lavrenov** [comment]
Ok, I see your point, thanks.

Actually, compiling of ngraph and other libraries as `STATIC` instead of `DYNAMIC` looks simple, because cmake has https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html which change library type for targets where it's not set explicitly. But IE sets library library type explicitly, but we can remove it.

Second problem - we load plugin dynamically in runtime. In static linkage, we need to compile plugins as static libraries as well and combine with `libinference_engine.a` library. It can be done as a separate step like combine `libinference_engine.a`, `libngraph.a`, `libinference_engine_transformations.a`, other dependencies and `libMKLDNNPlugin.a` into a new library like `libinference_engine_world.a` (like `libopencv_world.a`). But code of plugin can be thrown away by a linker, because IE does not have strict dependency on a plugin code. So, we need to keep a reference to `CreatePluginEngine` (the only public function of plugin) which creates a plugin instance somewhere inside the `ie_core.cpp` (or any other IE source file)

Third problem - what if we want to work with two plugins? They both have `CreatePluginEngine` function implementation which creates plugin instance, linker will complain about multiple definitions. Solution could be - replace `CreatePluginEngine` with `CreatePluginEngine_CPU`, `CreatePluginEngine_GPU` where the suffix defines a device name. Based on that, we can combine multiple plugins into a single `libinference_engine_world.a`. Once `Core::LoadNetwork("CPU")` is called, `Core` tries to find `CreatePluginEngine_CPU` and create a plugin instance.

I think you can start with these steps one by one.

**Comment by emmanuelattia-philips** [comment]
Thank you for the indications, can i use this issue to report blocking point for me when advancing on this task ?

**Comment by ilya-lavrenov** [comment]
@emmanuelattia-philips sure.

**Comment by emmanuelattia-philips** [comment]
I'm sorry i messed up my branch for the PR and i had to overwrite it, should I open a new PR to pursue the discussion ?

**Comment by ilya-lavrenov** [comment]
> should I open a new PR to pursue the discussion

We should not close PR and create a new one since discussion is lost. Just try to merge your changes with latest master and push to your branch with 1st PR.

**Comment by emmanuelattia-philips** [comment]
Github doesn't allow me to reopen it because i had to force push...

**Comment by ilya-lavrenov** [comment]
Ok, let's create a new PR.

**Comment by jgespino** [comment]
Closing issue, please re-open or start a new issue if additional assistance is needed.

**Comment by ilya-lavrenov** [comment]
The work is still in progress. Suggest keeping it open until the final PR is merged.

**Comment by CyunXiong** [comment]
at"/home/pi/opt/intel/l_openvino_toolkit_runtime_raspbian_p_2021.3.394/deployment_tools/inference_engine/samples/python/ngraph_function_creation_sample",however, it shows"ModuleNotFoundError: No module named 'ngraph'".

**Comment by ilya-lavrenov** [comment]
@CyunXiong have you used this https://github.com/openvinotoolkit/openvino/wiki/StaticLibraries guide to build static OpenVINO libraries?
