### ISSUE TITLE
-DENABLE_PYTHON=ON requires cython

### ISSUE THREAD

**Issue by peckhart89** [openvinotoolkit/openvino#272]
cmake required the cython module when the -DENABLE_PYTHON=ON flag was set. This is not documented in the "build for linux instructions" of the README

**Comment by shubha-ramani** [comment]
Dear @peckhart89 ,
Indeed you are correct ! Documentation needs updating about this.
Thanks for your sharp eyes !

Shubha

**Comment by ilya-lavrenov** [comment]
@peckhart89 now it's mentioned that in order to build a python, you have to install all the requirements (see build instruction https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md and https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/ie_bridges/python)
