### ISSUE TITLE
Labels missing for model

### ISSUE THREAD

**Issue by deimsdeutsch** [openvinotoolkit/openvino#291]
https://download.01.org/opencv/openvino_training_extensions/models/vehicle_attributes/

Can you please share the details of this model ?
accuracy, labels and other details ?

**Comment by avitial** [comment]
@deimsdeutsch all details of such model posted in OpenVINO™ Training Extensions are available in [README](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/vehicle_attributes/README.md). Not sure if any of the details there have been updated from the time this issue was submitted, as this issue is quite old and updates there may have occurred.

I will close this issue now, but please feel free to reopen or create a new one if help is still required.
