### ISSUE TITLE
Question about converting onnx quantized model to openvino

### ISSUE THREAD

**Issue by Nedae** [openvinotoolkit/openvino#2976]
##### System information (version)
- OpenVINO=> openvino_2021.1.110
- Operating System / Platform => Ubuntu 18.04.5 LTS
- Compiler => python 3.6.9, [GCC 8.4.0]
- Problem classification => Model Conversion

##### Detailed description
Is there a guideline on converting an already quantized onnx model to openvino?

What I have tried is that I called `/opt/intel/openvino_2021.1.110/deployment_tools/model_optimizer/mo_onnx.py` for a quantized onnx model, and the following is the errors I receive
```
[ ERROR ]  Cannot infer shapes or values for node "481_quantized".
[ ERROR ]  There is no registered "infer" function for node "481_quantized" with op = "QLinearConv". Please implement this function in the extensions. 
```

**Comment by jgespino** [comment]
Hi @Nedae 

Thanks for reaching out, the error you are seeing is due to the ONNX QLinearConv operation not being supported. The OpenVINO toolkit does support ONNX QuantizeLinear operation. Please see the list of [ONNX Supported Operators](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx_supported_operators).

You can try and implement this operation, see the following for tutorial:
https://github.com/david-drew/OpenVINO-Custom-Layers/blob/master/2019.r2.0/ReadMe.Linux.2019.r2.md

Regards,
Jesus

**Comment by Nedae** [comment]
I will give it a try, thanks you @jgespino !

**Comment by slyalin** [comment]
Hi @Nedae,

An easies way to support QLinearConv is to decompose it according to ONNX specification to QuantizeLinear(Convolution(DequantizeLinear(data), DequantizeLinear(weights)) inside Model Optimizer. Then it should be further transformed in Model Optimier to make Quantize/Dequantize pairs. The current Model Optimizer can fuse such pairs to supported primitives (FakeQuantize) that enables real int8 execution for such networks. OpenVINO expresses int8 models with implicit quantization using FakeQuantize ops, so the steps described above have a goal to transform network to this form.

Please avoid implementing int8 QLinearConv as a separate custom operation, in this case you have to implement it from scratch having already implemented int8 convolutions in OpenVINO which are enabled with FakeQuantize flow.

**Comment by Nedae** [comment]
Hi @slyalin, 
Do you have any sample/relevant piece of code (for any op, not necessarily this one) that you can point me to?

**Comment by slyalin** [comment]
@Nedae, here is relatively simple code that decomposes Flatten from ONNX to semantically equivalent sub-graph using OpenVINO ops: https://github.com/openvinotoolkit/openvino/blob/master/model-optimizer/extensions/front/onnx/flattenONNX_to_reshape.py. Also search for QuantizeLinear and DequantizeLinear in model_optimizer directory to understand how it is processed right now.

I would say if you don't have experience of Model Optimizer modification, QLinearConv is not a good thing for the first try, it includes some specifics about how FakeQuantize is used to represent int8 networks. You have to look into existing IRs with FQs produced by POT. Here is some material relevant to the topic:

https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Int8Inference.html
https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_IR_suitable_for_INT8_inference.html
https://docs.openvinotoolkit.org/latest/openvino_docs_ops_quantization_FakeQuantize_1.html

**Comment by Nedae** [comment]
Thanks for all these @slyalin!
Yes, this area is new to me. I will look into all the docs and codes you sent.
By the way, should we expect openvino to support `QlinearConv`, `QLinearAdd`, and `QLinearMul` any time soon, or in a foreseeable future?

**Comment by slyalin** [comment]
@Nedae, I cannot comment on future plans. If someone contribute to this, I can help with reviewing a PR. BTW, are you aware of int8 capabilities that OpenVINO provides? I mean POT (https://docs.openvinotoolkit.org/latest/pot_README.html) and NNCF (https://github.com/openvinotoolkit/nncf). They can help you to bake your own int8 model.

**Comment by Nedae** [comment]
@slyalin 
Oh, yeah! I have already done int8 calibration in OpenVINO. The conversion of already quantized model was the second step for me. 
Thanks!

**Comment by Hrayo712** [comment]
@slyalin 

From your comments, I am getting that OpenVino currently supports the transformation of ONNX quantized models (expressed using QuantizeLinear/Dequantizelinear pairs) to OpenVino fakequant models, to then allow computing these in int8. 

[https://github.com/openvinotoolkit/openvino/blob/3f35e2a32179ad055904700c3bfbbdd41c4f5fa6/tools/mo/openvino/tools/mo/middle/quantize_linear_resolver.py#L21](url)

Is my understanding correct ?

**Comment by Mxx-001** [comment]
> @slyalin Oh, yeah! I have already done int8 calibration in OpenVINO. The conversion of already quantized model was the second step for me. Thanks!

I have the same problem, may I ask how you implemented the code?

**Comment by Mxx-001** [comment]
> here is relatively simple code that decomposes Flatten from ONNX to semantically equivalent sub-graph using OpenVINO ops: https://github.com/openvinotoolkit/openvino/blob/master/model-optimizer/extensions/front/onnx/flattenONNX_to_reshape.py. Also search for QuantizeLinear and DequantizeLinear in model_optimizer directory to understand how it is processed right now.
> 
> I would say if you don't have experience of Model Optimizer modification, QLinearConv is not a good thing for the first try, it includes some specifics about how FakeQuantize is used to represent int8 networks. You have to look into existing IRs with FQs produced by POT. Here is some material relevant to the topic:



> @slyalin Oh, yeah! I have already done int8 calibration in OpenVINO. The conversion of already quantized model was the second step for me. Thanks!

I have the same problem, may I ask how is your code implemented?

**Comment by Mxx-001** [comment]
> @slyalin Oh, yeah! I have already done int8 calibration in OpenVINO. The conversion of already quantized model was the second step for me. Thanks!

I have the same problem, may I ask how is your code implemented?

**Comment by slyalin** [comment]
> @slyalin
> 
> From your comments, I am getting that OpenVino currently supports the transformation of ONNX quantized models (expressed using QuantizeLinear/Dequantizelinear pairs, aka Q/DQ) to OpenVino fakequant models, to then allow computing these in int8.
> 
> https://github.com/openvinotoolkit/openvino/blob/3f35e2a32179ad055904700c3bfbbdd41c4f5fa6/tools/mo/openvino/tools/mo/middle/quantize_linear_resolver.py#L21
> 
> Is my understanding correct ?

Hi @Hrayo712, precisely speaking we have switched to the new front-end for ONNX which is implemented in C++, but int8 approach is the same: first we decompose ONNX Qxxx operations in sub-graph consisting only supported OpenVINO operations using strict mathematical definition of operations, then we optimize these graphs applying several transformations in the optimization pipeline to make the graph suitable for further int8 efficient execution. FakeQuantize operation appears at some stage in the pipeline, but it is rather internal detail then something that you have to worry about.

**Comment by slyalin** [comment]
> > @slyalin Oh, yeah! I have already done int8 calibration in OpenVINO. The conversion of already quantized model was the second step for me. Thanks!
> 
> I have the same problem, may I ask how is your code implemented?

@Mxx-001, could you explain which particular problem you have? Thread says that the problem was resolved. Now we have switched to C++ ONNX front-end, this is a different code-base, in the following file you can see how QLinearConv is decomposed: https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/qlinear_conv.cpp.

I would encourage you not to look into Python flow, because we are trending to always use C++ front-ends instead, and there we have the most up-to-date code. Do you need an advise how to implement int8 for other frameworks (not for ONNX)?

**Comment by d-smit** [comment]
Hi there, long shot but I am also having a problem converting my quantized ONNX model into BLOB format using OpenVINO. 

My command (I realise the --data_type arg is wrong as the model has been quantized)

! source /opt/intel/openvino_2021/bin/setupvars.sh
! python /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py \
--input_model  /content/gdrive/MyDrive/ColabNotebooks/yolov5/train_new/output_pruned/yolov5s_sparse.onnx \
--model_name yolov5sp \
--data_type FP16 \
--output_dir /content/gdrive/MyDrive/ColabNotebooks/yolov5/train_new/output_pruned/ \
--reverse_input_channel \
--scale 255 \
--input_shape [1,3,416,416] \
--output "output1_yolov5,output2_yolov5,output3_yolov5"

My error:

[setupvars.sh] OpenVINO environment initialized
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/content/gdrive/MyDrive/ColabNotebooks/yolov5/train_new/output_pruned/yolov5s_sparse.onnx
	- Path for generated IR: 	/content/gdrive/MyDrive/ColabNotebooks/yolov5/train_new/output_pruned/
	- IR output name: 	yolov5sp
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	output1_yolov5,output2_yolov5,output3_yolov5
	- Input shapes: 	[1,3,416,416]
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	255.0
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	True
ONNX specific parameters:
	- Inference Engine found in: 	/usr/local/lib/python3.7/dist-packages/openvino
Inference Engine version: 	2021.4.0-3839-cd81789d294-releases/2021/4
Model Optimizer version: 	2021.4.0-3839-cd81789d294-releases/2021/4
[ ERROR ]  Cannot infer shapes or values for node "Conv_54_quant".
[ ERROR ]  There is no registered "infer" function for node "Conv_54_quant" with op = "QLinearConv". Please implement this function in the extensions. 
 For more information please refer to Model Optimizer FAQ, question #37. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=37#question-37)
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <UNKNOWN>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Conv_54_quant" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

**Comment by jgespino** [comment]
@d-smit Could you please start a new issue as this one has been closed for quite some time? Also, if possible please try on the latest OpenVINO 2022.1 release or the pre-release 2022.2 package. 

https://pypi.org/project/openvino-dev/2022.2.0.dev20220829/
