### ISSUE TITLE
Could any one supply 2018 branch much earlier Version? InferenceEngine reading network error

### ISSUE THREAD

**Issue by sainttelant** [openvinotoolkit/openvino#300]
Could any one supply 2018 branch much earlier Version?

Because, I need to deploy my NEW detection models on application system, however  when i embedded  NEW bin and xml files generated by  the latest OPIMIZER 2019 into the system,  then the terminal throws as  "InferenceEngine error".   

error reading network:cannot parse future versions :6

**Comment by sainttelant** [comment]
i checked the other relevant issues,  and found the reason why caused such issue due to different version of toolKIt of openVINO,   then, i  found  that the older version of OPTIMIZER we used is 2018 version2.0 probably.  ( i  checked the ie_cnn_net_reader.h ,its title writes 2018 intel corporation version2.0)
So, does that mean i  need to update the inference parts in accordance with the optimizer version?   is there any much more easier way to solve such issue?     or if i have to update the inference Engine, how should i do ? for a instance, just subsitude some headers and cpp files in application?

**Comment by sainttelant** [comment]
Any  advise  will be appreciated . Thanks in advance .

**Comment by moslex** [comment]
Hello, @sainttelant. We do not support forward compatibility and recommendation for you is to switch on a newer version of Inference Engine. We can't provide you version older than 2018 R3 because R3 was a start point on making DLDT open source delivery.

Could you please provide more details about your problem?
With OpenVINO 2019 R3 we introduced IE Core API and provided guide how to migrate on it: https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Migration_CoreAPI.html
If you want continue using OpenVINO (IE and new models enabled in MO) it is highly recommended to migrate your application on this Core API.

**Comment by sainttelant** [comment]
@moslex  thanks for your help, it works,  as you mentioned ,i  got your inspiration, i tried 2018R4, it was the same verion we used.  

Anyway, i will  try to upgrade my application as well. thanks for your help
