### ISSUE TITLE
why I get FP16 and I32 MIXED format?

### ISSUE THREAD

**Issue by cosimo17** [openvinotoolkit/openvino#301]
I have convert a tensorflow model to IR model. I do infenrence on raspberry+NCS2. but I got the error:
RuntimeError: The plugin does not support networks with MIXED format.
Then I checked the xml file.I find there are FP16 precision and I32 precision.I have point the --data_type FP 16 when I run mo_tf.py.
why I got this? How to get a pure FP16 precision model?
Thanks

**Comment by avitial** [comment]
@cosimo17 if you are still having this issue I would suggest to try a newer OpenVINO release as there have been new updates since the time you encountered this. If you need to get the IR model in FP16 precision, adding the `--data_type FP16` should be sufficient. Please note the NCS2 (Myriad plugin) supports Half Precision Floating Point (FP16) only as stated [here](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html#supported_model_formats).

If you are still facing this issue kindly share your .pb model files and full MO command used to convert to IR and sample/demo used for inference. I will close issue for now but please reopen if issue persists.

**Comment by maxlytkin** [comment]
test
