### ISSUE TITLE
Loading/saving a previously calculated calibration cache

### ISSUE THREAD

**Issue by Nedae** [openvinotoolkit/openvino#3019]
Hi,
1) Is it possible to save calibration statistics/cache from the calibration tool (calibrate.py)?
2) Is it possible to load a previously generated calibration statistics/cache to do int8 calibration with that?

**Comment by AlexKoff88** [comment]
Hi @Nedae,

Where did you find calibrate.py file?

If we are talking about INT8 quantization inside OpenVINO this is what POT tool is responsible for. Please find more info about it [here](https://docs.openvinotoolkit.org/latest/pot_README.html). POT does not have any functionality for statistics caching/loading. This is because we assume that it should be quite a fast process which requires inference over 100-300 samples.

Any feedback on the last part is appreciated.

**Comment by Nedae** [comment]
Hi @AlexKoff88! Thanks!
The reason I was interested to save and load the calibration data  was not to do the quantization faster, but I was just investigating whether it would be possible to use the exact calibration values calculated in other platforms (such as onnx.

**Comment by AlexKoff88** [comment]
It should be difficult to implement because POT tool is designed specifically for OpenVINO Intermediate Representation (IR) which has a different operation set and notation from ONNX. For simple models, I guess this is doable. But there will be problems how to map these statistics in general case.
