### ISSUE TITLE
[Bug] LoadNetwork Error

### ISSUE THREAD

**Issue by fel88** [openvinotoolkit/openvino#3076]
Hi, I get error when try to load network (ie.LoadNetwork)
OpenVINO: 2020.4 (Windows 10)

Steps to reproduce:
1. Download ONNX model:
https://github.com/omasaht/headpose-fsanet-pytorch/blob/master/pretrained/fsanet-var-iter-688590.onnx

2. Convert to xml/bin 
python .\mo.py --input_model .\fsanet-var.onnx

3. Run benchmark app (CPU and MYRIAD give different errors)
.\benchmark_app.exe -m .\fsanet-var.xml -d  MYRIAD
![image](https://user-images.githubusercontent.com/15663687/98796417-678e5f00-241c-11eb-8409-ce317a3c88f8.png)
.\benchmark_app.exe -m .\fsanet-var.xml
![image](https://user-images.githubusercontent.com/15663687/98796475-770da800-241c-11eb-8a2a-6714bdc92310.png)

What could be a problem? How to fix it?

**Comment by avitial** [comment]
Hi @fel88, thanks for reaching out. Have you tried running benchmark app with such model on GPU plugin? If not, I'd suggest to try this if your CPU has integrated graphics. Please share the results.

Based on the info looks like this ONNX model came from a PyTorch implementation, is this correct? Checking the Supported PyTorch models on OpenVINO [documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#supported_pytorch_models_via_onnx_conversion), FSA-Net model is not officially listed as supported. So that may be the reason why model fails at runtime. 


Regards,
Luis

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
