### ISSUE TITLE
[ ERROR ] Unknown model format! Cannot find reader for model format: xml and read the model: human-pose-estimation-0001.xml. Please check that reader library exists in your PATH.

### ISSUE THREAD

**Issue by jsynnott** [openvinotoolkit/openvino#3325]
Hello,
I am attempting to run the human_pose_estimation.exe demo on Windows 10. The installation verification checks run without any problem, however, when I run human_pose_extimation.exe with the following command:

`C:\Users\jsynn\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release>human_pose_estimation_demo.exe -i 0 -d MYRIAD -m human-pose-estimation-0001.xml`

I get the following error:

`InferenceEngine:        API version ......... 2.1
        Build ........... 2021.1.0-1237-bece22ac675-releases/2021/1
Parsing input parameters
[ ERROR ] Unknown model format! Cannot find reader for model format: xml and read the model: human-pose-estimation-0001.xml. Please check that reader library exists in your PATH.`

The model I am using is downloaded directly from:

`https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/human-pose-estimation-0001/FP32/human-pose-estimation-0001.xml`

Any help would be very much appreciated.

**Comment by jgespino** [comment]
Hi @jsynnott 

I have seen this issue before when a model is corrupted or .bin was passed instead of .xml. From your command above, I can see you passed the correct file. Could you try downloading the 2021.1 model version from the following link and do a checksum?

https://download.01.org/opencv/2021/openvinotoolkit/2021.1/open_model_zoo/models_bin/2/human-pose-estimation-0001/FP16/

Checksum the files using: `certUtil -hashfile <file_name> md5`
```
File: human-pose-estimation-0001.xml 
MD5: ca474c065d70e248aa958057e1ad84a6

File: human-pose-estimation-0001.bin
MD5: c1ea4d3f2f24abbe789ab6a4d5416cf8
```

Regards,
Jesus

**Comment by jsynnott** [comment]
Hi Jesus,
Thank you for your very quick response!

I have downloaded the .bin and .xml from the link you have provided. The following is the checksum result:
'SHA1 hash of human-pose-estimation-0001.bin:
a7adea1e8882d75bb3f4b5bd5aaf6175fa4ab641'

'SHA1 hash of human-pose-estimation-0001.xml:
9e24105c0fb16083920b97740a844535d608b318'

Unfortunately I still get exactly the same error. Could there perhaps be an issue with my PATH setup? I have run setupvars.bat in the same console before trying this.

Any further suggestions would be very much appreciated!

Thanks,
Jonathan

**Comment by jgespino** [comment]
Hi @jsynnott 

Thanks for checking the checksum, SHA1 matches my files as well. I don't believe it's a PATH issue since you ran setupvars.bat, If setupvars.bat was not ran you would see many popup errors. I am also curious if you see the same error using a different demo and model? Could you please provide the following information?

- How did you install OpenVINO toolkit?
- Python version
- CMake version
- Microsoft Visual Studio version

Regards,
Jesus

**Comment by ilya-lavrenov** [comment]
@jgespino please, check that `inference_engine_ir_reader.so` is located at the same folder as `inference_engine.so`.

**Comment by jgespino** [comment]
Hi @ilya-lavrenov on Windows, `inference_engine_ir_reader.dll` is located in the same directory as `inference_engine.dll`.

@jsynnott Could you check if you have `inference_engine_ir_reader.dll` along with `inference_engine.dll` in the following directory?

`C:\Program Files (x86)\Intel\openvino_2021.1.110\deployment_tools\inference_engine\bin\intel64\Release`

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open or start a new issues if additional assistance is needed.

**Comment by KamilMatejuk** [comment]
I had the same problem on linux. In my case it was due to plugins not being linked correctly. All I had to do was add the correct path to `LD_LIBRARY_PATH`:
```
find /opt/intel/openvino/* -type f -name "*plugin*"
    /opt/intel/openvino/runtime/lib/intel64/plugins.xml
    /opt/intel/openvino/runtime/lib/intel64/libopenvino_hetero_plugin.so
    /opt/intel/openvino/runtime/lib/intel64/libopenvino_auto_plugin.so
    /opt/intel/openvino/runtime/lib/intel64/libopenvino_intel_cpu_plugin.so
    /opt/intel/openvino/runtime/lib/intel64/libopenvino_intel_gpu_plugin.so
export LD_LIBRARY_PATH=/opt/intel/openvino/runtime/lib/intel64/
```

**Comment by dgorissen** [comment]
To help future googlers. I got bitten by this when using a model from the 2022.1.0 branch alongside a 2021.4 openvino installation. Using the 2021.4.2 tag of open model zoo fixed things.
