### ISSUE TITLE
No GetThreadDescription in Windows 10 IoT

### ISSUE THREAD

**Issue by wojsla** [openvinotoolkit/openvino#365]
I'm trying to run my application on Windows 10 IoT Enterprise (Version 1607). OpenVINO 2019 R2 works fine, but I'm having issues with 2019 R3. I am getting following error on start:

"The procedure entry point GetThreadDescription could not be located in the dynamic link library myriadPlugin.dll"

I found that similar issue has been already reported [here](https://forums.intel.com/s/question/0D50P00004TJ45x/problems-with-2019r3) but there is no solution or workaround.

**Comment by ArtemSkrebkov** [comment]
Documentation [here](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription) says that `GetThreadDescription` supported since `Windows 10, version 1607` Looks like exactly your version. Weird.

I can suggest a workaround. Just to comment out the body of [the function](https://github.com/opencv/dldt/blob/2019/inference-engine/thirdparty/movidius/WinPthread/win_pthread.c#L176) and make it always `return 0`, then re-compile myriadPlugin for your platform. 

I checked that it is used only for purposes of logging, so nothing dangerous shouldn happen, myriadPlugin still should be fully functional beside the thing that logger mechanism won't be printing names of threads.
