### ISSUE TITLE
AWS IoT Greengrass cannot find myriad 

### ISSUE THREAD

**Issue by Fatinnadiah** [openvinotoolkit/openvino#373]
I try to configure AWS IoT greengrass on my myriad devices but it cannot found it even though I already attach the devices path directory (/dev/bus/usb/003). Can anyone help me with this? 
Thank you

![image](https://user-images.githubusercontent.com/59385438/72974803-a4945100-3e0a-11ea-9e47-5897634084b2.png)

**Comment by brmarkus** [comment]
You have a Myriad (Myriad-X) NeuralComputeStick (NCS2) (USB3)?
You are setting-up AWS-greengrass to run *ON* the MyriadX USB-device?

Not sure I understood your environment...

You might want to look how to setup MyriadX together with OpenVINO here: "http://docs.openvinotoolkit.org/2019_R3.1/_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps".

If you want to see AWS-greengras as a kind of containerized environment then you might want to check how to setup OpenVINO and such VPU-devices like MyriadX in such a containerized environment here: "http://docs.openvinotoolkit.org/2019_R3.1/_docs_install_guides_installing_openvino_docker_linux.html".

The MyriadX USB-device gets reset when the Myriad-plugin gets initialized; the USB-device disappears from the USB-device (it was a high-speed USB2 device) and then appears again (as a USB3 super-speed device).
Therefore a UDEV-rule is ued on the HOST-system.
And within the container one recommendation is to use a libusb with udev-support disabled.
Otherwise, for instance for a Docker container environment, (root-)privileges would be required/recommended.

**Comment by Fatinnadiah** [comment]
Hi! Thank you for your response.
Yes I use both on board VPU and also NCS2. Yes I try to run my model as greengrass workload. 
I attached here the lambda configuration and also the lambda function log. 
I also found that the NCS2  gets reset when the Myriad-plugin gets initialized; the USB-device disappears from the USB-device (it was a high-speed USB2 device) and then appears again (as a USB3 super-speed device).
Can you explain more about this? Do I need to change something inside the udev file or just setup MYRIAD according to this link, "http://docs.openvinotoolkit.org/2019_R3.1/_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps"
[lambda_function.log](https://github.com/opencv/dldt/files/4107172/lambda_function.log)
![lambda_config](https://user-images.githubusercontent.com/59385438/73050829-0eb8fe80-3ebc-11ea-9a61-5cc8e8b1aed5.png)

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
