### ISSUE TITLE
How can I specify GPU？

### ISSUE THREAD

**Issue by qimoto** [openvinotoolkit/openvino#410]
I have NVIDIA's GPU on my computer, when I use openvino with command -d GPU, I got the error:
   No OpenCL device found which would match provided configuration:
        GeForce GTX 560 Ti: invalid vendor type

so how can I specify the intel's integrated graphics as my GPU, not nvidia's。。。

**Comment by brmarkus** [comment]
Not sure I understand you.
Do you have one GPU only (NVIDIA) or multiple GPUs (besides one from NVIDIA you have one from Intel as well)?

Can you run the OpenVINO sample `hello_query_device` and check which devices it detects (CPU, GPUs, VPUs, FPGAs, HDDLs), please?

Can you provide details about your SOC (e.g. `lscpu`, `cat /proc/cpuinfo`), please? It has an integraded GPU?

**Comment by leavim** [comment]
Hi @qimoto,
A couple of things I can suggest in "avoiding" discrete graphics card:

1. Make sure you have Internal/Integrated Graphics enabled in the BIOS. Once BIOS menu, the setting should be under **Chipset > Internal Graphics > [Enabled]** or similar.
2. Follow required steps to enable the toolkit components to use the processor graphics (GPU ). Find the steps for Linux [here](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html#additional-GPU-steps).

After performing these steps you should be able to run the OpenVINO* demo scripts just fine using the GPU plugin. You shouldn't have to remove the discrete graphics, both discrete and integrated graphics should run. I hope this works, let me know if it does not.

**If running on Windows** instead of step no. 2 follow [these steps](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_windows.html#Install-GPU). You may have to update my graphics driver with **Device Manager > Display adapters > Intel(R) HD Graphics > Search automatically for updated driver software**.

Best Regards,
Luis

**Comment by vladimir-paramuzov** [comment]
@qimoto Is your issue resolved by the comments above?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,

**Comment by deepwilson** [comment]
@AnastasiaKazantaeva Please could you elaborate on how you resolved it? It will help others as well.

Thanks!

**Comment by bharath5673** [comment]
> @AnastasiaKazantaeva Please could you elaborate on how you resolved it? It will help others as well.
> 
> Thanks!



> @AnastasiaKazantaeva Please could you elaborate on how you resolved it? It will help others as well.
> 
> Thanks!



> @qimoto Is your issue resolved by the comments above?



> Hi @qimoto, A couple of things I can suggest in "avoiding" discrete graphics card and use integrated graphics (if your processor has Intel® Processor Graphics):
> 
> 1. Make sure you have Internal/Integrated Graphics enabled in the BIOS. Once BIOS menu, the setting should be under **Chipset > Internal Graphics > [Enabled]** or similar.
> 2. Follow required steps to enable the toolkit components to use the processor graphics (GPU ). Find the steps for Linux [here](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html#additional-GPU-steps).
> 
> After performing these steps you should be able to run the OpenVINO* demo scripts just fine using the GPU plugin. You shouldn't have to remove the discrete graphics, both discrete and integrated graphics should run. I hope this works, let me know if it does not.
> 
> **If running on Windows** instead of step no. 2 follow [these steps](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_windows.html#Install-GPU). You may have to update my graphics driver with **Device Manager > Display adapters > Intel(R) HD Graphics > Search automatically for updated driver software**.
> 
> Best Regards, Luis



> I have NVIDIA's GPU on my computer, when I use openvino with command -d GPU, I got the error: No OpenCL device found which would match provided configuration: GeForce GTX 560 Ti: invalid vendor type
> 
> so how can I specify the intel's integrated graphics as my GPU, not nvidia's。。。



This repo may help u... 
https://github.com/bharath5673/OpenVINO
