### ISSUE TITLE
Is there any Custom CPU/GPU Kernel(Operation) example or tutorial?

### ISSUE THREAD

**Issue by dedoogong** [openvinotoolkit/openvino#4394]
I found a good git repo as a starting point : https://github.com/david-drew/OpenVINO-Custom-Layers, but it's little bit outdated and this example doesn't work for OpenVino 2021. Also there are nice youtube tutorials like https://www.youtube.com/watch?v=UrfWgFKjaPc&ab_channel=IntelSoftware, but it also handles 2019 version. For example, the tutorial says there is cldnn_global_custom_kernels folder in openvino installation, but there is no such a folder in 2021 version.
Also it says there is "deployment_tools\tools\extension_generator\extgen.py" generator, but no, there is no such a file in 2021 version. 

Do I need to implment not only cpp, cl, xml(I think those are CPU/GPU IE Extension), but also additional fron/middle/backend MO Extensions and too??

In my understand, I need to implement 6~7 codes by myself : 
my_custom_op.cpp(CPU IE extension), my_custom_op.xml(GPU IE extension), my_custom_op.cl(GPU IE extension), front/my_custom_op.py(MO extension), mid/my_custom_op.py(MO extension), back/my_custom_op.py(MO extension) op/front/my_custom_op.py(MO extension)

I found there are some custom GPU op(like Yolov3's region/reorg) files in Openvino installation, but there is no related running binary example or ReadMe file. I feel really hard how or where to start. 

I'm trying to implement several custom operations to convert TF models on Openvino like tf.meshgrid, tf.extract_patches, tf.clip_by_value,  tf.l2_normalize, tf.divide_no_nan,... so on. 

I already read almost all of openvino docs related to custom layers but it's too extensive and complicated to understand the whole workflow comprehensively. 

Please give me any hint. 

Thank you!

**Comment by ilyachur** [comment]
Hi @dedoogong ,

You can find information how to create custom operation in the OpenVINO documentation:

- [MO part](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html)
- [IE Part](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Extensibility_DG_Intro.html)

**Comment by ts-accessio** [comment]
The GPU part in the documentation seems to be outdated. E.g. there is no "cldnn_global_custom_kernels/cldnn_global_custom_kernels.xml" as stated in the documentation. I implemented an extension according to the guide ([https://github.com/accessio-gmbh/arivo_custom_openvino_layers](https://github.com/accessio-gmbh/arivo_custom_openvino_layers)) however there are some problems:
 * the CPU extension has to be loaded, even if running on GPU (otherwise the model cannot be loaded)
 * the benchmark_app does not work on GPU as you cannot load CPU and GPU extensions simultaneously (needed because of problem above)
 * getPerformanceCounts does not work correctly on GPU (says layer was optimized out) 

So either something in the documentation is missing or GPU extensions do not work correctly in version 2021.2 (or I am really stupid and missed something)

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
