### ISSUE TITLE
Effect issues

### ISSUE THREAD

**Issue by konioy** [openvinotoolkit/openvino#4730]
I changed the mxnet model to onnx and, under python, tested the mxnet model and the onnx model to get the same results. But when I ran the onnx model in the openvino c++ environment, I got a different result. 
I also tried xml and bin files, and the result was different from the mxnet model.
Is this reasonable and could you give some advice?
openvino version: 2021.2

**Comment by Iffa-Meah** [comment]
I did notice that the result of inferencing between a native model (onnx,etc) and converted to IR model is different.
Basically the IR version would have better latency and throughput since we used the model optimizer because the model is optimized.

[This](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html) would helps you to understand, check out the video too.

**Comment by konioy** [comment]
Thank you very much for your reply, I understand your answer.
But even native onnx models use onnxruntime under python and the result of inferencing from using openvino are different.
Is this reasonable?

**Comment by Iffa-Meah** [comment]
They are both inference engines(onnxruntime,OpenVINO)  but they are built differently. I believe it would differ as OpenVINO is having its own CNN architecture.

**Comment by konioy** [comment]
What do you mean is that because the cnn architecture is different, the result of inferencing will be different between onnxruntime(python) and openvino(load the onnx model directly with openvino)?

**Comment by Iffa-Meah** [comment]
If you did your own custom opencv inferencing in both cases (onnxruntime and [OpenVINO Inferencing with OpenCV](https://www.youtube.com/watch?v=Nmf-aHeRFq4)), and they both run on the same device, under the same circumstances, then they should have approximately the same result.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
