### ISSUE TITLE
About NMS or TopK op  from MXnet to Openvino

### ISSUE THREAD

**Issue by Aktcob** [openvinotoolkit/openvino#531]
From the newest version doc, now openvino does not support NMS or TopK op in Mxnet. Is there any plan to add these important ops?

**Comment by lazarevevgeny** [comment]
@Aktcob, the support for operation is primarily determined by the model support requests the OpenVINO team receives. As of now there are no nearest future plans to support NMS since the MxNet version of the operation significantly differs from other frameworks. But support for the TopK could be done on the Model Optimizer side since since the MxNet TopK is quite the same as the one that is already implemented in OpenVINO. 

Could you share the model which you are interested in so we can take a look what version of NMS is used in it?

**Comment by Aktcob** [comment]
Thank u so much for reply. Now I am using the code from gluoncv(mxnet) official code.(URL: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/yolo/yolo3.py). The NMS is on line 410. (op in mxnet: F.contrib.box_nms)
