### ISSUE TITLE
Where can I find the training framework with the training model road-segmentation-adas-0001?

### ISSUE THREAD

**Issue by uglymie** [openvinotoolkit/openvino#5382]
I want to train a road-segmentation model with my own data, I see that openvino has a pre-trained model: road-segmentation-adas-0001, so I want to ask Where can I find the training framework with the training model road-segmentation-adas-0001?

**Comment by ilya-lavrenov** [comment]
CC @snosov1

**Comment by Iffa-Meah** [comment]
Hi,

The model road-segmentation-adas-0001 has this demos supported on the model: [Segmentation Demo](https://docs.openvinotoolkit.org/latest/omz_demos_segmentation_demo_cpp.html).

You may try it out and perhaps make it as a template for your custom implementation.

That model can be downloaded using [OpenVINO model downloader](https://docs.openvinotoolkit.org/latest/omz_tools_downloader.html)

to list out all available models: python downloader.py --print_all
check your desired model's name and download: python downloader.py --name <model's name> -o <path you want to save your model to>

**Comment by Iffa-Meah** [comment]
In addition to my previous reply, this pre-trained model is only for inferencing instead of re-training since it is not open-sourced.

All available details can be found here: https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/road-segmentation-adas-0001/description/road-segmentation-adas-0001.md

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
