### ISSUE TITLE
[Bug] the inference time of the same model fluctuates a lot

### ISSUE THREAD

**Issue by cherrysnower** [openvinotoolkit/openvino#5583]
##### System information (version)

- OpenVINO => 2021.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- Problem classification: Perfermance
- Model name: fsrcnn.xml
- device: GPU Intel（R）UHD Graphics 630

##### Detailed description

I try to do inference on different test images and find that the inference time fluctuates. Then I do like this 
```
   for i in range(1000):
        start2 = datetime.now()
        res = exec_net.infer(inputs={input_blob: lr})
        end2 = datetime.now()
        print("the inference time of openvino is %6f ms" %((end2 - start2).microseconds/1000), flush=True, end=',')
```
Then I repeat inference in a small loop 1000 times for the same test image and find that the inference time fluctuates a lot, is this rersult normal?
the inference time of openvino is 15.610000 ms
the inference time of openvino is 31.257000 ms
the inference time of openvino is 15.624000 ms
the inference time of openvino is 15.626000 ms
the inference time of openvino is 15.627000 ms
the inference time of openvino is 16.885000 ms
the inference time of openvino is 19.045000 ms
the inference time of openvino is 9.246000 ms
the inference time of openvino is 15.664000 ms
the inference time of openvino is 15.650000 ms
the inference time of openvino is 15.622000 ms
the inference time of openvino is 15.609000 ms
the inference time of openvino is 15.626000 ms
the inference time of openvino is 15.623000 ms
the inference time of openvino is 31.250000 ms
the inference time of openvino is 15.627000 ms
the inference time of openvino is 17.522000 ms
the inference time of openvino is 10.673000 ms
the inference time of openvino is 15.634000 ms
the inference time of openvino is 16.840000 ms
the inference time of openvino is 15.657000 ms
the inference time of openvino is 15.597000 ms
the inference time of openvino is 15.631000 ms
the inference time of openvino is 15.671000 ms

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [ ] There is reproducer code and related data files: images, videos, models, etc.

**Comment by Iffa-Meah** [comment]
The fluctuation is expected and actually had been recorded.

Previously, there is a customer that reported the fps fluctuates over multiple runs and the issue was replicated using below configurations:


a) Setup: benchmark_app and squeezenet

b) Number of inference requests: 1, 2, 4, 8, 16, 32, 64, 128

c) Number of runs for each: 32 (eg: 32 times you will run the benchmark_app with 32 inference requests and collect the logs)


The result depicts that fluctuations are to be expected for 8 to 24 concurrent inference requests. 
Before 8 there is always a completely free device to run inference. 
After 24 there are always 3 per device and each MYX is loaded with 2 in-flight and 1 on data transfer. 
In between some tasks will get the free device and some will get a device where something is already running. 
So performance will fluctuate depending on minor timing differences between runs.

Once again this is not a bug but a property of the platform.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
