### ISSUE TITLE
[Bug]Some problems about benchmark__app.py 

### ISSUE THREAD

**Issue by NeekHua** [openvinotoolkit/openvino#5601]
I‘m testing openvino quantization result.Some information have problems. 

DOS parameter is:
(openvino) C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\tools\benchmark_tool>python benchmark_app.py -m gaze-estimation-adas-8.xml -d CPU -api async -i J:\data_work\face\total_images\0001_Color.bmp -progress true -b 1

portion output information
[Step 11/11] Dumping statistics report
Count:      181728 iterations
Duration:   60001.53 ms
Latency:    1.25 ms
Throughput: 3028.72 FPS

What does Latency and Throughout stand for?

**Comment by NeekHua** [comment]
And I have another problem.why int8 model data type is float16.
For example face-detection-retail-0004\FP16-INT8\face-detection-retail-0004.xml
![image](https://user-images.githubusercontent.com/32665609/117941654-e9fcca80-b33c-11eb-995f-13569bc175d8.png)

**Comment by Iffa-Meah** [comment]
In [Performance Benchmark Application](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html), Performance can be measured for two inference modes: synchronous (latency-oriented) and asynchronous (throughput-oriented).

For Synchronous , during the execution, the application collects two types of metrics:

1.Latency for each infer request executed with Infer method
2.Duration of all executions

Reported latency value is calculated as mean value of all collected latencies.
Reported throughput value is a derivative from reported latency and additionally depends on batch size.

Meanwhile for Asynchronous, the primary metric is throughput in frames per second (FPS).
A number of executions are defined by one of the two values:

1.Number of iterations defined with the -niter command-line argument
2.Time duration specified with the -t command-line argument
3. Both of them (execution will continue until both conditions are met)
4. Predefined duration if -niter and -t are not specified. Predefined duration value depends on device.

The application measures all infer requests executions and reports the throughput metric based on batch size and total execution duration.

In short, latency in this case, means the delay that happens when inferencing.
The throughput means the frame rate (fps), which is the speed images are inferred. ( 3028.72 FPS means that each seconds 3028.72 images are inferred)--Please note that videos are series of pictures (You might want to study the concept of fps if you want to know further)

Generaly, there are precision of FP32, FP16(usually used for NCS2) and INT8.
Quantization of a model using POT, can be done using a full precision IR (FP32) which would produce an INT8 precision.
Same case for the half precision (FP16).

You are getting FP16 precision in your quantized model probably because the  precisions is set to FP16-INT8.

You need to study[ this documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Int8Inference.html) to know why.

**Comment by NeekHua** [comment]
Thanks your reply.Through your explain,I've got it my questions.
