### ISSUE TITLE
[Bug] "-d MULTI:CPU, GPU" will load to CPU only

### ISSUE THREAD

**Issue by coneypo** [openvinotoolkit/openvino#5631]
When running benchmark with device: `-d MULTI:CPU,GPU`, no issue there;
But if I run `-d MULIT:CPU, GPU` (an extra space between CPU and GPU), no warning or error, and load to CPU only;

If it is an issue from UX/DX side?

In `inference-engine/samples/benchmark_app/main.cpp`

` // Parse devices
  auto devices = parseDevices(device_name);`

"device_name" is "MULTI:CPU," there if  `-d MULIT:CPU, GPU`;

**Comment by Iffa-Meah** [comment]
Hi,

That's most probably due to the syntax created for the Multi-Device Plugin.
As you can see in the [official documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_MULTI.html), they should be used without a single/double space in between.

The proof is, you didn't get the correct output when executing the code with space.

let's take this as example, let's say, In c programming you are trying to read the character "a", which suppose to be at the position of c[0], but due to a space inserted at the beginning of the array, the program printed the space instead of character "a"
char s[5] = " abcde"
printf("%c",c[0]);

**Comment by ilya-lavrenov** [comment]
CC @nkogteva

**Comment by coneypo** [comment]
> Hi,
> 
> That's most probably due to the syntax created for the Multi-Device Plugin.
> As you can see in the [official documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_MULTI.html), they should be used without a single/double space in between.
> 
> The proof is, you didn't get the correct output when executing the code with space.
> 
> let's take this as example, let's say, In c programming you are trying to read the character "a", which suppose to be at the position of s[0], but due to a space inserted at the beginning of the array, the program printed the space instead of character "a"
> char s[5] = " abcde"
> printf("%c",s[0]);
> 
> The nature of this Multi-Device execution is, if something is wrong with the second device (which in your case GPU) eg: unable to read the device or etc, it will revert to the first priority device which in your case is CPU.

Thanks for you reply, agree with you from the implementation perspective, but maybe an issue from UX/DX perspective;
