### ISSUE TITLE
[Bug]memory leaks when loading network to plugin

### ISSUE THREAD

**Issue by robbiewongBD** [openvinotoolkit/openvino#6092]
##### System information (version)
- OpenVINO =openvino_2021.3.394
- Operating System / Platform = Windows 64 Bit
- Compiler = Visual Studio 2017
- Problem classification: memory leaks when loading network to plugin
##### Detailed description
the code:
auto executable_network = core.LoadNetwork(network, "CPU") 
cause memory leaks

previous discussion can be found here:
https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Bug-report-Memory-leak-in-CPU-plugin/m-p/1149789
the leaks also happen in the latest version.

**Comment by Iffa-Meah** [comment]
Hi,

Some issues related to memory leaks were fixed in the latest 2021.3 Github master branch.
However, this memory leaks issues is quite vast and we require more info regarding your issue (it might or might not be the same as the one that been fixed)

If possible, could you provide detailed steps and required files(if any) so that we could dig further?

**Comment by dkurt** [comment]
Issue does not have a reproducer. The link refers to outdated problem which has been already fixed.
