### ISSUE TITLE
question about install accuracy_checker on windows10(openvino2021.1.110)

### ISSUE THREAD

**Issue by ahbyqq** [openvinotoolkit/openvino#6300]
when i install accuracy_checker with run "python setup.py install", there is a eror: "error: [Errno 2] No such file or directory: 'build\\bdist.win-amd64\\egg\\accuracy_checker\\evaluators\\custom_evaluators\\__pycache__\\sequential_action_recognition_evaluator.cpython-36.pyc.2199014545328'", 
how can i solve it?

![image](https://user-images.githubusercontent.com/38413644/122918945-43bbd000-d392-11eb-98ed-165fd3a97c67.png)

**Comment by ilya-lavrenov** [comment]
CC @eaidova @AlexKoff88

**Comment by eaidova** [comment]
#### Troubleshooting during installation

When previous version of the tool already installed in the environment, in some cases, it can broke new installation.
If you see the error about directory/file not found, please try remove manually old tool version from your environment or install the tool with following command (in accuracy checker directory, instead of setup.py install):
```bash
pip install --upgrade --force-reinstall .
```

source: [Accuracy Checker documentation](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/accuracy_checker/README.md#troubleshooting-during-installation)

**Comment by Iffa-Meah** [comment]
Hi,

if there are no further inquiries/help required, we shall proceed to the case closure.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by EricLukMovidius** [comment]
Sorry for asking a superficial question here.  I am looking to install the accuracy check too.  I have the virtual environment enabled and openvino version is 2020.1.023.  The page I am looking at for installing the accuracy check tool is referred to, https://docs.openvino.ai/cn/2021.4/omz_tools_accuracy_checker.html
As it goes on to the installation of the tool, it says, "
Install accuracy checker
If all prerequisite are installed, then you are ready to install accuracy checker:
python3 setup.py install
"
I presume 'setup.py' is specific to the accuracy check installation.  Where can this be downloaded? 

Thanks,
Eric.
