### ISSUE TITLE
Unable to load network for a trained YoloV4 model (Argument element types are inconsistent)

### ISSUE THREAD

**Issue by Kshitij-Khode** [openvinotoolkit/openvino#6334]
## System information (version)
- Docker Image Used: openvino/ubuntu18_dev:2021.3 (https://hub.docker.com/r/openvino/ubuntu18_dev)

- OpenVINO => 2021.3
- Operating System / Platform => Ubuntu 18.04 x64 
- Compiler => GCC 7.5.0
- Problem classification: Model Conversion
- Framework: Model trained in Darknet, Converted to TensorFlow using https://github.com/theAIGuysCode/tensorflow-yolov4-tflite and then converted to OpenVINO IR using mo_tf.py
- Model name: yolov4

## Detailed description

When reading the model (attached as *yolov4_custom_best.xml*) for inferencing I get the following error
```
Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 507, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_yolov3_async.py", line 356, in main
    num_requests=args.num_infer_requests)
  File "ie_api.pyx", line 336, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 345, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Check 'element::Type::merge(inputs_et, inputs_et, get_input_element_type(i))' failed at core/src/op/concat.cpp:62:
While validating node 'v0::Concat StatefulPartitionedCall/functional_1/tf_op_layer_Shape_10/Shape_10 (DynDim/Gather_10626[0]:i64{1}, ConstDim/Constant_10627[0]:i32{1}) -> (i32{2})' with friendly_name 'StatefulPartitionedCall/functional_1/tf_op_layer_Shape_10/Shape_10':
```

## Steps to reproduce

- I trained a yolov4 darknet model (attached as yolov4_custom_best.weight) on a custom dataset. This model is a 2 class object detector with the configs provided in *yolov4_custom.cfg*, *obj.data* and *obj.names*.
- This yolov4 darknet model was converted to a Tensorflow 2.3.0rc0 SavedModel format using save_model.py provided in https://github.com/theAIGuysCode/tensorflow-yolov4-tflite. The line in `__C.YOLO.CLASSES = "./data/yolov4_custom_best.names"` in `core/config.py` was changed to support the custom darknet yolov4 model.
- The SavedModel was then converted to OpenVINO IR via the command: `python3 mo_tf.py --saved_model_dir  $saved_model_dir --transformations_config ./yolov4.json --reverse_input_channels --batch 1`. yolov4.json is attached with this issue ticket.
- The converted OpenVINO IR was then attempted to be read via `openvino.inference_engine.ie_api.IECore.load_network`. However at this point OpenVINO spits out the following error
```
Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 507, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_yolov3_async.py", line 356, in main
    num_requests=args.num_infer_requests)
  File "ie_api.pyx", line 336, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 345, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Check 'element::Type::merge(inputs_et, inputs_et, get_input_element_type(i))' failed at core/src/op/concat.cpp:62:
While validating node 'v0::Concat StatefulPartitionedCall/functional_1/tf_op_layer_Shape_10/Shape_10 (DynDim/Gather_10626[0]:i64{1}, ConstDim/Constant_10627[0]:i32{1}) -> (i32{2})' with friendly_name 'StatefulPartitionedCall/functional_1/tf_op_layer_Shape_10/Shape_10':
```

I have tried fixes using the --input parameter in the form of `--input "DynDim/Gather_10626:0[1]{i32}"` however, that hasn't fixed the issue.

The files mentioned above can be found in this zip file: https://drive.google.com/file/d/1icEReAL-sbPEyjcJ1GZZEBlXreyypdw5/view?usp=sharing

**Comment by Iffa-Meah** [comment]
Hi,

I think that happen because you didn't freeze your model before converting it to IR.
You may refer [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html) for the info.

If you look at the supported topology, you will find the officially supported [yolov4 repo](https://github.com/Ma-Dan/keras-yolo4)

**Comment by Kshitij-Khode** [comment]
I thought mo_tf.py supports TF 2.0 Saved Model format as input. That's why I used the `python3 mo_tf.py --saved_model_dir $saved_model_dir --transformations_config ./yolov4.json --reverse_input_channels --batch 1` to do the conversion.

However, I froze the model based on your suggestion, using the script freezeModel.py and I ran into the following problem
```
Traceback (most recent call last):
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 135, in partial_infer
    node.infer(node)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 66, in tf_native_tf_node_infer
    tf_subgraph_infer(tmp_node)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 141, in tf_subgraph_infer
    all_constants, output_tensors = get_subgraph_output_tensors(node)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/front/tf/partial_infer/tf.py", line 121, in get_subgraph_output_tensors
    tf_v1.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from conv2d/kernel_port_0_ie_placeholder:0 incompatible with expected resource.
```

When I looked up the dimension of the output layer via saved_model_cli (from TF 2.0), I get the following print
```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 608, 608, 3)
        name: serving_default_input_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['tf_op_layer_concat_18'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, -1)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
```

Which suggests that the output tensor has (-1, -1, -1)  size, which makes sense since # detections vary for yolov4.

Is there something that I'm doing wrong? freezeModel.py alongside the frozen model (inference_graph.pb) can be found here: https://drive.google.com/file/d/1j-X6SAvmku13U-VLWpvxovBtWYZGyqif/view?usp=sharing

**Comment by Iffa-Meah** [comment]
These are the steps that I'm confident would work since I had done it myself.
1. label file (coco.names/labels that fit your tasks)
2. weight file: yolov4.weights
3. convert those into inference_graph.pb 
4. use OpenVINO model optimizer to convert the inference_graph.pb into IR, you will need yolov4.json file
5. Now you can use the model (in IR form) for inferencing purpose.


You may refer to my attachments
![freeze_yolov4](https://user-images.githubusercontent.com/79643476/124289678-2bfbfd00-db85-11eb-85ea-0d10438e8ee2.png)
![convertyolov4_toIR](https://user-images.githubusercontent.com/79643476/124289719-34543800-db85-11eb-985e-d574fa5ee150.png)
![yolov4IR_objectdetection](https://user-images.githubusercontent.com/79643476/124289767-40d89080-db85-11eb-8bb5-c0a041e7c5b3.png)

**Comment by Kshitij-Khode** [comment]
That's the exact procedure I've used.

Could you share your yolov4.json? Also, if possible could you try converting/reproducing the issue on your side? I have provided my label/data, weights and yolov4.json file here: https://drive.google.com/file/d/1icEReAL-sbPEyjcJ1GZZEBlXreyypdw5/view?usp=sharing

Maybe you might be able to reproduce the same issue I'm running into. I'm not using the default label/data and weights because I'm using a model that I custom trained.

**Comment by TNTWEN** [comment]
@Kshitij-Khode 
Welcome to use https://github.com/TNTWEN/OpenVINO-YOLOV4
what Iffa-Meah uses may be this repos

**Comment by Iffa-Meah** [comment]
@Kshitij-Khode,
I don't see any issue in converting your model.
You just didn't freeze them properly.
Note: freezing and converting to IR are two different things.
Freezing is still within Tensorflow scope(.pb), meanwhile, model Optimizer is in OpenVINO scope (IR files:bin,xml)

@TNTWEN suggest a great idea. His conversion script is good and working. You may try his script.

Refer to my attachment. I used all the files that you gave (yolov4.json, yolov4_custom_best.weights, yolov4_custom.cfg)

I'm able to get IR and do inferencing to them. Your trained model is not suitable to be run with OpenVINO object detection due to your trained data (probably insufficient or etc)
![modelTrained_notSuitable_objDetection](https://user-images.githubusercontent.com/79643476/124417193-2d971200-dd8b-11eb-98a8-ecad64a09c44.png)
 but it works with Benchmark Apps. So you should be good to go since the basic of the model is proven to work.

![frozen](https://user-images.githubusercontent.com/79643476/124416927-a5b10800-dd8a-11eb-8e62-c814711bd7c6.png)
![IR](https://user-images.githubusercontent.com/79643476/124416940-acd81600-dd8a-11eb-8740-f51bb7372d98.png)
![inference_benchmarkApp](https://user-images.githubusercontent.com/79643476/124416957-b5c8e780-dd8a-11eb-9f23-37b7fa5a4714.png)

**Comment by Kshitij-Khode** [comment]
@Iffa-Meah Got it. I understand that freezing of the TF model needs to be done before converting to IR and that those 2 are different processes.

The first thing I tried before writing my own scripts and posting the issue was use @TNTWEN repo. However, when I use his script and then convert model to IR, my output blob has the shape `(1, 10647, 7)`. You can see the same error show up in your object_detection_demo.exe output as well.

I believe the output blob shape should be (B,N*6,Cx,Cy), right?. **NOTE:** It should also not be (B,N*85,Cx,Cy), since my model only detects a single class. This can checked by loading the model via `net = ie.read_network( .. )` and checking net.outputs['output_boxes'].shape. Is this a bug or is there something wrong I'm doing in handling the output blob?

**Comment by Iffa-Meah** [comment]
You need to make sure your IR has the correct shape then, using [--input_shape INPUT_SHAPE prameter](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html)
I didn't specify this in the first place because I just need to ensure your model is able to be inferred or not only which the Benchmark App is enough to fulfill this purpose.

However, if you are talking about object detection inferencing, this sample has more in-depth application, one of it as you mentioned, the shape. You will need to use the parameter as I mentioned above.

You need to refer to this official documentation where it has the step by step of [common workflow for using Inference Engine API](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html)


check your data format too. For testing purposes I just assume them as --data_format NHWC.

**Comment by Kshitij-Khode** [comment]
I tried forcibly providing the input_shape for the model i.e. (1,608,608,3), but I'm getting the same error. `python3 mo.py --input_model /OpenVINO-YOLOV4/frozen_darknet_yolov4_model.pb --transformations_config /OpenVINO-YOLOV4/yolov4.json --reverse_input_channels --input_shape [1,608,608,3]`

I even tried reshaping the output blob to the correct expected shape according to the (B,N * 7,Cx,Cy) shape referred in https://docs.openvinotoolkit.org/2021.2/omz_models_public_yolo_v4_tf_yolo_v4_tf.html, however, the math just doesn't work out when reshaping [1, 22743, 7] into [1, 5 * 7, X, X].

Could you try to convert any 2 class yolov4 darknet model and infer the bounding boxes correctly? You can use my model or any model that you might prefer. I'm able to convert the original 80 class model just fine. It's my custom 2 class model that's causing trouble.

**Comment by Kshitij-Khode** [comment]
@eizamaliev (Zamaliev, Eduard) from the open_model_zoo repo team and figured out the problem is with the inferencing library script: yolo.py, which has classes hardcoded to 80. He'll push out the fix to support variable # of class in open_model_zoo repo. Closing this issue now.
