### ISSUE TITLE
[Bug] How to utilize CPU 100%?

### ISSUE THREAD

**Issue by dedoogong** [openvinotoolkit/openvino#6372]
##### System information (version) 
- OpenVINO => 2021.3
- Operating System / Platform => ubuntu 18.04
- Compiler => GCC 7.5.0
- Problem classification: CPU computation resource utilize
- Framework: Pytorch  
- Model name: R2D2
--> Hello, I've run my own model with openvino 2021 R3 on some servers like T4, V100, so on.
Weirdly I used same docker container but it shows quite different inference time ( some server shows 600ms, another one shows 360ms) and I found, the slower one utilize CPU just 40~70% otherwise, another one does 100% CPU.  
I wonder why this difference is made. 

Faster one shows log like
InferenceEngine:        API version ......... 2.1
        Build ........... 2021.3.0-2787-60059f2c755-releases/2021/3

Available target devices:  CPU
[ INFO ] Parsing input parameters
[ INFO ] Loading Inference Engine
[ INFO ] Device info:
[ INFO ]        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2021.3.0-2787-60059f2c755-releases/2021/3
....

Slower one shows like 
InferenceEngine:        API version ......... 2.1
        Build ........... custom_HEAD_18e83a217702c650280c6abfc43f3285a3aadb61

Available target devices:  CPU  GNA
[ INFO ] Parsing input parameters
[ INFO ] Loading Inference Engine
[ INFO ] Device info:
[ INFO ]        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... custom_HEAD_18e83a217702c650280c6abfc43f3285a3aadb61

Do you think openvino build version makes this speed gap?

Please help me. 

I hope you to tell me how to list up, all related libraries version like mkl, mkldnn, opencv, tbb, so on. 

Thank you!

**Comment by dedoogong** [comment]
oh, even when I tried to test again, it shows 30~40% cpu usage on V100, and it's still faster x2 times then T4. T4 and V100 has almost same CPU and clock speed. I use only 4 cores by setting cpu-sets option when running docker.

**Comment by Iffa-Meah** [comment]
Hi,

Sometimes there could be background programs that run and thus consuming some of the cpu processing power. (eg software updates, VPN, servers).

I think it's not possible to have 100% the same performance even they have the same CPU.

Similar to having two DELLs laptops with exactly the same specs, the performance might still be different since they might have different software running on them (unless you ensure they have the same exact software inside) and it might also be a hardware issue.

Besides, there is a power-management technique known as demand-based switching (DBS) where it dynamically modify the voltage of the CPU and hence the processor clock  speed, based on CPU load

Try to investigate what has been using CPU processing power and close/uninstall unnecessary apps

Generally running the OpenVINO inference engine with -d CPU parameter is enough to ensure CPU is utilized.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
