### ISSUE TITLE
c++ API: input_info->setLayout() seems not work

### ISSUE THREAD

**Issue by cosmos1982** [openvinotoolkit/openvino#6471]
### Description
In hello_classification C++ sample: main.cpp Line177:
`input_info->setLayout(Layout::NHWC);`
Either using input_info->setLayout(Layout:NHWC) or input_info->setLayout(Layout::NCHW), the detecton results are the same and both correct. 
But since the input blob is NHWC,  the result is supposed to be wrong if we did not change the input layout to NHWC.

### How to reproduce
Run following cmd, change the model path and image path with yours:
` ./hello_classification ~/workspace/tmp/public/efficientnet-b5-pytorch/FP32/efficientnet-b5-pytorch.xml ~/workspace/dataset/imagenet-10/n0153282900000005.jpg CPU`
Then  modify main.cpp L177 with:
`input_info->setLayout(Layout::NCHW);   //wrong layout format`
After rebuild and run, the detection result is still the same even I specify the wrong layout format.

I am not sure whether this is a bug or 'setLayout' just has some tricks like auto-conversion?
But if it does has some tricks, I think it would be better to describe clearly in API doc. Now I can't find any descriptions about this problem. Thanks!

**Comment by jgespino** [comment]
Hi @cosmos1982 

I am also seeing the same behavior as you described which leads me to believe the inference engine automatically does the conversion. Let me reach out  to the development team and confirm this is the case.

Regards,
Jesus

Ref. 53713

**Comment by ilya-lavrenov** [comment]
If layout set via `setlayout` and actual layout of passed blob via `SetBlob` are different, conversion happens

**Comment by cosmos1982** [comment]
@ilya-lavrenov , @jgespino , thanks for your reply.   If conversion will happen automatically , I am wondering what's the design purpose of setLayout(). Maybe you can consider removing this c++ API which does not exist in Python bindings.

**Comment by ilya-lavrenov** [comment]
@cosmos1982 

Generally, user should pass blob in the layout which is set by `cnnnetwork->getInputsInfo()->...->setLayout()`, but from the API level user can pass blobs of different layout to `SetBlob` (after the network is compiled). 
So, in this case conversion happens automatically. 

`SetLayout` is needed for cases when for e.g. network has input in `fp32` format, while user want to pass `u8` input. In this case user gives Inference Engine knowledge about his desire about `u8` input via `setlayout`. 
In this case we can insert `Convert` layer to the network and merge later it with some other layers, e.g. first convolution can accept `u8` instead of `fp32` in this case.
For discrete devices like dGPU it allows also to optimize memory transfers because for `u8` we need to transfer 4x less memory with compare to `f32`

So, `setLayout` is a hint from user that he wants to pass data in a different format (different from actual network expects)

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
