### ISSUE TITLE
misalignments between openvino and onnxruntime 

### ISSUE THREAD

**Issue by tilaba** [openvinotoolkit/openvino#7218]
results of  openvino and onnxruntime  are misaligned。
![image](https://user-images.githubusercontent.com/31062802/130589035-e9e3c885-38d6-4fd5-8f16-f27948eeb674.png)
![image](https://user-images.githubusercontent.com/31062802/130589161-f8ac7079-3960-4b3c-adbe-5d15fc970051.png)

**Comment by alalek** [comment]
We see 4 equal floating point digits here. These results doesn't have dramatical difference.
There is no bit-exact guarantee in floating-point computation algorithms (between order of operations, or even between platforms / GPUs / accelerators)
IMHO, tolerance check (and its metrics) should be revised.
In general it is caused by computational approximation errors. Also there are no "gold values", because even onnxruntime has the same problems.

BTW, Used DL models should be stable (reliable). In general this means:
- input noise is eliminated by DL model (all cameras sensors provide some noise)
- computation approximation errors should not be amplified (e.g, input difference on several [ULPs](https://en.wikipedia.org/wiki/Unit_in_the_last_place) should not provide dramatical results difference)
