### ISSUE TITLE
[Bug] compile tool gets stuck - MYRIAD blob-conversion

### ISSUE THREAD

**Issue by Orchidaceae** [openvinotoolkit/openvino#7681]
##### System information (version)

- OpenVINO=> 2021.4
- Operating System / Platform => Ubuntu 20.04.3 LTS 64 Bit
- Problem classification => compile tool .blob conversion
- Model name: [EfficientDet d0](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)

##### Detailed description

So I have converted the above mentioned TensorFlow model to IR using the model optimizer without any apparent issues. But when I then try to compile it to .blob-format for the MYRIAD using the compile tool I cannot get it to work. I start the compile tool but it never converges and outputs a .blob file, and I have tried running the process for more than 2 hours. Is the conversion supposed to take that long? I don't get any command line output from the compile tool but I suspect that it may potentially be stuck in some kind of loop.

##### Steps to reproduce

Download the EfficientDet d0 source files (including the IR .xml and .bin in question) from [here](https://github.com/Orchidaceae/EfficientDet_d0-model)

Run the following in bash
```bash
# set up variables for OpenVINO compile tool
~/openvino_2021.4.689/bin/setupvars.sh

# move to directory where you want the blob-file
cd ~/efficientdet_d0_coco17_tpu-32/

# run compile tool to convert saved_model to blob format
~/openvino_2021.4.689/deployment_tools/tools/compile_tool/compile_tool -m saved_model.xml -ip U8 -d MYRIAD -VPU_NUMBER_OF_SHAVES 4 -VPU_NUMBER_OF_CMX_SLICES 4
```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [x] There is reproducer code and related data files: images, videos, models, etc.

**Comment by zulkifli-halim** [comment]
Hello @Orchidaceae. I tried the compile_tool on other models, and it works fine. I replicate your issue and I get killed as the output. On another occasion, I get bad allocation as the output.

I also tried myriad_compile and it still running for almost 5 hours and haven’t completed until now. It looks like this issue might be because of the EfficinetDet complex model structure or the memory allocation issue. We are currently looking into this matter.

**Comment by Orchidaceae** [comment]
@zulkifli-halim That is also my experience. I tried converting the ssd mobileNet v2 coco, also from the TF2 detection model zoo, with the same process as for I used for EfficientDet d0 without any issues.

**Comment by avitial** [comment]
@Orchidaceae, we can reproduce the issue and it's not clear whether this model from TF2 Zoo is supported by Myriad plugin or not, sounds like it may not. We are checking with development team for more information, we will share more details soon.

I'd suggest to check the [efficientdet-d0-tf ](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/efficientdet-d0-tf) model available in the OMZ see if that is useful to you.

Ref: 66687

**Comment by avitial** [comment]
@Orchidaceae apologies for the delay in my response, the long execution of this model compilation is associated with a large amount of data that comes to the ajustDataLayout pass. Thus, we do not have a hang on compile tool rather we have a long execution. 

The EfficientDet-d0 network provided originally is not supported as I previously suspected on Myriad, but version in OpenVINO's OMZ is supported that's why [EfficientDet-do-tf](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/efficientdet-d0-tf) model works. I'd recommend to check and use efficientdet-d0-tf model available in the OMZ if you wish to use efficiendet-d0 with MYRIAD/compile tool.

Best Regards,
Luis

**Comment by avitial** [comment]
Closing issue, feel free to reopen to ask any additional questions related to this topic.
