### ISSUE TITLE
Failed to convert onnx model to openvino

### ISSUE THREAD

**Issue by MikoyChinese** [openvinotoolkit/openvino#821]
Hi,

I have a model from pytorch, and I use torch.onnx.export to convert it to onnx model. Then I try to convert it to openvino by command `python3 mo.py --input_model /root/workspace/models/DFA_model.onnx`, but I got a error:

```bash
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/root/workspace/models/DFA_model.onnx
	- Path for generated IR: 	/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/.
	- IR output name: 	DFA_model
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
ONNX specific parameters:
Model Optimizer version: 	
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.load.onnx.loader.ONNXLoader'>): Unexpected exception happened during extracting attributes for node Constant_22.
```

So how can I solve this problem? Thx. :)

**Comment by avitial** [comment]
Hi @MikoyChinese , not sure what is the issue here but it could be multiple things.
- Operation/layer produced by ONNX when you convert the PyTorch model may not be supported. Take a look at [Caffe* Supported Layers](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx_supported_operators). 
- PyTorch model is not a supported PyTorch model via ONNX conversion as shown in [guide](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#supported_pytorch_models_via_onnx_conversion). 

Some of this or a combination of both could be the underlying cause why the Model Optimizer is facing trouble at such node. 

~Luis

**Comment by MikoyChinese** [comment]
I found the reason is that the current release openvino does not support pytorch's `opset_version=11` which supports the opearation of `bilinear`. So I have to change it to `nearest` to upsampling my feature map.

When I set `opset_version >= 10, default is 9.`, the openvino convert the onnx model sucessfully.
