### ISSUE TITLE
[Bug]Caffe Model BN Custom Layer Failed with message type "mo_caffe.LayerParameter" has no field named "bn_param"

### ISSUE THREAD

**Issue by Begin0ner** [openvinotoolkit/openvino#8391]
##### Detailed description
Hello, when I convert caffemodel to IR using mo.py file, it says parse prototxt file failed because it contains custom layer.I tried adding a custom layer following an online tutorial, but the extgen.py file is not available in the OpenVino version 2021.4 that I use.I would like to ask if there is any way to solve my problem?
![image](https://user-images.githubusercontent.com/93638983/140018118-41e8ffe3-899c-4a49-824c-63d1c84c2b1a.png)

**Comment by Iffa-Meah** [comment]
Hi,

may I know which custom layer you are using? 
Currently, [listed here](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#doxid-openvino-docs-m-o-d-g-prepare-model-supported-frameworks-layers) are the supported layers.

**Comment by Begin0ner** [comment]
Thanks for your answer, the custom layer I use is BN, but hint mo_caffe.LayerParameter has no field named "bn_param"
![image](https://user-images.githubusercontent.com/93638983/140247958-5536cf01-a9c0-4e6f-9f2a-821ac9350a96.png)

**Comment by Iffa-Meah** [comment]
I suspect your issue came from the proto file,which you mention that it could not be parsed. You'll need to work on this part, which related to your native caffe model. Plus, make sure the proto is in a valid structure.

You may refer to this [Custom Python Layer for Caffe](https://sodocumentation.net/caffe/topic/10535/custom-python-layers) and try to get a proto file that match.

This is the [official OpenVINO guide](https://docs.openvino.ai/latest/openvino_docs_HOWTO_Custom_Layers_Guide.html) that might also help.

**Comment by Begin0ner** [comment]
Thanks, I will try these two methods again

**Comment by Begin0ner** [comment]
Thanks, I will try these two methods again

**Comment by Begin0ner** [comment]
Thanks, I will try these two methods again

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
