### ISSUE TITLE
Time-series classification: different shape for each element of a batch

### ISSUE THREAD

**Issue by touisteur** [openvinotoolkit/openvino#8424]
Hi,

I'm trying to classify time-series through OpenVINO, using RNN/LSTM/GRU models. I'm trying to batch inferences, and haven't found a way to have a different shape for each element of the batch.

I have this input structure:
- time-series 1 , with 15 elements
- time-series 2 , with 140 elements
- time-series 3 , with 4 elements
And would like to batch inferences for 1, 2, and 3 together.

Is there a way to define for each element of a batch a specific shape ?

Thanks in advance for your help.

**Comment by touisteur** [comment]
I'm looking for something similar to https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pack_padded_sequence.html where one can define the length of each sequence in the batch ?

**Comment by Iffa-Meah** [comment]
Hi,

You can set a new batch dimension value with the setBatchSize() method.

You may use InferenceEngine::CNNNetwork::reshape instead of InferenceEngine::CNNNetwork::setBatchSize to set new input shapes for the model if the model has one of the following:

- Multiple inputs with different zero-index dimension meanings
- 
- Input without a batch dimension
- 
- 0D, 1D, or 3D shape

For further info, you may refer [here](https://docs.openvino.ai/latest/openvino_docs_IE_DG_ShapeInference.html).

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
