### ISSUE TITLE
Question about older processors

### ISSUE THREAD

**Issue by JustasZJ** [openvinotoolkit/openvino#8471]
Hello, 

I've been able to use OpenVINO successfully in general, but I've noticed that it doesn't work for me on Windows on i7 processors of 3rd generation and earlier. Perhaps somehow AVX2 is enforced, but the processor does not support it? I would be thankful for any insight. I've compiled OpenVINO from source using the command

`cmake .. -G"Visual Studio 15 2017" -A x64 -B "build64" -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX="%OPENVINO_BASEDIR%/openvino_dist" -DENABLE_CLDNN=OFF -DENABLE_OPENCV=OFF -DENABLE_VPU=OFF -DNGRAPH_ONNX_IMPORT_ENABLE=ON -DENABLE_PYTHON=OFF -DCMAKE_CXX_COMPILER="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64" -DENABLE_SSE42=ON -DENABLE_TBB_RELEASE_ONLY=ON -DENABLE_GNA=OFF -DENABLE_MYRIAD=OFF -DENABLE_MKL_DNN=ON -DENABLE_AVX2=ON -DENABLE_AVX512F=ON   
cmake --build build64 --target install --config Release -j 8`

**Comment by brmarkus** [comment]
See the system-requirements of OpenVINO here:
https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html

For both, target and development machine it mentions "6th to 11th generation Intel Core processors".

With "Windows" you mean "MS Win10"?

**Comment by JustasZJ** [comment]
Thank you for the response. Have the system requirements increased with some of the newer versions? I believe it used to work on older processors with an older OpenVINO version.

> With "Windows" you mean "MS Win10"?

Yes

**Comment by alalek** [comment]
OpenVINO target platforms include "Intel Atom® processor with Intel® Streaming SIMD Extensions 4.2 (Intel® SSE4.2)" (from the same link above)

> -DENABLE_AVX2=ON

Try to play with this option. At least don't enforce that.
BTW, clear CMake cache / build directory between experiments.

**Comment by brmarkus** [comment]
What is the behavior you are seeing? Do you get build-errors or runtime-errors or wrong results?

Do you have a chance to use a pre-built version of OpenVINO - to make sure it's not related to your customized build (because there are so many cmake config-options, many related to CPU-instruction-sets; like do you really want to disable "ENABLE_CLDNN=OFF").
Are you sure your 3rd generation CPU/SOC do support AVX/AVX2 (as you set "-DENABLE_AVX2=ON -DENABLE_AVX512F=ON")?
Can you provide more details about your CPU/SOC (with/without embedded GPU), please (right-click on START, then select "System"; you should see something like "Processor: Intel (R) Core(TM) i7-8665U CPU @ 1.90 GHz  2.11 GHz"")?

AVX/AVX2 is definitely not a pre-requisite.

**Comment by JustasZJ** [comment]
Thank you for the follow-ups. The CPU is i7-2600. I thought that even when compiling with -DENABLE_AVX2=ON OpenVINO will only try to use AVX2 when it is supported?

**Comment by Iffa-Meah** [comment]
The [CPU i7-2600](https://ark.intel.com/content/www/us/en/ark/products/52213/intel-core-i72600-processor-8m-cache-up-to-3-80-ghz.html) is actually has been too old and only AVX1 is supported for this model.
It's suggested you build with SSE42 only, turn of AVX2 and AVX512.

**Comment by JustasZJ** [comment]
I see, thank you!
