### ISSUE TITLE
Samples on i.MX 8M

### ISSUE THREAD

**Issue by mfaccin** [openvinotoolkit/openvino#8516]
Hi!

I successfully built the openvino (following the build instructions for Raspibian) but can't run any samples or even install the openvinotoolkit. I didn't understand very well how to detect the board and run the examples.

Do you have any step-by-step guide in order to install and use the [UP AI Core X](https://up-board.org/ai-core-x/) on my system or any guidance for it? It is being required to connect on our mini PCIe for ML inference. 

More info about my system:
Variscite VAR-SOM-MX8M-MINI
NXP i.MX 8M
2Gb RAM
Operating System: Debian GNU/Linux bullseye/sid
Kernel: Linux 5.4.3-
g050b21f4b394
Architecture: arm64

Thanks in advance for your time!

**Comment by Iffa-Meah** [comment]
Hi,

Generally, there are two methods of getting OpenVINO into your system:
1. Open Source Build :[ Build on Linux System](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux)
2. Install from release package: [Install and Configure Intel® Distribution of OpenVINO™ toolkit for Linux*](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html)

If you prefer an easier process you could go for option 2.
If you intend to use Raspbian on your arm, there is a section specific for Raspbian.

Since currently, you are in option 1, you may refer to this guide for running a sample application:
[Get Started with OpenVINO™ Toolkit on Linux*](https://github.com/openvinotoolkit/openvino/wiki/GettingStarted)

Make sure you had run the install_prerequisit.sh script and the script to install drivers.

[This discussion](https://forum.up-community.org/discussion/3809/solved-problem-configuring-ai-core-x-mini-pcie-with-openvino) might also help you.

**Comment by mfaccin** [comment]
hi @Iffa-Meah , thank you for your response. I successfully built through the first option, but I can't install all requirements.

is there any version for the second option ready for my scneario? I couldn't identity any suitable one.

**Comment by Iffa-Meah** [comment]
You can't install the requirements, means that you failed running these commands?:
cd <OPENVINO_DIR>/model_optimizer/install_prerequisites
sudo ./install_prerequisites.sh


If you going to try option number 2 (Install from release package: Install and Configure Intel® Distribution of OpenVINO™ toolkit for Linux*), you may try the latest version (2021.4.1) and follow the installation steps in the guide.

Previously, there's someone successfully [configured AI core X mPcie with OpenVINO (using option 2)](https://forum.up-community.org/discussion/3809/solved-problem-configuring-ai-core-x-mini-pcie-with-openvino). He's using Ubuntu system tho.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
