### ISSUE TITLE
Convert a model from IR format to .blob format to run on Azure Percept

### ISSUE THREAD

**Issue by tsuting** [openvinotoolkit/openvino#8559]
Hello,

My goal is to convert a model from IR format to .blob format in order to run the model on Azure Percept. 
I tried with the following command. The model can be downloaded from [here](https://storage.openvinotoolkit.org/repositories/open_model_zoo/2021.4/models_bin/3/human-pose-estimation-0001/FP32/).
```
./opt/intel/openvino_2021/deployment_tools/tools/compile_tool 
    -m human-pose-estimation-0001.xml 
    -d MYRIAD 
    -ip U8 
    -VPU_NUMBER_OF_SHAVES 8 
    -VPU_NUMBER_OF_CMX_SLICES 8 
    -op FP32
```
There is no error but only warning messages. 
`E: [xLinkUsb] [     88320] [myriad_compile] usb_find_device_with_bcd:266        Library has not been initialized when loaded`

However, it didn't work on Azure Percept. I'm trying to figure out if the problem is the converted model (`.blob`) or the code on Azure Percept. Therefore, could you help me answer the following questions? 
1. Does the above command look okay?
1. Does the warning message matter?
1. Do I need to set up a configuration file? If yes, could you guide me how to do? I found  `-c                           <value>     Optional. Path to the configuration file.` on this [compile_tool page](https://docs.openvino.ai/latest/openvino_inference_engine_tools_compile_tool_README.html?highlight=compile_tool). But I'm not sure how to write this.
1. Which one should I use, `compile_tool` or `myriad_compile`? as on [the percept github page](https://github.com/microsoft/azure-percept-advanced-development/blob/main/scripts/compile_ir.sh), it's using `myriad_compile` to compile from IR to .blob not `compile_tool`.

* Environment
  * OS is Windows WSL2 Ubuntu 20.04.
  * OpenVINO docker image: `openvino/ubuntu20_dev`
  * Percept spec: Intel Movidius Myriad X (MA2085) Vision Processing Unit (VPU)

Thank you.

**Comment by Iffa-Meah** [comment]
Hi,

The VPU/NCS2 only supports FP16 precision. Therefore, you'll need to use a model that's in [FP16 format](https://storage.openvinotoolkit.org/repositories/open_model_zoo/2021.4/models_bin/3/human-pose-estimation-0001/FP16/). This might help you to understand [how to choose the right precision](https://www.youtube.com/watch?v=RF8ypHyiKrY). This is probably the main reason why your blob file didn't work.

For the input layer precision (-ip) you can use the U8 (note that it will be converted internally to FP16). However, the output layer is expected to be FP16 in this case because usually, **the output layer is the input layer of a new layer** (in the creation of the neural network). Without the definition of -op the program would automatically use FP16 as network output. The -op parameter is optional anyway.

I manage to get the blob file with the human-pose-estimation-0001 in FP16 format. Probably you could try this instead and use it to run on your Azure Percept.



![blob](https://user-images.githubusercontent.com/79643476/141748156-d72117e6-d697-4c4a-9839-3c5034703ef1.png)

**Comment by tsuting** [comment]
Hello,

Thanks for your reply and suggestion!
I found that I made a mistake on the zipped file and that's why the Percept cannot read the model. I used converted FP32 model and it works. I will check out the VPU supports as you mentioned. Thank you!
