### ISSUE TITLE
[Bug]  demo_squeezenet_download_convert_run.bat ||  Unkown model format! 

### ISSUE THREAD

**Issue by DunguTmp** [openvinotoolkit/openvino#8722]
System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => Windows 11 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: demo
- Framework: TensorFlow (if applicable)
- Model name: SqueezeNet1.1

Detailed description:
I am attempting to run the demo_squeezenet_download_convert_run.bat demo on Windows11. 
When the program executes to the following command line：

classification_sample_async.exe -i "C:\Program FIles (x86)\Inte\openvino_2021\deployment_tools\demo\car.png" -m "C:\Users\dungu\Documnets\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1.xml" -d CPU
 
I got the following error:

[ERROR] Unkown model format! Cannot find reader for model format: xml and read the model: C:\Users\dungu\Documnets\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1.xml. Please check that reader library exists in your PATH.
Error.

PS: I can run this demo successfully on Windows 10.

Any help would be appreciated.

**Comment by zulkifli-halim** [comment]
Hello @DunguTmp, it seems like there is a typo in your directory. Instead of using this command:
 classification_sample_async.exe -i "C:\Program FIles (x86)\Inte\openvino_2021\deployment_tools\demo\car.png" -m "C:\Users\dungu\ **Documnets** \Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1.xml" -d CPU

please try this command:
classification_sample_async.exe -i "C:\Program FIles (x86)\Inte\openvino_2021\deployment_tools\demo\car.png" -m "C:\Users\dungu\Documents\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1.xml" -d CPU

**Comment by zulkifli-halim** [comment]
Closing issue.
