### ISSUE TITLE
Rund benchmark Openvino using RPI

### ISSUE THREAD

**Issue by besmaGuesmi** [openvinotoolkit/openvino#8728]
Hi! I faced this problem when I ran the benchmark on RPI! any help?

```
[Step 3/11] Setting device configuration
[Step 4/11] Reading the Intermediate Representation network
[ ERROR ] Cannot create Swish layer Mul_2 id:5
Traceback (most recent call last):
  File "/opt/intel/openvino/python/python3.7/openvino/tools/benchmark/main.py", line 166, in run
    ie_network = benchmark.read_network(args.path_to_model)
  File "/opt/intel/openvino/python/python3.7/openvino/tools/benchmark/benchmark.py", line 67, in read_network
    ie_network = self.ie.read_network(xml_filename, bin_filename)
  File "ie_api.pyx", line 261, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 293, in openvino.inference_engine.ie_api.IECore.read_network
**RuntimeError: Cannot create Swish layer Mul_2 id:5**

```

**Comment by Iffa-Meah** [comment]
Hi,

which model are you using? and what topology is it? (eg: Model: Tensorflow, Topology:Inception v2)

**Comment by alalek** [comment]
Do you have "CPU" plugin in the used RPi OpenVINO package? (check plugins.xml file)

If no, then it is special package which is targeted to support MYRIAD devices (like Intel NCS2 USB stick) only.
- use "MYRIAD" device instead of CPU in benchmark_app
- or build OpenVINO from source code and include ARM CPU plugin: https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin

/cc @alvoron @vladimir-dudnik

**Comment by besmaGuesmi** [comment]
Hi, I used a YOLOv5 nanoarchitecture,  the model works fine with the same Python scripts on my computer using MYRIAD and I tested it before on RPI! I don't know where this problem comes from.

**Comment by Iffa-Meah** [comment]
From what I can see your model, topology, and layer ([Swish layer](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html)) is supported.
Did you create this custom layer or is it already been there in the YOLOV5 model since the last time it worked?
Usually, this swish activation function is [used with Keras](https://bignerdranch.com/blog/implementing-swish-activation-function-in-keras/). 

From [here](https://towardsai.net/p/computer-vision/yolo-v5%E2%80%8A-%E2%80%8Aexplained-and-demystified), it's said that the YOLOV5 is using Sigmoid activation function. While the Swish activation function = x times Sigmod function.

If you created it, I suggest you take a proper look at your code since that's the main thing your error is telling.

**Comment by zzff-sys** [comment]
Hello! I ran into the same problem when I used Yolov5s and The PyT
![AX(ASSQ3EKI XZNJ@(L}LOB](https://user-images.githubusercontent.com/71440760/142987127-ddea6ae3-65c1-4dd2-8503-e7042bf4dfd7.png)
orch framework and ran the result on raspberry PI 4 and NCS2 as follows:

**Comment by Iffa-Meah** [comment]
@zzff-sys ,

Similar to what I asked from @besmaGuesmi,

**It would be great if you could provide these:**

1. your model and also the link to the YOLOV5 nanoarchitecture source (if possible)
2. which version of OpenVINO you are using? build from source or installed from distribution?
3. In your case, it's good if you could provide your conversion details.

**Comment by zzff-sys** [comment]
Hello! I have posted some instructions to my Github project, which can be accessed as follows:
https://github.com/zzff-sys/yolov5s_demo
thank you! @ @Iffa-Meah

**Comment by alalek** [comment]
@zzff-sys 

> 2020.3.2

This is old release. Please try the latest one (e.g., 2021.4.2).

> Swish

Looks like VPU (MYRIAD) plugin brings support in 2021.1: #1612

---

(BTW, avoid posting text information through screenshots - it is ridiculous and blocks searching engines)

**Comment by zzff-sys** [comment]
@Iffa-Meah 
Thank you very much for the detailed steps you provided. According to your steps, I have been able to successfully complete and have a deep understanding of the deployment process. Thank you very much!

**Comment by besmaGuesmi** [comment]
Hi @Iffa-Meah 
I have downloaded OpenVINO20210.4 and I faced an error That openVINO is not found !! the problem is that I used this version with my script last time and worked fine! I don't understand what is the problem with the new versions!

**Comment by Iffa-Meah** [comment]
@besmaGuesmi if you faced the error of OpenVINO is not found, then definitely there's something you didn't set up properly.
Please help to follow the guide carefully.
**The yolov5 with OpenVINO is proven to work from my side and also @zzff-sys side.**

If you custom created that python script there's possibility that you need to update the script or it could be something else.
It's good if you could share the script.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
