### ISSUE TITLE
[Question] YoloV5 RPI

### ISSUE THREAD

**Issue by alexanderaltena** [openvinotoolkit/openvino#9014]
Dear devs,

Im relatively new to openvino and object detection but I've done my fair share of research the past week (which isnt nearly enough) but I was wondering if you could help me in the right direction.

When Im building the optimized model I'm getting the following output:

Inference Engine version: 	2021.4.2-3974-e2a469a3450-releases/2021/4
Model Optimizer version: 	2021.4.2-3974-e2a469a3450-releases/2021/4
[ WARNING ]  Const node 'Resize_138/Add' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Const node 'Resize_117/Add' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Changing Const node 'Resize_117/Add' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ WARNING ]  Changing Const node 'Resize_138/Add' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /Users/vascowerk/ir/yolov5s.xml
[ SUCCESS ] BIN file: /Users/vascowerk/ir/yolov5s.bin
[ SUCCESS ] Total execution time: 18.14 seconds. 
[ SUCCESS ] Memory consumed: 179 MB. 

I'm trying to understand the warnings (and if possible I would like to resolve them) so I was wondering if you could point me in the right direction.

Furthermore I was wondering if i could use the model on a raspberry pi4 (8gb) with the stick2 for liveObjectDetection. Any resource that would put me in the right direction would be greatly appreciated 

With kind regards

Alex

**Comment by Iffa-Meah** [comment]
Hi,

your warning is all about the data type. You don't have to worry about them since they had been automatically casted into the proper data type.

You may refer to this thread for getting the correct binary of the OpenVINO sample app (compilation) if required: [#8728](https://github.com/openvinotoolkit/openvino/issues/8728#issuecomment-976895941)

Try to run your model with the Benchmark App first and make sure It works as indicated in that thread.
Then, you may run it with the object_detection_demo.

You'll need to do the same steps as Benchmark App compilation to get the binary of the object_detection_demo:
1. clone/download the [OpenVINO Open Model Zoo repo](https://github.com/openvinotoolkit/open_model_zoo)
2. cd to open model zoo folder
3. cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=armv7-a" <locationOMZ/demo>

![cmake](https://user-images.githubusercontent.com/79643476/144806486-31c9886d-5df9-486b-9215-437efbb12e38.png)

4. make -j2 object_detection_demo

the built binary should be inside <omzpath/demo/arm7l/Release

![make](https://user-images.githubusercontent.com/79643476/144806581-42770682-f2e9-4f00-ba92-e76ae2dc7c32.png)
![make2](https://user-images.githubusercontent.com/79643476/144806700-12b5cc97-bf38-4dc3-ba25-a75590ef4ba8.png)

Infer the YOLOv5, the sample app with suitable input file and you'll get something like this:

![object_detection_sample](https://user-images.githubusercontent.com/79643476/144807070-e0f0fb70-684e-4975-9d99-41aee9f7a29e.png)

**Comment by alexanderaltena** [comment]
oh wauw thnx a lot!!

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
