### ISSUE TITLE
[Bug]Unable to convert custom trained TF Mask-Rcnn to IR 

### ISSUE THREAD

**Issue by nevoGoldamn** [openvinotoolkit/openvino#9128]
- OpenVINO => 2020.4.582
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Model Conversion
- Framework: TensorFlow 
- Model name: mask_rcnn_inception_resnet_v2_1024x1024_coco17

##### Detailed description
 have been trying to convert the model using the above script, but every time I got the error:

"Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class'extensions.front.tf.tensorflow_custom_operations_config_update.TensorflowCustomOperationsConfigUpdate'>)": The function 'update_custom_layer_attributes' must be implemented in the sub-class."

I have exported the graph using exporter_main_v2.py. If more information is needed please inform me.

##### Steps to reproduce

python mo_tf.py 
--saved_model_dir C:\DATASETS\mask50000\exports\saved_model 
--output_dir C:\DATASETS\mask50000 
--reverse_input_channels 
--tensorflow_custom_operations_config extensions\front\tf\mask_rcnn_support_api_v2.4.json
--tensorflow_object_detection_api_pipeline_config C:\DATASETS\mask50000\exports\pipeline.config 
--log_level=DEBUG

This was my script to convert the saved_model.pb
when I used the following script I got an other error : Stopped shape/value propagation at "input_tensor" node.

python mo_tf.py --saved_model_dir C:\DATASETS\mask50000\exports\saved_model --output_dir C:\DATASETS\mask50000      

I got the same error even when adding --input_shape...

(the site don't allow to upload the saved_model.pb...)

**Comment by zulkifli-halim** [comment]
Hi @nevoGoldamn, OpenVINO 2020.4 is not compatible with TensorFlow 2. Support for TF 2.0 Object Detection API models was fully enabled only in OpenVINO 2021.3.

I’ve successfully converted the model [mask_rcnn_inception_resnet_v2_1024x1024_coco17](http://download.tensorflow.org/models/object_detection/tf2/20200711/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8.tar.gz) to IR using the latest OpenVINO release (2021.4.752). 

![image](https://user-images.githubusercontent.com/79680111/145569809-c9d7c31f-5a29-4867-a9de-eceb584c8658.png)

I share the MO conversion command here:

_python mo_tf.py --saved_model_dir <Saved_model_dir>\saved_model --tensorflow_object_detection_api_pipeline_config <Pipeline_dir>\pipeline.config --transformations_config <Installed_dir>\extensions\front\tf\mask_rcnn_support_api_v2.0.json"_

I used _mask_rcnn_support_api_v2.0.json_ since [ TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md#tensorflow-2-detection-model-zoo) models were trained using TensorFlow 2.2.

**Comment by nevoGoldamn** [comment]
Hi @zulkifli-halim I too was able to successfully convert the model mask_rcnn_inception_resnet_v2_1024x1024_coco17 to IR using the latest OpenVINO release (2021.4.752).

but I still get an error whilst trying to convert my model (by using the same MO command): 
 Exception occurred during running replacer "ObjectDetectionAPIPreprocessor2Replacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIPreprocessor2Replacement'>)

 assert len(start_nodes) >= 1
AssertionError

I have added my config file. If there are other files I need to share please advise.
[pipeline.zip](https://github.com/openvinotoolkit/openvino/files/7696727/pipeline.zip)

Thank you.

**Comment by zulkifli-halim** [comment]
@nevoGoldamn. Please share with us your custom model for replication purposes. If you cannot post it here, you can send it to me on my email zulkiflix.bin.abdul.halim@intel.com

**Comment by nevoGoldamn** [comment]
Hi, @zulkifli-halim I managed to solve the problem by changing the mask_rcnn_support_api_v2.4.json file. Thank you.
