### ISSUE TITLE
how to initialize openvino installed from pypi on windwos

### ISSUE THREAD

**Issue by leqiao-1** [openvinotoolkit/openvino#9250]
Hi. I installed OpenVino with command `pip install openvino-dev` instead of exe installer on Windows. How can I initialize OpenVino and setup environment variables, since there is not bin/setupvars.bat in the package installation directory. Thanks.

**Comment by Iffa-Meah** [comment]
Hi,

You won't need to init the setupvars.bat for this installation method. 

create & init virtual env in python
![env](https://user-images.githubusercontent.com/79643476/146480361-bbbb10db-4032-4e5e-94f9-1a1a3bb43f8e.png)

mo -h (test run the model optimizer)
![mo_test](https://user-images.githubusercontent.com/79643476/146480427-fda2c99f-635c-4b7b-a08f-64a50a39623f.png)

benchmark_app -h (test run benchmark app)
![benchmark_test](https://user-images.githubusercontent.com/79643476/146480484-2d4e2cbf-a7e1-427c-9877-c7f7380c6120.png)

python -c "from openvino.inference_engine import IECore" (test OpenVINO IE)
![IE_test](https://user-images.githubusercontent.com/79643476/146480560-4762291b-cabc-4bb5-89a1-14fef534710d.png)


Make sure you didn't encounter any errors when running those commands.
You may refer to [this documentation](https://pypi.org/project/openvino-dev/) to see which **components are installed by default**. You should be able to use them directly without the initialization of setupvars.

For inferencing purpose, since this is meant for developer/development purposes, you'll need to create your own scripts/code with the utilization of OpenVINO IE libraries as the example I had shown above.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by Lin-333** [comment]
HELLO,my Openvino does not work properly after downloading via pip.
Hi, I downloaded this library in pycharm terminal via pip install openvino, but I get an error when I run the project.
F:\Anaconda\envs\xxxxxxx\lib\site-packages\openvino\inference_engine\__init__.py", line 30, in <module>
    from .ie_api import *
ImportError: DLL load failed while importing ie_api: 找不到指定的模块(The specified module cannot be found)
my python version 3.9   , Windows 11
Please, how can I solve this problem?Thanks.

**Comment by Lin-333** [comment]
HELLO,my Openvino does not work properly after downloading via pip.
Hi, I downloaded this library in pycharm terminal via pip install openvino, but I get an error when I run the project.
F:\Anaconda\envs\xxxxxxx\lib\site-packages\openvino\inference_engine_init_.py", line 30, in
from .ie_api import *
ImportError: DLL load failed while importing ie_api: The specified procedure could not be found
my python version 3.9 , Windows 11
Please, how can I solve this problem?Thanks
@Iffa-Meah @Munesh-Intel

**Comment by brmarkus** [comment]
See the section "System Requirements" on page "https://pypi.org/project/openvino/"; Python in version v3.9 seems not supported. Can you use Python in v3.8 instead, e.g. via a (e.g. conda) virtual environment?

**Comment by Lin-333** [comment]
hello，I created a python 3.8 virtual environment with conda, and after using "pip install openvino" again, I still get the same error. How do I fix it? Looking forward to your reply!
@brmarkus @Iffa-Meah @leqiao-1

**Comment by brmarkus** [comment]
Hmm, I'm not using MS-Win11, but MS-Win10.
I'm doing it like this (I'm still using Python v3.7 in one of my projects currently):
$> conda create --name hello python=3.7
$> conda activate hello
Then, in my current project, I even need another Python virtual-env:

$> python --version
Which version do you see?

$> python3 -m venv hello2
$> hello2\Scripts\activate.bat

Then I install all dependencies:
$> pip install -U -r requirements.txt

The file "requirements.txt" contains "openvino==2021.4.2" and others. Can you install OpenVINO with a specific version, like "openvino==2021.4.2"?

How does your test-application look like?

A quick test could be something like this in the console, without a real Python application:

$> python -c "from openvino.inference_engine import IECore"
