### ISSUE TITLE
Opencv4.5.4 Inference result error

### ISSUE THREAD

**Issue by XiangMichael** [openvinotoolkit/openvino#9347]
##### System information (version)

When testing yolov3, when the inference width and height values are set differently, the inference result is wrong. For example, when inpWidth=480, inpHeight=320, the inference result is wrong; when inpWidth=320, inpHeight=320, the inference result is correct

**Comment by Iffa-Meah** [comment]
This is actually more related to your native YOLOv3 model instead of OpenVINO.
In order to overcome this issue, you'll need to train your data for non-square images.
This discussion thread might be useful to you: https://github.com/ultralytics/yolov3/issues/126
and here is the tutorial for YOLOv3 non-square images: https://github.com/ultralytics/yolov3/issues/232

If you are looking for a solution within OpenVINO, you may try to use the Reshape Inference Feature to change your model's input shape. You may refer to this [Reshape Inference Feature documentation](https://docs.openvino.ai/latest/openvino_docs_IE_DG_ShapeInference.html?sw_type=switcher-python).

**Comment by alalek** [comment]
OpenCV ticket is here: https://github.com/opencv/opencv/issues/19781

**Comment by XiangMichael** [comment]
> OpenCV ticket is here: [opencv/opencv#19781](https://github.com/opencv/opencv/issues/19781)
When I did it according to [opencv/opencv#19781](https://github.com/opencv/opencv/issues/19781), when "backendId = CV ::DNN ::DNN_BACKEND_INFERENCE_ENGINE,  TargetId = CV ::DNN ::DNN_TARGET_CPU "Running result is normal, but" backendId = CV ::DNN ::DNN_BACKEND_INFERENCE_ENGINE,  TargetId = CV ::DNN ::DNN_TARGET_OPENCL_FP16 "will crash directly

**Comment by XiangMichael** [comment]
> This is actually more related to your native YOLOv3 model instead of OpenVINO. In order to overcome this issue, you'll need to train your data for non-square images. This discussion thread might be useful to you: [ultralytics/yolov3#126](https://github.com/ultralytics/yolov3/issues/126) and here is the tutorial for YOLOv3 non-square images: [ultralytics/yolov3#232](https://github.com/ultralytics/yolov3/issues/232)
> 
> If you are looking for a solution within OpenVINO, you may try to use the Reshape Inference Feature to change your model's input shape. You may refer to this [Reshape Inference Feature documentation](https://docs.openvino.ai/latest/openvino_docs_IE_DG_ShapeInference.html?sw_type=switcher-python).

When I did it according to [opencv/opencv#19781](https://github.com/opencv/opencv/issues/19781), when "backendId = CV ::DNN ::DNN_BACKEND_INFERENCE_ENGINE,  TargetId = CV ::DNN ::DNN_TARGET_CPU "Running result is normal, but" backendId = CV ::DNN ::DNN_BACKEND_INFERENCE_ENGINE,  TargetId = CV ::DNN ::DNN_TARGET_OPENCL_FP16 "will crash directly

**Comment by jgespino** [comment]
Hi @XiangMichael 

Apologies for the delay, is this something you are still working on? If so, please share your model and sample code to reproduce the issue. 

Regards,
Jesus
