### ISSUE TITLE
wrong metric key in GetMetric function example

### ISSUE THREAD

**Issue by SummerZ2020** [openvinotoolkit/openvino#9531]
The key value should be AVAILABLE_DEVICES not myriadDevices in [https://docs.openvino.ai/2021.1/openvino_docs_IE_DG_supported_plugins_MULTI.html]
Here is the screenshot:

![image](https://user-images.githubusercontent.com/59429566/148727155-a7ce6bc9-64b0-4716-8eaf-f7530736afd8.png)

**Comment by jgespino** [comment]
Hi @SummerZ2020 

This typo is fixed in the [latest](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_MULTI.html) documentation, the link you shared is for 2021.1 release. 

![image](https://user-images.githubusercontent.com/18014973/148809302-ce4e8929-a3d8-41ab-9521-91029231b8ac.png)

Regards,
Jesus

**Comment by SummerZ2020** [comment]
> 
Thanks for your clarification. I am sorry for the misunderstand.
