### ISSUE TITLE
(Failed to initialize Inference Engine backend (device = GPU)

### ISSUE THREAD

**Issue by husiluanxiang** [openvinotoolkit/openvino#9658]
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.2) Error: Unspecified error (Failed to initialize Inference Engine backend (device = GPU): Ngraph operation Reshape with name 71 has dynamic output shape on 0 port, but CPU plug-in supports only static shape) in cv::dnn::InfEngineNgraphNet::initPlugin, file D:\opencv\sources\modules\dnn\src\ie_ngraph.cpp, line 718
![image](https://user-images.githubusercontent.com/38007233/149461391-6b7327c8-4600-40fc-9efc-6ee35a15c609.png)

how to solve it

**Comment by alalek** [comment]
> OpenCV(4.5.2)

This version is outdated.

> Ngraph operation Reshape with name 71 has dynamic output shape on 0 port, but CPU plug-in supports only static shape

OpenCV team observing simimar issues with OpenVINO 2021.4.x (search for "has dynamic output shape" in `<opencv>/modules/dnn/test`). 
Some of these problems have been resolved on the master branch of OpenVINO (upcoming 2022.1 release)

Another workaround: try to use OpenVINO API for DL inference instead of OpenCV DNN.
OpenVINO is able to import ONNX models without IR stage, see [here](https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_OnnxImporterTutorial.html)

**Comment by husiluanxiang** [comment]
I also have a problem I use opencv to infrerence crnn but when I process program I find the time is almost same,when I use backend opencv and INFERENCE_ENGINE
![image](https://user-images.githubusercontent.com/38007233/149466761-28d9a058-ae07-4961-9793-8005c54a4e09.png)
![image](https://user-images.githubusercontent.com/38007233/149466877-9209c6cc-5874-426a-bd06-5bf6d57a496e.png)

**Comment by husiluanxiang** [comment]
![image](https://user-images.githubusercontent.com/38007233/149467264-7b7cc2f3-b236-49c8-8b50-16ee4fcc2f98.png)
![image](https://user-images.githubusercontent.com/38007233/149467330-909bcf2e-4976-4065-a588-197770741a72.png)
but when I use the example example_dnn_classification.exe I can get a good result .I dont understand  why crnn and googlenet ,its result so different.

**Comment by husiluanxiang** [comment]
how can I know I use or use not DNN_BACKEND_INFERENCE_ENGINE

**Comment by avitial** [comment]
@husiluanxiang apologies for the delay in my response, you stated with example_dnn_classification you get a good result but with crnn and googlenet results are different, have you tried to use OpenVINO API for inference instead of DNN as previously suggested? And if so, are the results any better or do you still face the same issue previously reported?

BR,
Luis

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
