### ISSUE TITLE
minor [Bug] in demo script launchers

### ISSUE THREAD

**Issue by ChrisArnault** [openvinotoolkit/openvino#9727]
My Configuration:

- OpenVINO openvino_2021.4.752
- System Windows 10 64 bits
- MBUILD 17 2022
- Python 3.8
- Target MYRIAD Neural Compute Stick 2

I have installed OpenVINO I have found **minor** issues in the 

- **bin\setupvars.bat**>  My Python Installation was not standard, I had to manually specify PATH before calling setupvars.bat

- **deployment_tools\demo\*.bat**> 
  1) I had to add knowledge of MSBUILD version adding:

       if not "!MSBUILD_BIN:2022=!"=="!MSBUILD_BIN!" set "MSBUILD_VERSION=17 2022"

   2) the temporary area to build intermediate files (BUILD_FOLDER) aimed by default at a protected location thus I added one argument to all scripts so as to accept user defined area:

    if "%1"=="-temp" {
        set BUILD_FOLDER=%2
        echo Temp = %BUILD_FOLDER%
	shift
    }

**Comment by Iffa-Meah** [comment]
Hi,

for Python, it is recommended to "tick" the option for adding Python 3.x to PATH during installation. This would avoid any issues afterward especially when using Python through CMD. Otherwise, situation like yours could happen.

![9727_python](https://user-images.githubusercontent.com/79643476/149892885-6a1c2c4b-3058-487d-9a3f-fbb63319c1a1.png)

![9727_python2](https://user-images.githubusercontent.com/79643476/149893094-7e936f5b-bb84-49cc-a337-625b3ca9d1f7.png)


"MSBUILD_VERSION=17 2022" means that you are using Visual Studio 2022 version 17. I downloaded the same VS to verify.
![9727_VS](https://user-images.githubusercontent.com/79643476/149893617-1e900d94-d4c0-410d-b7eb-46d5a046d5a6.png)

The OpenVINO Intel Distribution Toolkit installation shows that there's no VS found.
![9727_VSversion](https://user-images.githubusercontent.com/79643476/149893888-80960ebe-77d2-4ddb-a27b-538265108f61.png)

The **latest VS version that is supported by OpenVINO is 2019**. This is the reason why you need to manually add the MSBUILD version.

You may refer to the System Requirement section (Sofware) in this[ official OpenVINO guide](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_windows.html#system-requirements).

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
